### ISSUE TITLE
`arches-project create` fails with `AttributeError` for invalid names

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10018]
Instead of failing with an appropriate error, `arches-project create invalid-name` fails like this:
```py
% arches-project create invalid-name
/Users/jwalls/prj/venv39/bin/arches-project:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/Users/jwalls/prj/venv39/bin/arches-project", line 159, in <module>
    main()
  File "/Users/jwalls/prj/venv39/bin/arches-project", line 152, in main
    COMMANDS[args.command](args)
  File "/Users/jwalls/prj/venv39/bin/arches-project", line 68, in command_create_app
    cmd.handle(options)
  File "/Users/jwalls/prj/venv39/bin/arches-project", line 35, in handle
    self.validate_name(project_name, "project")
  File "/Users/jwalls/prj/venv39/lib/python3.9/site-packages/django/core/management/templates.py", line 275, in validate_name
    app=self.app_or_project,
AttributeError: 'ArchesCommand' object has no attribute 'app_or_project'
```

**Comment by jacobtylerwalls** [comment]
Turned out to be the same fix as #10759 / #10166
