### ISSUE TITLE
Deleting all files from tile raises TypeError

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10057]
1. Resource Editor: find a file-list node, submit a valid file
2. Add
3. Click "x" to delete the file from dropzone widget
4. Save edits

Result:
```py
2023-09-21 08:51:06 2023-09-21 12:51:06,693 arches.app.views.tile ERROR    Unable to save. [Tile id: 7b9dc8e0-6be9-4f0d-b9fe-2cde540e3f37]                      [Exception message: 'NoneType' object is not subscriptable]                      [Exception trace: Traceback (most recent call last):
2023-09-21 08:51:06   File "/web_root/arches/arches/app/views/tile.py", line 144, in post
2023-09-21 08:51:06     tile.save(request=request, transaction_id=transaction_id)
2023-09-21 08:51:06   File "/web_root/arches/arches/app/models/tile.py", line 453, in save
2023-09-21 08:51:06     self.datatype_post_save_actions(request)
2023-09-21 08:51:06   File "/web_root/arches/arches/app/models/tile.py", line 378, in datatype_post_save_actions
2023-09-21 08:51:06     datatype.post_tile_save(self, nodeid, request)
2023-09-21 08:51:06   File "/web_root/arches/arches/app/datatypes/datatypes.py", line 1583, in post_tile_save
2023-09-21 08:51:06     if previously_saved_tile_data[nodeid] is not None:
2023-09-21 08:51:06 TypeError: 'NoneType' object is not subscriptable
```
Version: 7.5

**Comment by jacobtylerwalls** [comment]
Fixed in #10115
