### ISSUE TITLE
'types.SimpleNamespace' object has no attribute 'pk'

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10072]
After #9753, there's an error when uploading a file:

```py
2023-09-25 15:39:22 2023-09-25 14:39:22,631 arches.app.views.tile ERROR    Unable to save. [Tile id: 32efc8cb-6ad7-46cc-aedf-385f59786d98]                      [Exception message: 'types.SimpleNamespace' object has no attribute 'pk']                      [Exception trace: Traceback (most recent call last):
2023-09-25 15:39:22   File "/web_root/arches/arches/app/views/tile.py", line 144, in post
2023-09-25 15:39:22     tile.save(request=request, transaction_id=transaction_id)
2023-09-25 15:39:22   File "/web_root/arches/arches/app/models/tile.py", line 452, in save
2023-09-25 15:39:22     self.validate([], request=request)
2023-09-25 15:39:22   File "/web_root/arches/arches/app/models/tile.py", line 341, in validate
2023-09-25 15:39:22     error = datatype.validate(value, node=node, strict=strict, request=request)
2023-09-25 15:39:22   File "/web_root/arches/arches/app/datatypes/datatypes.py", line 1483, in validate
2023-09-25 15:39:22     file_type_errors = errors + self.validate_file_types(request, str(node.pk))
2023-09-25 15:39:22 AttributeError: 'types.SimpleNamespace' object has no attribute 'pk'
2023-09-25 15:39:22 ]
2023-09-25 15:39:22 Internal Server Error: /arches/tile
```

#### Version ####
7.4 dev (unreleased)

**Comment by jacobtylerwalls** [comment]
Closed in #10075
