### ISSUE TITLE
Arches dev/7.5.x project problems in drop and recreate DB (relates to Arches for Science)

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#10167]
I'm working on getting set up with more recent versions of Arches for Science, and I seem to have some problems with projects created in Arches dev/7.5.x

My project "afs_plocal" was created by Arches dev/7.5.x without any obvious error. However, I get a bunch of errors when trying to drop and recreate the database:

```
arches                | WARNINGS:
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media' in the STATICFILES_DIRS setting does not exist.
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media/build' in the STATICFILES_DIRS setting does not exist.
arches                | Drop and recreate the database...
arches                |
arches                | SELECT pg_terminate_backend(pid) FROM pg_stat_activity
arches                |     WHERE datname IN ('afs_plocal', 'template_postgis');
arches                |
arches                | DROP DATABASE IF EXISTS afs_plocal;
arches                |
arches                | CREATE DATABASE afs_plocal
arches                |     WITH OWNER = postgres
arches                |         ENCODING = 'UTF8'
arches                |         CONNECTION LIMIT=-1
arches                |         TEMPLATE = template_postgis;
arches                |
arches                | deleting index : afs_plocal_terms
arches                | deleting index : afs_plocal_concepts
arches                | deleting index : afs_plocal_resources
arches                | deleting index : afs_plocal_resource_relations
arches                | creating index : afs_plocal_terms
arches                | creating index : afs_plocal_concepts
arches                | Skipping datatype mappings because the datatypes table is not yet available
arches                | creating index : afs_plocal_resources
arches                | Traceback (most recent call last):
arches                |   File "/arches_app/afs_plocal/manage.py", line 30, in <module>
arches                |     execute_from_command_line(sys.argv)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
arches                |     utility.execute()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
arches                |     self.fetch_command(subcommand).run_from_argv(self.argv)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
arches                |     self.execute(*args, **cmd_options)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
arches                |     output = self.handle(*args, **options)
arches                |   File "/arches_app/arches/arches/management/commands/setup_db.py", line 54, in handle
arches                |     self.setup_db(development=options["dev"])
arches                |   File "/arches_app/arches/arches/management/commands/setup_db.py", line 197, in setup_db
arches                |     management.call_command("migrate")
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 194, in call_command
arches                |     return command.execute(*args, **defaults)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
arches                |     output = self.handle(*args, **options)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
arches                |     res = handle_func(*args, **kwargs)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 117, in handle
arches                |     executor = MigrationExecutor(connection, self.migration_progress_callback)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
arches                |     self.loader = MigrationLoader(self.connection)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
arches                |     self.build_graph()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 229, in build_graph
arches                |     self.load_disk()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 120, in load_disk
arches                |     migration_module = import_module(migration_path)
arches                |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
arches                |     return _bootstrap._gcd_import(name[level:], package, level)
arches                |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
arches                |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
arches                |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
arches                |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
arches                |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
arches                |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 93, in <module>
arches                |     class Migration(migrations.Migration):
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 745, in Migration
arches                |     migrations.RunSQL(get_sql_string_from_file(os.path.join(settings.ROOT_DIR, "db", "dml", "db_data.sql")), ""),
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 17, in get_sql_string_from_file
arches                |     with codecs.open(pathtofile, encoding="utf-8") as f:
arches                |   File "/usr/lib/python3.10/codecs.py", line 906, in open
arches                |     file = builtins.open(filename, mode, buffering)
arches                | FileNotFoundError: [Errno 2] No such file or directory: '/arches_app/afs_plocal/afs_plocal/db/dml/db_data.sql'
arches                |
arches                | 2023-10-19 22:52:27,034 arches.app.utils.compatibility WARNING  A minimum Arches version is not specified. Unable to check minimum version project compatibility
arches                | 2023-10-19 22:52:27,034 arches.app.utils.compatibility WARNING  A maximum Arches version is not specified. Unable to check maximum version project compatibility
arches                | System check identified some issues:
arches                |
arches                | WARNINGS:
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media' in the STATICFILES_DIRS setting does not exist.
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media/build' in the STATICFILES_DIRS setting does not exist.
arches                | Traceback (most recent call last):
arches                |   File "/arches_app/afs_plocal/manage.py", line 30, in <module>
arches                |     execute_from_command_line(sys.argv)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
arches                |     utility.execute()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
arches                |     self.fetch_command(subcommand).run_from_argv(self.argv)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
arches                |     self.execute(*args, **cmd_options)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
arches                |     output = self.handle(*args, **options)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
arches                |     res = handle_func(*args, **kwargs)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 117, in handle
arches                |     executor = MigrationExecutor(connection, self.migration_progress_callback)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
arches                |     self.loader = MigrationLoader(self.connection)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
arches                |     self.build_graph()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 229, in build_graph
arches                |     self.load_disk()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 120, in load_disk
arches                |     migration_module = import_module(migration_path)
arches                |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
arches                |     return _bootstrap._gcd_import(name[level:], package, level)
arches                |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
arches                |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
arches                |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
arches                |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
arches                |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
arches                |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 93, in <module>
arches                |     class Migration(migrations.Migration):
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 745, in Migration
arches                |     migrations.RunSQL(get_sql_string_from_file(os.path.join(settings.ROOT_DIR, "db", "dml", "db_data.sql")), ""),
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 17, in get_sql_string_from_file
arches                |     with codecs.open(pathtofile, encoding="utf-8") as f:
arches                |   File "/usr/lib/python3.10/codecs.py", line 906, in open
arches                |     file = builtins.open(filename, mode, buffering)
arches                | FileNotFoundError: [Errno 2] No such file or directory: '/arches_app/afs_plocal/afs_plocal/db/dml/db_data.sql'

arches                |
arches                | 2023-10-19 22:52:28,687 arches.app.utils.compatibility WARNING  A minimum Arches version is not specified. Unable to check minimum version project compatibility
arches                | 2023-10-19 22:52:28,687 arches.app.utils.compatibility WARNING  A maximum Arches version is not specified. Unable to check maximum version project compatibility
arches                | System check identified some issues:
arches                |
arches                | WARNINGS:
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media' in the STATICFILES_DIRS setting does not exist.
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media/build' in the STATICFILES_DIRS setting does not exist.
arches                | operation: load_package
arches                | loading ontologies
arches_db             | 2023-10-19 22:52:30.880 PST [87] ERROR:  relation "ontologies" does not exist at character 22
arches_db             | 2023-10-19 22:52:30.880 PST [87] STATEMENT:  SELECT 1 AS "a" FROM "ontologies" WHERE "ontologies"."ontologyid" = '0b1f5462-faa7-11e9-8f09-3af9d3b32b71'::uuid LIMIT 1
arches                | Traceback (most recent call last):
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
arches                |     return self.cursor.execute(sql, params)
arches                | psycopg2.errors.UndefinedTable: relation "ontologies" does not exist
arches                | LINE 1: SELECT 1 AS "a" FROM "ontologies" WHERE "ontologies"."ontolo...
arches                |                              ^
arches                |
arches                |
arches                | The above exception was the direct cause of the following exception:
arches                |
arches                | Traceback (most recent call last):
arches                |   File "/arches_app/afs_plocal/manage.py", line 30, in <module>
arches                |     execute_from_command_line(sys.argv)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
arches                |     utility.execute()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
arches                |     self.fetch_command(subcommand).run_from_argv(self.argv)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
arches                |     self.execute(*args, **cmd_options)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
arches                |     output = self.handle(*args, **options)
arches                |   File "/arches_app/arches/arches/management/commands/packages.py", line 352, in handle
arches                |     self.load_package(
arches                |   File "/arches_app/arches/arches/management/commands/packages.py", line 916, in load_package
arches                |     load_ontologies(package_location)
arches                |   File "/arches_app/arches/arches/management/commands/packages.py", line 559, in load_ontologies
arches                |     management.call_command("load_ontology", source=ontology)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 194, in call_command
arches                |     return command.execute(*args, **defaults)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
arches                |     output = self.handle(*args, **options)
arches                |   File "/arches_app/arches/arches/management/commands/load_ontology.py", line 75, in handle
arches                |     ontology_exists = models.Ontology.objects.filter(pk=configs["base_id"]).exists()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1241, in exists
arches                |     return self.query.has_results(using=self.db)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 598, in has_results
arches                |     return compiler.has_results()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
arches                |     return bool(self.execute_sql(SINGLE))
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
arches                |     cursor.execute(sql, params)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
arches                |     return super().execute(sql, params)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
arches                |     return self._execute_with_wrappers(
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
arches                |     return executor(sql, params, many, context)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
arches                |     with self.db.wrap_database_errors:
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
arches                |     raise dj_exc_value.with_traceback(traceback) from exc_value
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
arches                |     return self.cursor.execute(sql, params)
arches                | django.db.utils.ProgrammingError: relation "ontologies" does not exist
arches                | LINE 1: SELECT 1 AS "a" FROM "ontologies" WHERE "ontologies"."ontolo...

arches                | WARNINGS:
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media' in the STATICFILES_DIRS setting does not exist.
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media/build' in the STATICFILES_DIRS setting does not exist.
arches                | Traceback (most recent call last):
arches                |   File "/arches_app/afs_plocal/manage.py", line 30, in <module>
arches                |     execute_from_command_line(sys.argv)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
arches                |     utility.execute()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
arches                |     self.fetch_command(subcommand).run_from_argv(self.argv)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
arches                |     self.execute(*args, **cmd_options)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
arches                |     output = self.handle(*args, **options)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
arches                |     res = handle_func(*args, **kwargs)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 117, in handle
arches                |     executor = MigrationExecutor(connection, self.migration_progress_callback)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
arches                |     self.loader = MigrationLoader(self.connection)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
arches                |     self.build_graph()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 229, in build_graph
arches                |     self.load_disk()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 120, in load_disk
arches                |     migration_module = import_module(migration_path)
arches                |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
arches                |     return _bootstrap._gcd_import(name[level:], package, level)
arches                |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
arches                |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
arches                |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
arches                |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
arches                |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
arches                |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 93, in <module>
arches                |     class Migration(migrations.Migration):
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 745, in Migration
arches                |     migrations.RunSQL(get_sql_string_from_file(os.path.join(settings.ROOT_DIR, "db", "dml", "db_data.sql")), ""),
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 17, in get_sql_string_from_file
arches                |     with codecs.open(pathtofile, encoding="utf-8") as f:
arches                |   File "/usr/lib/python3.10/codecs.py", line 906, in open
arches                |     file = builtins.open(filename, mode, buffering)
arches                | FileNotFoundError: [Errno 2] No such file or directory: '/arches_app/afs_plocal/afs_plocal/db/dml/db_data.sql'
arches                |
arches                | ----- RUNNING CREATE CACHETABLE -----
arches                |
arches                |
arches                | ----- *** RUNNING DJANGO DEVELOPMENT SERVER *** -----
arches                |
arches                | Running DEBUG mode Django
arches                | Watching for file changes with StatReloader
arches                | Performing system checks...
arches                |
arches                | 2023-10-19 22:52:55,235 arches.app.utils.compatibility WARNING  A minimum Arches version is not specified. Unable to check minimum version project compatibility
arches                | 2023-10-19 22:52:55,235 arches.app.utils.compatibility WARNING  A maximum Arches version is not specified. Unable to check maximum version project compatibility
arches                | System check identified some issues:
arches                |
arches                | WARNINGS:
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media' in the STATICFILES_DIRS setting does not exist.
arches                | ?: (staticfiles.W004) The directory '/arches_app/afs_plocal/afs_plocal/app/media/build' in the STATICFILES_DIRS setting does not exist.
arches                |
arches                | System check identified 2 issues (1 silenced).
arches                | Exception in thread django-main-thread:
arches                | Traceback (most recent call last):
arches                |   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
arches                |     self.run()
arches                |   File "/usr/lib/python3.10/threading.py", line 953, in run
arches                |     self._target(*self._args, **self._kwargs)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
arches                |     fn(*args, **kwargs)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 136, in inner_run
arches                |     self.check_migrations()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 574, in check_migrations
arches                |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
arches                |     self.loader = MigrationLoader(self.connection)
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
arches                |     self.build_graph()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 229, in build_graph
arches                |     self.load_disk()
arches                |   File "/root/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 120, in load_disk
arches                |     migration_module = import_module(migration_path)
arches                |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
arches                |     return _bootstrap._gcd_import(name[level:], package, level)
arches                |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
arches                |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
arches                |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
arches                |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
arches                |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
arches                |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 93, in <module>
arches                |     class Migration(migrations.Migration):
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 745, in Migration
arches                |     migrations.RunSQL(get_sql_string_from_file(os.path.join(settings.ROOT_DIR, "db", "dml", "db_data.sql")), ""),
arches                |   File "/arches_app/arches/arches/app/models/migrations/0001_initial.py", line 17, in get_sql_string_from_file
arches                |     with codecs.open(pathtofile, encoding="utf-8") as f:
arches                |   File "/usr/lib/python3.10/codecs.py", line 906, in open
arches                |     file = builtins.open(filename, mode, buffering)
arches                | FileNotFoundError: [Errno 2] No such file or directory: '/arches_app/afs_plocal/afs_plocal/db/dml/db_data.sql'
```

**Comment by jacobtylerwalls** [comment]
Hey @ekansa. Looks like your `ROOT_DIR` is pointing to `/arches_app/afs_plocal/afs_plocal/`, when it should be pointing to your core arches install.

My DISCO installation looks like:
```py
root@f5ace64eec45:/web_root/disco# python3 manage.py shell
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from django.conf import settings

In [2]: settings.ROOT_DIR
Out[2]: '/web_root/arches/arches'
```

Can you trace where your settings.ROOT_DIR is being created? We may need to update the settings.py template used by `arches-project create`.

I'd also be in favor of removing this try/except in the template to make things easier to debug (and since we truly depend on these settings being imported now):
https://github.com/archesproject/arches/blob/d084723fd602d81cc88f357162878fc27e5a069c/arches/install/arches-templates/project_name/settings.py-tpl#L13-L16

**Comment by ekansa** [comment]
@jacobtylerwalls let me investigate and get back to you!

**Comment by jacobtylerwalls** [comment]
Hey @ekansa were there any todo items remaining here after getting AfS spun up?
