### ISSUE TITLE
Exporting a branch from published model exports the whole model

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10348]
1. Create a resource model with a string node
2. Publish
3. Export the string node as a branch
4. Notice the whole model was exported. You're on the branch page.
5. Click "Unpublish Graph"

```py
[05/Dec/2023 15:51:55] "GET /graph_settings/750c0498-93b8-11ee-8917-1ea1ac521290?search=true&csrfmiddlewaretoken=%7B%7B%20csrf_token%20%7D%7D HTTP/1.1" 200 38646
[05/Dec/2023 15:51:55] "GET /notifications?unread_only=true HTTP/1.1" 200 38
2023-12-05 15:52:00,078 arches.app.views.graph ERROR    duplicate key value violates unique constraint "unique_alias_graph"
DETAIL:  Key (alias, graphid)=(string_node, 750c0498-93b8-11ee-8917-1ea1ac521290) already exists.
Traceback (most recent call last):
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "unique_alias_graph"
DETAIL:  Key (alias, graphid)=(string_node, 750c0498-93b8-11ee-8917-1ea1ac521290) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jwalls/prj/arches/arches/app/views/graph.py", line 526, in post
    graph.unpublish()
  File "/Users/jwalls/prj/arches/arches/app/models/graph.py", line 1842, in unpublish
    self.save(validate=False)
  File "/Users/jwalls/prj/arches/arches/app/models/graph.py", line 511, in save
    node.save()
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/models/base.py", line 990, in _save_table
    updated = self._do_update(
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/models/base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/models/query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/jwalls/prj/release/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "unique_alias_graph"
DETAIL:  Key (alias, graphid)=(string_node, 750c0498-93b8-11ee-8917-1ea1ac521290) already exists.

Internal Server Error: /graph/750c0498-93b8-11ee-8917-1ea1ac521290/unpublish
[05/Dec/2023 15:52:00] "POST /graph/750c0498-93b8-11ee-8917-1ea1ac521290/unpublish HTTP/1.1" 500 145
```

https://github.com/archesproject/arches/assets/38668450/965b7a99-48d4-462f-8a8c-92fa50f36d48

**Comment by chrabyrd** [comment]
resolved in #10979
