### ISSUE TITLE
SyntaxError when viewing provisional edits

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10360]
View a provisional edit in the resource editor. (Click pencil icon, then click the provisional edit in the list.)

```js
VM134423:1 Uncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at eval (provisional-tile.js:98:20)
    at Array.forEach (<anonymous>)
    at ProvisionalTileViewModel.self.selectProvisionalEdit (provisional-tile.js:96:46)
    at Object.eval (eval at parseBindingsString (knockout-latest.js:1:1), <anonymous>:3:214)
    at HTMLDivElement.eval (knockout-latest.js:104:62)
    at HTMLDivElement.dispatch (jquery.min.js:2:40017)
    at v.handle (jquery.min.js:2:37988)
```

**Comment by chiatt** [comment]
Fixed in latest
