### ISSUE TITLE
Selecting "Choose a data type" from node type picker gives 500 error

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10362]
Graph Designer:
1. Create a node
2. Open node type picker, select "Choose a data type" (perhaps you just want to dismiss the picker)
3. Save Edits
```py
[06/Dec/2023 18:51:17] "GET /graph/674bda9a-fe3f-4e56-9a64-3e1c5bbe4912/get_related_nodes/abcbb522-949a-11ee-8f11-1ea1ac521290 HTTP/1.1" 200 2
Internal Server Error: /node/674bda9a-fe3f-4e56-9a64-3e1c5bbe4912
Traceback (most recent call last):
  File "/Users/jwalls/prj/arches/arches/app/datatypes/datatypes.py", line 93, in get_instance
    d_datatype = DataTypeFactory._datatypes[datatype]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "/Users/jwalls/prj/arches/arches/app/views/graph.py", line 380, in post
    graph.save(nodeid=data["nodeid"])
  File "/Users/jwalls/prj/arches/arches/app/models/graph.py", line 490, in save
    self.update_es_node_mapping(node, datatype_factory, se)
  File "/Users/jwalls/prj/arches/arches/app/models/graph.py", line 461, in update_es_node_mapping
    datatype = datatype_factory.get_instance(node.datatype)
  File "/Users/jwalls/prj/arches/arches/app/datatypes/datatypes.py", line 96, in get_instance
    d_datatype = DataTypeFactory._datatypes[datatype]
KeyError: ''
[06/Dec/2023 18:51:36] "POST /node/674bda9a-fe3f-4e56-9a64-3e1c5bbe4912 HTTP/1.1" 500 135521
```

**Comment by alexwuthrich** [comment]
Still an issue during 7.6.0 review.
