### ISSUE TITLE
Map Card fails to render

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#10401]
To reproduce - 
Create a geojson node
Change the card to a Map card
Try to create a tile using the new card

![image](https://github.com/archesproject/arches/assets/1877663/939f51ac-2ec9-4e19-bf6d-aa17400aac9c)

**Comment by jacobtylerwalls** [comment]
Works for me with the provided steps, but I can reproduce a slightly different error with:

1. Create a model, save
2. Create a geojson node, save
3. Click cards tab. You're on the map widget
5. Go to the card: change to map card
6. Discard Card Edits

```js
knockout-latest.js:20 Uncaught TypeError: geometryTypes.map is not a function
    at viewModel.read (map.js:23:30)
    at Function.xd (knockout-latest.js:59:369)
    at Function.yd (knockout-latest.js:59:66)
    at Function.ha (knockout-latest.js:58:406)
    at a.o.a.$ (knockout-latest.js:56:165)
    at new viewModel (map.js:20:32)
    at Object.eval [as createViewModel] (knockout-latest.js:92:380)
    at c (knockout-latest.js:98:333)
    at eval (knockout-latest.js:99:294)
    at eval (knockout-latest.js:91:377)
```

Seems like it's a symptom of an observable not being unwrapped.

**Comment by jacobtylerwalls** [comment]
I also get a slightly different error in this workflow:

1. Save a geojson point
2. Remove the point, save
3. View map card

```js
knockout-latest.js:20 Uncaught TypeError: Cannot read properties of null (reading '__ko_mapping__')
    at r.toJS (knockout.mapping.min.js:6:8199)
    at eval (map-editor.js:70:33)
    at Function.xd (knockout-latest.js:59:380)
    at Function.yd (knockout-latest.js:59:66)
    at Function.ha (knockout-latest.js:58:406)
    at a.o.a.$ (knockout-latest.js:56:165)
    at eval (map-editor.js:69:22)
    at Array.forEach (<anonymous>)
    at viewModel (map-editor.js:66:25)
    at new viewModel (map.js:62:24)
```

**Comment by alexwuthrich** [comment]
Still an issue during 7.6.0 release testing

**Comment by alexwuthrich** [comment]
Still an issue during 8.0 release testing
