### ISSUE TITLE
Reselecting Related Resource Map Card breaks

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10413]
https://github.com/archesproject/arches/assets/38668450/3ca05f60-b6f9-44c8-9dba-dbe459f78c50

```js
knockout-latest.js:20 Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at getNodeIds (related-resources-map.js:34:86)
    at new viewModel (related-resources-map.js:169:20)
    at Object.eval [as createViewModel] (knockout-latest.js:92:380)
    at c (knockout-latest.js:98:333)
    at eval (knockout-latest.js:99:294)
    at eval (knockout-latest.js:91:377)
    at b (knockout-latest.js:38:98)
    at MutationObserver.c (knockout-latest.js:38:136)
```

**Comment by alexwuthrich** [comment]
7.6.0 Release Testing: issue still persists as of 8/22/24
