### ISSUE TITLE
TypeError when running celery jobs

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10479]
~Have a resource/graph/descriptor function combo that produces nothing for a language in LANGUAGES (e.g. no node value in that language).~

~In other words, you want `_("Undefined")` to be returned from `get_primary_descriptor_from_nodes()`.~

~Then, take an action that causes `save_descriptors()` to be called, e.g. importing or indexing resources.~

See next comment.

```py
2023-12-28 20:22:22,871 arches.app.tasks WARNING  Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/web_root/arches/arches/app/tasks.py", line 164, in package_load_complete
    notify_completion(msg, user, notifytype_name, context)
  File "/web_root/arches/arches/app/tasks.py", line 376, in notify_completion
    notif = models.Notification.objects.create(notiftype=notif_type, message=msg, context=context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
...
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/_json.py", line 78, in getquoted
    s = self.dumps(self.adapted)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/_json.py", line 72, in dumps
    return self._dumps(obj)
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type __proxy__ is not JSON serializable
```

**Comment by jacobtylerwalls** [comment]
Actually, this doesn't have to do with `save_descriptors()`, looks like it's just coming from `package_load_complete()` when using celery:

Repro:
```py
>>> from arches.app.tasks import notify_completion
>>> from arches.app.utils.message_contexts import return_message_context
>>> from django.utils.translation import gettext as _
>>> context = return_message_context(greeting=_("abc"))
>>> msg = _("msg")
>>> notify_completion(msg, None, notiftype_name='Package Load Complete', context=context)
{'greeting': 'abc', 'closing': '', 'salutation': 'Hi', 'expiration': 'Saturday, 30 December 2023'}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type __proxy__ is not JSON serializable
```
