### ISSUE TITLE
JS error when using photo gallery card during new resource creation

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10588]
```js
knockout-latest.js:83 Uncaught Error: Unable to process binding "if: function(){return activeTab() ==='add' }"
Message: Unable to process binding "dropzone: function(){return dropzoneOptions }"
Message: Invalid `previewsContainer` option provided. Please provide a CSS selector or a plain HTML element.
    at d.getElement (dropzone-amd-module.min.js:4:42295)
    at new z (dropzone-amd-module.min.js:4:3558)
    at HTMLDivElement.eval (dropzone-amd-module.min.js:4:43793)
    at Function.each (jquery.min.js:2:3111)
    at ce.fn.init.each (jquery.min.js:2:1576)
    at e.fn.dropzone (dropzone-amd-module.min.js:4:43770)
    at init (dropzone.js:16:18)
    at eval (knockout-latest.js:83:50)
    at Object.K (knockout-latest.js:45:458)
    at eval (knockout-latest.js:83:31)
```

**Comment by jacobtylerwalls** [comment]
Will reopen if I can reproduce
