### ISSUE TITLE
ES Error when importing large graph - total fields exceeded

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#10580]
Importing a graph with a lot of nodes using the Graph Manager results in an error from ElasticSearch:

```
Traceback (most recent call last):
  File "/web_root/arches/arches/app/utils/data_management/resource_graphs/importer.py", line 128, in import_graph
    graph.save()
  File "/web_root/arches/arches/app/models/graph.py", line 510, in save
    self.update_es_node_mapping(node, datatype_factory, se)
  File "/web_root/arches/arches/app/models/graph.py", line 464, in update_es_node_mapping
    se.create_mapping("resources", body=datatype_mapping)
  File "/web_root/arches/arches/app/search/search.py", line 164, in create_mapping
    self.es.indices.put_mapping(index=index, **body)
...
elasticsearch.BadRequestError: BadRequestError(400, 'illegal_argument_exception', 'Limit of total fields [1000] has been exceeded')
```
Increasing the limit with the following command resolves the issue: 
```
curl -H "Content-Type: application/json" -XPUT http://localhost:9202/[my project name]_resources/_settings -d  "{\"index.mapping.total_fields.limit\": 2000}"
```
We may consider raising this limit to 2000 when defining the mapping if this is becomes a common issue.

**Comment by chiatt** [comment]
Haven run into this issue in over a year - closing
