### ISSUE TITLE
bulk_update() on I18n_JSON fields fails with heterogenous values

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10619]
See skipped unittest `test_bulk_update_heterogenous_values()` from #10620:

https://github.com/archesproject/arches/blob/44127d53dc8aa2bcccc8170956dc5981de618a2f/tests/localization/field_tests.py#L381-L402

Fails with:

```py
======================================================================
FAIL: test_bulk_update_heterogenous_values (tests.localization.field_tests.I18nJSONFieldBulkUpdateTests.test_bulk_update_heterogenous_values) (new_config='{}')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jwalls/prj/arches/tests/localization/field_tests.py", line 399, in test_bulk_update_heterogenous_values
    self.assertEqual(str(obj.defaultconfig), new_config_as_string)
AssertionError: '{"en": "some", "zh": "json"}' != '{}'
- {"en": "some", "zh": "json"}
+ {}


======================================================================
FAIL: test_bulk_update_heterogenous_values (tests.localization.field_tests.I18nJSONFieldBulkUpdateTests.test_bulk_update_heterogenous_values) (new_config='None')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jwalls/prj/arches/tests/localization/field_tests.py", line 399, in test_bulk_update_heterogenous_values
    self.assertEqual(str(obj.defaultconfig), new_config_as_string)
AssertionError: '{"en": "some", "zh": "json"}' != 'None'
- {"en": "some", "zh": "json"}
+ None


----------------------------------------------------------------------
Ran 19 tests in 2.432s

FAILED (failures=2)
```

**Comment by jacobtylerwalls** [comment]
This might be something that goes away when the [underlying issue](https://code.djangoproject.com/ticket/35167) in Django is solved?

**Comment by jacobtylerwalls** [comment]
Fixed in 28bb2e5401aa6b75263fdd448c85a8be48c62654
