### ISSUE TITLE
whatisthis command broken in version 7

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches#10913]
The management command `python manage.py whatisthis` used for getting information relating to uuids in Arches appears to be broken in V7, producing an output similar to the following:
```
(env3.11) samuel@DESKTOP-V8R64B6:~/arches_dev/arches_her/arches_her$ python manage.py whatisthis d17a5392-28cd-11eb-9b38-f875a44e0e11
System check identified some issues:

WARNINGS:
?: (arches.W001) Cache backend does not support rate-limiting
        HINT: Your cache: django.core.cache.backends.dummy.DummyCache
        Supported caches: ('django.core.cache.backends.memcached.PyLibMCCache', 'django.core.cache.backends.memcached.PyMemcacheCache', 'django.core.cache.backends.redis.RedisCache')
Traceback (most recent call last):
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedFunction: operator does not exist: text = uuid
LINE 1: ..._annotations" WHERE "vw_annotations"."feature_id" = 'd17a539...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samuel/arches_dev/arches_her/arches_her/manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samuel/arches_dev/arches_her/arches/arches/management/commands/whatisthis.py", line 15, in handle
    self.find_uuid(options["uuid"])
  File "/home/samuel/arches_dev/arches_her/arches/arches/management/commands/whatisthis.py", line 34, in find_uuid
    objs += ob
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/samuel/arches_dev/arches_her/env3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: operator does not exist: text = uuid
LINE 1: ..._annotations" WHERE "vw_annotations"."feature_id" = 'd17a539...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

This command was working back in version 6.

**Comment by jacobtylerwalls** [comment]
Duplicate of #10083
