### ISSUE TITLE
Use db_default for auto-UUID fields in Django 5

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10958]
When Django 5 is the minimum required version, we can just use [db_default](https://docs.djangoproject.com/en/5.0/ref/models/fields/#db-default) for database-generated UUIDs and drop our [custom implementation](https://github.com/archesproject/arches/blob/760d4826201e5ad6d87f6fd3350a86d10a318578/arches/db/migration_operations/extras.py#L109-L126), which currently throws errors if you try to `manage.py sqlmigrate`:

```py
$ manage.py sqlmigrate models 0001
Traceback (most recent call last):
  File "/Users/jwalls/prj/arches/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jwalls/django/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/jwalls/django/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jwalls/django/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jwalls/django/django/core/management/commands/sqlmigrate.py", line 38, in execute
    return super().execute(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/django/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/django/django/core/management/commands/sqlmigrate.py", line 80, in handle
    sql_statements = loader.collect_sql(plan)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/django/django/db/migrations/loader.py", line 381, in collect_sql
    state = migration.apply(state, schema_editor, collect_sql=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/django/django/db/migrations/migration.py", line 108, in apply
    schema_editor.collected_sql.append("-- %s" % operation.describe())
                                                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/prj/arches/arches/db/migration_operations/extras.py", line 126, in describe
    return "Sets default value for uuid column(s) %s in %s" % self.columns, self.table
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: not enough arguments for format string
```

**Comment by jacobtylerwalls** [comment]
Consider removing `CreateAutoPopulateUUIDField` at the same time.
