### ISSUE TITLE
 Issue with related_resources_graph visualization on Stable 7.5.2 

### ISSUE THREAD

**Issue by YuvalShafriri** [archesproject/arches#10954]
Hi, on stable 7.5.2, after adding more than one resource model that has relations and creating instances with related resources, the related_resources_graph raises an error when clicking on "related resources" in the results or clicking the * icon in the related filter tab.
**console log**
related-resources-graph.js:137 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'className')
    at dataToElement (related-resources-graph.js:137:98)
    at eval (related-resources-graph.js:324:27)
    
**Steps to Reproduce:**
- Add more than one resource model with relations.
- Create instances with related resources.
- Click on "related resources" in the results or the * icon in the related filter tab.
- Observe the error in the console log.

 **more details**   
- the resource do relate and is accessible other views, like reports
- indexing process: when deleting, setup and reindexing with it prints "deleting resource_instance_relations" but not "setup resource_instance_relations"  so it seems connected to the elasticsearch indexing (??)

 Thanks:)
 Yuval

**Comment by YuvalShafriri** [comment]
Hi, I have some additional information regarding the issue.

Now I see it doesn't happen consistently. Sometimes, after deleting, setting up, and reindexing, it does work; sometimes, it does not. I tried restarting the Django server on localhost and then running it on 0:8000 for remote access, and sometimes it works.

I am currently in a development environment and planning to move to Apache for production once I finish customizing the project.

  how could it be to ensured this works consistently?.

Thank you!
