### ISSUE TITLE
Failure in spatialview_model_tests.SpatialViewTests.setUpClass

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#11354]
As of #11101:

```
python manage.py test tests -k spatialview  --settings=tests.test_settings  --failfast --keepdb
```

```py
======================================================================
ERROR: setUpClass (tests.models.spatialview_model_tests.SpatialViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jwalls/prj/arches/tests/models/spatialview_model_tests.py", line 91, in setUpClass
    BusinessDataImporter(spatialviews_test_data_path).import_business_data()
  File "/Users/jwalls/prj/arches/arches/app/utils/data_management/resources/importer.py", line 218, in import_business_data
    reader.import_business_data(
  File "/Users/jwalls/prj/arches/arches/app/utils/data_management/resources/formats/archesfile.py", line 304, in import_business_data
    self.import_business_data_without_mapping(
  File "/Users/jwalls/prj/arches/arches/app/utils/data_management/resources/formats/archesfile.py", line 264, in import_business_data_without_mapping
    last_resource = self.save_descriptors_and_index(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/prj/arches/arches/app/utils/data_management/resources/formats/archesfile.py", line 585, in save_descriptors_and_index
    this_resource.index()
  File "/Users/jwalls/prj/arches/arches/app/models/resource.py", line 413, in index
    document, terms = self.get_documents_to_index(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/prj/arches/arches/app/models/resource.py", line 568, in get_documents_to_index
    datatype_instance.append_to_document(
  File "/Users/jwalls/prj/arches/arches/app/datatypes/datatypes.py", line 2167, in append_to_document
    self.get_relationship_display_value(ontology_property_item)
  File "/Users/jwalls/prj/arches/arches/app/datatypes/datatypes.py", line 2116, in get_relationship_display_value
    preflabel = get_preflabel_from_valueid(relationship_valueid, get_language())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/prj/arches/arches/app/models/concept.py", line 1726, in get_preflabel_from_valueid
    concept_label = se.search(index=CONCEPTS_INDEX, id=valueid)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/prj/arches/arches/app/search/search.py", line 156, in search
    return self.es.get(**kwargs).body
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/release/lib/python3.12/site-packages/elasticsearch/_sync/client/utils.py", line 446, in wrapped
    return api(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/release/lib/python3.12/site-packages/elasticsearch/_sync/client/__init__.py", line 2015, in get
    return self.perform_request(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/release/lib/python3.12/site-packages/elasticsearch/_sync/client/_base.py", line 271, in perform_request
    response = self._perform_request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/release/lib/python3.12/site-packages/elasticsearch/_sync/client/_base.py", line 352, in _perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.NotFoundError: NotFoundError(404, "{'_index': 'test_concepts', '_id': 'ac41d9be-79db-4256-b368-2f4559cfbe55', 'found': False}")

----------------------------------------------------------------------
Ran 0 tests in 1.704s

FAILED (errors=1)
```

@aj-he offered to have a look.

**Comment by aj-he** [comment]
This appears to be due to changes merged after my PR was submitted to review, at which point tests were passing.

It fails somewhere in the loading of my test data, on a new function `get_relationship_display_value`.

If I manually load my test models and data via command line I get an error on using `import_business_data` with `--defer_indexing False` parameter.

![image](https://github.com/user-attachments/assets/d6817642-fe79-4ead-88d7-f251bb49910c)

However, if I load the data but leave the indexing deferred, it loads fine. I can then run reindex_database and the data appears ok

![image](https://github.com/user-attachments/assets/57b55b54-79b8-4ec7-8041-3324509283d5)

I can see that this new function and related code talks a lot about getting labels with ontologies. My test models had no ontologies specifically set so perhaps the added functionality is missing something.

I am unsure how to update my test models and data as it does not consistently break when loading it.

Perhaps @whatisgalen could advise?

**Comment by whatisgalen** [comment]
@aj-he it looks like you're passing in `--defer_indexing False` but I don't know believe the argument parser will accept `False` after the kwarg. The default value for `defer_indexing` is already false and when you add that kwarg to the import command it sets `defer_indexing` to `True`.

**Comment by jacobtylerwalls** [comment]
Sorry, I updated the OP to include the whole trace.

**Comment by whatisgalen** [comment]
Ahh I see, so ES raises an error because that id doesn't exist because it hasn't been indexed yet -- which also makes sense why it broke when `defer_indexing` was `True`. So basically if you have `defer_indexing == True`, you also need to defer `post_save` actions. Which means that maybe `defer_indexing` shouldn't really be its own mode and should just be lumped in with `bulk` since that disables (postpones?) `post_save` actions

**Comment by jacobtylerwalls** [comment]
Now tracked in #11360
