### ISSUE TITLE
Cannot republish graph after adding parent/child nodegroup configuration

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#11570]
dev/8.0.x
Graph Designer:
- Create graph
- Create one child node
- Save edits
- Create one grandchild node
- Save edits
- Create new publication and confirm dialog
- Grandchild node: toggle "Place node(s) in separate card" to ON
- Save edits
- Create new publication and confirm dialog
```py
[23/Oct/2024 09:45:04] "POST /graph_has_unpublished_changes/5defdbf2-914d-11ef-8101-1ea1ac521291 HTTP/1.1" 200 33
2024-10-23 09:45:12,810 arches.app.views.graph ERROR    NodeGroup matching query does not exist.
Traceback (most recent call last):
  File "/Users/jwalls/django/django/db/models/fields/related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/django/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'nodegroup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jwalls/prj/arches/arches/app/views/graph.py", line 693, in post
    source_graph.update_from_editable_future_graph()
  File "/Users/jwalls/prj/arches/arches/app/models/graph.py", line 2582, in update_from_editable_future_graph
    _update_source_nodegroup_hierarchy(future_card.nodegroup)
                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/django/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/django/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwalls/django/django/db/models/query.py", line 630, in get
    raise self.model.DoesNotExist(
arches.app.models.models.NodeGroup.DoesNotExist: NodeGroup matching query does not exist.
Internal Server Error: /graph/5defdbf2-914d-11ef-8101-1ea1ac521291/publish
[23/Oct/2024 09:45:12] "POST /graph/5defdbf2-914d-11ef-8101-1ea1ac521291/publish HTTP/1.1" 500 145
```

**Comment by chiatt** [comment]
It looks like this branch needs to pull in the latest in 8. Getting the following error when I try to run the django server:
```  
File "/arches/arches/app/models/models.py", line 755, in __init__
    super(NodeGroup, self).__init__(*args, **kwargs)
  File "/python3.12/site-packages/django/db/models/base.py", line 569, in __init__
    raise TypeError(
TypeError: NodeGroup() got unexpected keyword arguments: 'grouping_node_id'
```
