### ISSUE TITLE
Import:  Import of example_source_resource.json fails if a concept scheme already exists in target Arches instance

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1412]
### Bug Report

To recreate the error, follow these steps:

1. Load authority documents from v3 HIP into Arches v4
2. Run python manage.py packages -o import_json -s 'tests/fixtures/data/example_source_resource.json'

3. Observe error message:  
(ENV)DRW-MacBook-Pro:arches4 dwuthrich$ python manage.py packages -o import_json -s 'tests/fixtures/data/example_source_resource.json'
operation: import_json
package: arches

LOADING ARCHES CONCEPT SCHEME FROM ARCHES JSON
---------------------------------------------
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/dwuthrich/arches/arches4/arches/management/commands/packages.py", line 144, in handle
    self.import_json(options['source'], options['graphs'], options['resources'], options['concepts'])
  File "/Users/dwuthrich/arches/arches4/arches/management/commands/packages.py", line 390, in import_json
    ArchesFileImporter(path).import_all()
  File "/Users/dwuthrich/arches/arches4/arches/app/utils/data_management/arches_file_importer.py", line 100, in import_all
    conceptImporter(self.reference_data)
  File "/Users/dwuthrich/arches/arches4/arches/app/utils/data_management/concepts/importer.py", line 89, in import_reference_data
    concept.save()
  File "/Users/dwuthrich/arches/arches4/arches/app/models/concept.py", line 207, in save
    subconcept.save()
  File "/Users/dwuthrich/arches/arches4/arches/app/models/concept.py", line 194, in save
    concept, created = models.Concept.objects.get_or_create(pk=self.id, defaults={'legacyoid': self.legacyoid if self.legacyoid != '' else self.id, 'nodetype_id': self.nodetype})
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 467, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 507, in _create_object_from_params
    six.reraise(*exc_info)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 499, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "concepts_legacyoid_key"
DETAIL:  Key (legacyoid)=(ADDRESS_TYPE_AUTHORITY_DOCUMENT.csv) already exists.

**Comment by ryan86** [comment]
@dwuthrich This is a more general issue with concept save. I believe we decided that if you are trying to import a concept that has the same legacyoid as an existing concept the existing concept would be updated with the contents of the incoming concept. Can you please confirm?

For import of the example_source_resource.json, I believe all concept collections required for that resource are contained within that json file. So if you have a blank rdm and import that json file it should populate your rdm with the relevant concepts.

**Comment by ryan86** [comment]
Resolution:
While importing concepts the user should have to specify what they would like to do when the importer tries to import concepts that already exist in the system. There will be two options 1.) Do not import the incoming concept, 2.) import the incoming concept and overwrite the existing concept. If no option is specified concept import will fail.

For incoming concepts with conceptids uniqueness will be defined by the conceptid (possibly the combination of conceptid and legacyoid).
For incoming concepts without conceptids uniqueness will be defined by the legacyoid.

**Comment by apeters** [comment]
concepts are now not imported as part of business data load.  A user need to load concepts (via a SKOS file) BEFORE loading business data.
