### ISSUE TITLE
Document bower requirement

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#1517]
In stepping through the development setup instructions, I get to step 7 which requires bower.  Bower (and npm etc) isn't mentioned at the top in the installation requirements.

I would consider this issue solved if https://github.com/archesproject/arches/wiki/Dev-Installation referred to https://bower.io/#install-bower

**Comment by azaroth42** [comment]
And then I get:

```
(ENV) [rsanderson@GT26940 arches (master)]$ python manage.py packages -o setup
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rsanderson/Development/getty/arches/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/rsanderson/Development/getty/arches/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rsanderson/Development/getty/arches/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/rsanderson/Development/getty/arches/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/rsanderson/Development/getty/arches/arches/management/commands/packages.py", line 28, in <module>
    from arches.app.utils.data_management.resources.importer import ResourceLoader
  File "/Users/rsanderson/Development/getty/arches/arches/app/utils/data_management/resources/importer.py", line 23, in <module>
    from formats.shpfile import ShapeReader
  File "/Users/rsanderson/Development/getty/arches/arches/app/utils/data_management/resources/formats/shpfile.py", line 5, in <module>
    from django.contrib.gis.gdal import DataSource
ImportError: cannot import name DataSource
```

```
>>> django.contrib.gis.gdal.HAS_GDAL
```

Missing library that's a default on some other systems?

**Comment by azaroth42** [comment]
Found this: http://www.kyngchaos.com/software/frameworks

**Comment by azaroth42** [comment]
After those I was up and running on MacOS :)

**Comment by chiatt** [comment]
@azaroth42  Thanks for bringing this to our attention. We'll go ahead and get bower added to the installation instructions.

**Comment by robgaston** [comment]
For what it's worth, I think the easiest way to install gdal on MacOS is w/ homebrew.  I think all of the system dependencies for arches can be installed nowadays w/ homebrew.

Here's how I installed them:
```
brew update
brew install elasticsearch
brew install postgres
brew install postgis
brew install gdal
brew install mapnik2
```

It would be nice to ultimately add an install script for MacOS along the lines of what we've got for ubuntu.

**Comment by chiatt** [comment]
I've updated the installation requirements here: https://github.com/archesproject/arches/wiki/Dev-Installation
