### ISSUE TITLE
Update (re-index) if the Resource Descriptors Function is edited after instances have been created

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1726]
### Bug Report

Editing the Resource Descriptor Function (e.g.: defining a node for the resource instance name) after existing instances of the resource exist requires re-indexing ES for the edits to take effect

**Comment by apeters** [comment]
related to #1776

**Comment by dwuthrich** [comment]
@apeters I tested as follows: 
1. Update the function to use "Keyword" (fyi, a concept) for the map pop-up description.
2. Re-index
3. Select an instance and try to edit "Keyword"
4. Note that save fails (previous to re-indexing saving keyword worked fine; reverting the function so that it does not index map pop-up on keyword resolved the problem). 

Note: error message was:  

ERROR:django.request:Internal Server Error: /tile
Traceback (most recent call last):
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/arches/app/views/tile.py", line 50, in post
    tile.save(request=request)
  File "/Users/dwuthrich/arches/arches4/arches/app/models/tile.py", line 103, in save
    self.index()
  File "/Users/dwuthrich/arches/arches4/arches/app/models/tile.py", line 138, in index
    Resource.objects.get(pk=self.resourceinstance_id).index()
  File "/Users/dwuthrich/arches/arches4/arches/app/models/resource.py", line 131, in index
    document, terms = self.get_documents_to_index(datatype_factory=datatype_factory, node_datatypes=node_datatypes)
  File "/Users/dwuthrich/arches/arches4/arches/app/models/resource.py", line 149, in get_documents_to_index
    document = JSONSerializer().serializeToPython(self)
  File "/Users/dwuthrich/arches/arches4/arches/app/utils/betterJSONSerializer.py", line 48, in serializeToPython
    return self.handle_object(obj)
  File "/Users/dwuthrich/arches/arches4/arches/app/utils/betterJSONSerializer.py", line 86, in handle_object
    return self.handle_object(getattr(object, 'serialize')())
  File "/Users/dwuthrich/arches/arches4/arches/app/models/resource.py", line 236, in serialize
    ret = JSONSerializer().handle_model(self)
  File "/Users/dwuthrich/arches/arches4/arches/app/utils/betterJSONSerializer.py", line 168, in handle_model
    data[property_name] = self.handle_object(getattr(instance, property_name))
  File "/Users/dwuthrich/arches/arches4/arches/app/models/resource.py", line 62, in map_popup
    return self.get_descriptor('map_popup')
  File "/Users/dwuthrich/arches/arches4/arches/app/models/resource.py", line 52, in get_descriptor
    return PrimaryDescriptorsFunction.get_primary_descriptor_from_nodes(self, functionConfig[0].config[descriptor])
  File "/Users/dwuthrich/arches/arches4/arches/app/functions/primary_descriptors.py", line 21, in get_primary_descriptor_from_nodes
    config['string_template'] = config['string_template'].replace('<%s>' % node.name, value)
TypeError: coercing to Unicode: need string or buffer, list found

**Comment by apeters** [comment]
@dwuthrich 
So, this issue really has nothing to do with the re-indexing work related to this ticket.  The reindexing so far works as expected.  

The issue you're seeing is when we have a list of items the system assumes it's a string and can't handle the list type.  I'll make a separate ticket for that.  In the mean time, can you re-confirm that reindexing of  resources works as intended?

**Comment by dwuthrich** [comment]
@apeters Yes, reindexing appears to work as expected.
