### ISSUE TITLE
CLI Command for Indexing Database Throws Error

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1776]
### User Story
When trying to reindex the database by using this command

`python manage.py packages -o index_database`

The following error is encountered:

```shell
(ENVv4) C:\arches\v4\arches>python manage.py packages -o index_database
operation: index_database
package: arches
deleting index : concept_labels
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "C:\arches\v4\ENVv4\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\arches\v4\ENVv4\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\arches\v4\ENVv4\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\arches\v4\ENVv4\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "C:\arches\v4\arches\arches\management\commands\packages.py", line 155, in handle
    self.index_database(package_name)
  File "C:\arches\v4\arches\arches\management\commands\packages.py", line 315, in index_database
    index_database.index_db()
  File "C:\arches\v4\arches\arches\app\utils\index_database.py", line 27, in index_db
    index_concepts()
  File "C:\arches\v4\arches\arches\app\utils\index_database.py", line 102, in index_concepts
    se.delete(index='term', body='{"query":{"bool":{"must_not":[{"constant_score":{"filter":{"missing":{"field":"value.options.conceptid"}}}}],"must":[],"should":[]}}}')
  File "C:\arches\v4\arches\arches\app\search\search.py", line 59, in delete
    raise detail
AttributeError: 'str' object has no attribute 'copy'
```

I'm calling this a critical/major/bug because I don't think there is any other way for a user to re-index the database, and this operation should be facilitated.

#### Definition of Done
This command (or another that replaces it) should allow for manual re-indexing of the database. Additionally (this is extra!) it would be nice to pass an argument through the command that would index only a specific ES index (if that makes sense, I don't actually know the v4 index structure).

#### Your Arches Information
Windows 10

**Comment by apeters** [comment]
@mradamcox to test the new command is
```python manage.py es index_database```

**Comment by mradamcox** [comment]
That command runs without error, but there are no print statements, so I don't know what is going on.
To test it, I added a resource descriptors function to a resource model, and then created a new resource (all good, name showed up in search as defined in the function). Then I changed the function, and ran this command. Refreshed the search page and the old display name is still there, even though according to #1726 this is solved. I'm probably missing something obvious, so can you advise on how best to test this?
