### ISSUE TITLE
Arches fails when trying to access Map Layer Manager

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1790]
### Bug Report

When trying to access the Map Layer Manager Arches fails with the following error:

Internal Server Error: /map_layer_manager
Traceback (most recent call last):
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/arches/app/views/map.py", line 57, in get
    map_layer = datatype.get_map_layer(node=node, preview=True)
  File "/Users/dwuthrich/arches/arches4/arches/app/datatypes/datatypes.py", line 522, in get_map_layer
    "addtomap": node.config['addToMap'],
KeyError: 'addToMap'

**Comment by robgaston** [comment]
@dwuthrich sounds like an issue w/ a specific graph (resource model) json file.  those configurations were added a couple weeks ago and when they were added we updated the json files in the repo.  I'm guessing that either
1) there has been regression in those json files (possibly because people were exporting json files from old versions of arches) or 
2) you are using a locally stored json file that is out of sync w/ the latest code.
In any event, I suspect this can be resolved by updating the resource model json in question
Did you import resource model json files from some source other than the repo?

**Comment by dwuthrich** [comment]
@robgaston Yes, testing with Annabel's HER models.  However, am now getting:

Internal Server Error: /graph/
Traceback (most recent call last):
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/arches/app/views/graph.py", line 129, in get
    root_nodes=JSONSerializer().serialize(root_nodes),
  File "/Users/dwuthrich/arches/arches4/arches/app/views/graph.py", line 52, in get_context_data
    context = super(GraphBaseView, self).get_context_data(**kwargs)
  File "/Users/dwuthrich/arches/arches4/arches/app/views/base.py", line 57, in get_context_data
    map_layer = datatype.get_map_layer(node)
  File "/Users/dwuthrich/arches/arches4/arches/app/datatypes/datatypes.py", line 325, in get_map_layer
    if not preview and node.config["layerIcon"] != "":
KeyError: 'layerIcon'

From home page and trying either search or manage data.  Will try rebuilding to see if this resolves the issue.

**Comment by dwuthrich** [comment]
FYI, its a problem if importing a resource model results in system failure.  We need to be careful of importing models if they can bring down an Arches instance

**Comment by robgaston** [comment]
@dwuthrich RE: importing bad resource models - I agree.  We should enhance our import logic to apply the default configuration values stored in the `d_datatypes` table to the node configurations if values are absent in the incoming resource model json.  This will address issues related to node configurations that the application expects.  We should apply the same idea to widget, report, and function configurations, which also have corresponding defaults that evolve w/ the application code.

**Comment by ryan86** [comment]
I see this and can work on it. I think for json fields(most of our config fields) in particular because they are schema-less it would also maybe be good to check for the keys in the application code too.

**Comment by dwuthrich** [comment]
@ryan86 Resolving this would be great (otherwise we risk losing a fair amount of Annabel's work).  Is this a quick fix or will it take time?

**Comment by robgaston** [comment]
@ryan86 I agree we should strive to handle for this in the application code as well.  In this case, though, a small amount of code added to the import here can save us from changing a lot of other code and doing a lot of extra QA.  It should be a simple change - let me know if you have any questions.

**Comment by dwuthrich** [comment]
In the meantime, I'm just copying valid config data for the geojson geometry data type from a model that I know works

**Comment by dwuthrich** [comment]
FYI, this resolved the issue

**Comment by dwuthrich** [comment]
meets requirements
