### ISSUE TITLE
RDM does not allow special characters

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#1917]
### Bug Report
I have imported the sample Concepts provided in arches/db/schemes/arches_concept_scheme.rdf

From the RDM: When opening the 'Façade' concept (under Arches -> Component Type), the pane on the right of the Thesauri list turns empty, except for a "Loading..." message. Nothing else happens.

Stack trace in the console displays:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 65: ordinal not in range(128)
```

#### Expected Behavior
Open the concept edit page for Facade. 

#### Current Behavior
Stack trace displayed in my console output:

```
cvast-arches            | [30/Mar/2017 13:38:34] "GET /concepts/3f106c9f-c4a2-42ee-829b-1d76370a660f?f=html&mode=semantic HTTP/1.1" 200 54244
cvast-arches            | Internal Server Error: /concepts/27bec21b-6782-4794-b9d9-f5c141bf1808
cvast-arches            | Traceback (most recent call last):
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
cvast-arches            |     response = self.process_exception_by_middleware(e, request)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
cvast-arches            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
cvast-arches            |     return view_func(request, *args, **kwargs)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/arches/app/views/concept.py", line 146, in concept
cvast-arches            |     'direct_parents': [parent.get_preflabel(lang=lang) for parent in concept_graph.parentconcepts]
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
cvast-arches            |     template_name, context, request=request, using=using)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
cvast-arches            |     return template.render(context, request)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
cvast-arches            |     return self.template.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
cvast-arches            |     return self._render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
cvast-arches            |     return self.nodelist.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
cvast-arches            |     bit = node.render_annotated(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
cvast-arches            |     return self.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
cvast-arches            |     return nodelist.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
cvast-arches            |     bit = node.render_annotated(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
cvast-arches            |     return self.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
cvast-arches            |     nodelist.append(node.render_annotated(context))
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
cvast-arches            |     return self.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 584, in render
cvast-arches            |     return self.nodelist.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
cvast-arches            |     bit = node.render_annotated(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
cvast-arches            |     return self.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
cvast-arches            |     nodelist.append(node.render_annotated(context))
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
cvast-arches            |     return self.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
cvast-arches            |     return nodelist.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
cvast-arches            |     bit = node.render_annotated(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
cvast-arches            |     return self.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 584, in render
cvast-arches            |     return self.nodelist.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
cvast-arches            |     bit = node.render_annotated(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
cvast-arches            |     return self.render(context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 1049, in render
cvast-arches            |     return render_value_in_context(output, context)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 1026, in render_value_in_context
cvast-arches            |     value = force_text(value)
cvast-arches            |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/utils/encoding.py", line 80, in force_text
cvast-arches            |     s = six.text_type(bytes(s), encoding, errors)
cvast-arches            | UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 65: ordinal not in range(128)
cvast-arches            | [30/Mar/2017 13:38:37] "GET /concepts/27bec21b-6782-4794-b9d9-f5c141bf1808?f=html&mode=semantic HTTP/1.1" 500 23860
```

#### Steps to Reproduce (for bugs)

1. Import arches/db/schemes/arches_concept_scheme.rdf
2. Open RDM in browser
3. Click on 'Arches' --> 'Component Type' --> 'Façade'

#### Your Arches Information

* Version used: master branch, SHA 7c8bb4af6bdc13b6afaa9cfb4b1e5f009713aa7a
* Browser Name and version: Chrome Version 57.0.2987.133
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by veuncent** [comment]
Fixed
