### ISSUE TITLE
import_reference_data does not allow ampersands (&)

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#1927]
### Bug Report

The import_reference_data cli function does not work when there are ampersands (&) in the value nodes of a concept scheme. 

Running my scheme through a SKOS validator (http://qskos.poolparty.biz/) those ampersands showed up as trouble makers. After removing the ampersands the import worked fine.

I am using a slightly customized version of the default `arches_concept_scheme.rdf`. 
I was able to import this before without problems. The ampersands were in there from the start. 

#### Expected Behavior

Import schemes without errors. 

#### Current Behavior
When importing a concept scheme into Arches I received the following error: 

```
Running: python manage.py packages -o import_reference_data -s "cvast_arches/db/schemes/arches_concept_scheme.rdf"
operation: import_reference_data
package: arches
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/web_root/ENV/local/lib/python2.7/site-packages/arches/management/commands/packages.py", line 160, in handle
    self.import_reference_data(options['source'], options['overwrite'], options['stage'])
  File "/web_root/ENV/local/lib/python2.7/site-packages/arches/management/commands/packages.py", line 351, in import_reference_data
    rdf = skos.read_file(data_source)
  File "/web_root/ENV/local/lib/python2.7/site-packages/arches/app/utils/skos.py", line 56, in read_file
    raise Exception('Error occurred while parsing the file %s' % path_to_file)
Exception: Error occurred while parsing the file cvast_arches/db/schemes/arches_concept_scheme.rdf
```

#### Your Arches Information

* Version used: master branch SHA 72d80aea6bf1ef70bcf7270cf7ec3229b56ee0a1
* Operating System and version (desktop or mobile): Ubuntu Xenial 16.04 Docker container
* Link to your Arches Install (optional):

**Comment by apeters** [comment]
can you attach an example file that fails the import?

**Comment by veuncent** [comment]
I was using a copy of this [arches_concept_scheme.rdf](https://github.com/archesproject/arches/blob/master/arches/db/schemes/arches_concept_scheme.rdf) for the import. 

However, the problem is gone in my current version (pulled today, SHA 11cbf68cf9a53e1955ee079d39b480747e1080e3). 

If no one else has this problem, please go ahead and close :)
