### ISSUE TITLE
4.0b3 install fails

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#1954]
After following the instructions in the README, arches does not get correctly installed.

On MacOS 10.10.5,  I run:  `sudo -H pip install arches==4.0b3` resulting in:
```
    Could not open requirements file: [Errno 2] No such file or directory: '/private/tmp/pip-build-j6QGJN/arches/arches/virtualenv/ENV/lib/python2.7/site-packages/arches/install/requirements.txt'
    error: [Errno 2] No such file or directory: '/private/tmp/pip-build-j6QGJN/arches/arches/virtualenv/ENV/lib/python2.7/site-packages/arches/install/django_overrides/admin.py'
```

Subsequently: `python ./manage.py runserver` results in:

```
Unhandled exception in thread started by <function wrapper at 0x1021509b0>
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Library/Python/2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/arches/arches.log'
```

And running that with sudo (which for :8000 shouldn't be needed) results in 

```
...
  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 2, in <module>
    from django.db.backends.postgresql.base import \
  File "/Library/Python/2.7/site-packages/django/db/backends/postgresql/base.py", line 24, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named psycopg2
```
Probably as the arches install failed to get through all of the requirements in the first step.

**Comment by azaroth42** [comment]
Manually installing psycopg2 just kicks the issue down the road a little:

```
  File "/Users/rsanderson/Development/getty/arches/project/project/urls.py", line 5, in <module>
    url(r'^', include('arches.urls')),
  File "/Library/Python/2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/arches/urls.py", line 22, in <module>
    from django.conf.urls.i18n import patterns
ImportError: cannot import name patterns
```

**Comment by mradamcox** [comment]
Hi Rob, why are you using sudo with the pip command? If you've created a virtual environment, you don't need to use sudo, and I think that may be causing the problem.

**Comment by azaroth42** [comment]
Same error, unfortunately:

```
[rsanderson@GT26940 arches]$ virtualenv ENV
New python executable in /Users/rsanderson/Development/getty/arches/ENV/bin/python
Installing setuptools, pip, wheel...          
done.

[rsanderson@GT26940 arches]$ source ENV/bin/activate

(ENV) [rsanderson@GT26940 arches]$ pip install arches==4.0b3
Collecting arches==4.0b3
[...]
  Could not open requirements file: [Errno 2] No such file or directory: '/Users/rsanderson/Development/getty/arches/ENV/lib/python2.7/site-packages/arches/install/requirements.txt'
  error: [Errno 2] No such file or directory: '/Users/rsanderson/Development/getty/arches/ENV/lib/python2.7/site-packages/arches/install/django_overrides/admin.py'
```

Also, if virtualenv is required, it would be good to put that in the README :)

**Comment by apeters** [comment]
Hi Rob,
I just tested this command and everything was successfully installed.

First I created a new directory and then a virtualenv within that directory:

mkdir test_install
> cd test_install
> virtualenv ENV
> source ENV/bin/activate
> pip install arches==4.0b3


I didn't need *sudo *nor would I recommend using sudo.

Can you confirm the existence of the requirements.txt file located here on
your system:

/private/tmp/pip-build-j6QGJN/arches/arches/virtualenv/ENV/lib/python2.7/site-packages/arches/install/

Cheers,
Alexei




Director of Web Development - Farallon Geographics, Inc. - 971.227.3173

**Comment by azaroth42** [comment]
Sorry! I follow the same steps and get a different result:

```
[rsanderson@GT26940 arches]$ mkdir test_install
[rsanderson@GT26940 arches]$ cd test_install/
[rsanderson@GT26940 test_install]$ virtualenv ENV
New python executable in /Users/rsanderson/Development/getty/arches/test_install/ENV/bin/python
Installing setuptools, pip, wheel...done.
[rsanderson@GT26940 test_install]$ source ENV/bin/activate
(ENV) [rsanderson@GT26940 test_install]$ pip install arches==4.0b3

  [...]
  Could not open requirements file: [Errno 2] No such file or directory: '/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/arches/install/requirements.txt'
  error: [Errno 2] No such file or directory: '/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/arches/install/django_overrides/admin.py'
```
If I go to .../arches/install/ then the requirements.txt file exists when I'm there, as does admin.py in django_overrides.  /private/tmp/... does not exist though.

I manually installed requirements.txt and it runs ... but then I get:

```
[11/Apr/2017 13:26:27] "POST /auth/?next=/graph/ HTTP/1.1" 302 0
Internal Server Error: /graph/
Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/arches/app/views/graph.py", line 129, in get
    root_nodes=JSONSerializer().serialize(root_nodes),
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/arches/app/views/graph.py", line 52, in get_context_data
    context = super(GraphBaseView, self).get_context_data(**kwargs)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/arches/app/views/base.py", line 31, in get_context_data
    datatype_factory = DataTypeFactory()
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/arches/app/datatypes/datatypes.py", line 25, in __init__
    self.datatypes = {datatype.datatype:datatype for datatype in models.DDataType.objects.all()}
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rsanderson/Development/getty/arches/test_install/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column d_data_types.isgeometric does not exist
LINE 1: ..."."configcomponent", "d_data_types"."configname", "d_data_ty...
  ```

**Comment by mradamcox** [comment]
Hmm, did you try upgrading pip? use `python -m pip install --upgrade pip`

**Comment by jmunowitch** [comment]
Can you run this command and confirm what version of python you are using?
`python --version`

**Comment by azaroth42** [comment]
I have the latest pip, and Python 2.7.10:

```
[rsanderson@GT26940 ~]$ pip --version
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)
[rsanderson@GT26940 ~]$ python --version
Python 2.7.10
```

**Comment by apeters** [comment]
I'm guessing that this has something to do with permissions.
Are you trying to load Arches in a protected location or as a user that does't have privileges to the /private/tml directory?
I'm a bit stumped on this as I can't really reproduce what you're seeing.

**Comment by ianibo** [comment]
Hey @apeters, @azaroth42 (Hope you are doing well Rob). Neil Smith and I (Think maybe you met at the liverpool workshop) are trying to do an install, and we're seeing the same problems reported by Rob (I've tried on ubuntu 1704, neil on windows). Is there anything we can do to help diagnose this? I might be able to get you access to a server that exhibits the problem. We're planning to meet up with Phil Carslile and some of the arches team on tuesday - so we're just trying to run through in advance. Any ideas for ways to move this forward? Cheers, Ian and Neil.

**Comment by apeters** [comment]
Hey @ianibo and @azaroth42, 
I just tested this on a windows 8 64bit machine and was able to reproduce the error you're seeing (**Could not open requirements file**), but in fact it did look like the requirements were all loaded.  I could confirm this by looking at the **site-packages** folder in the virtualenv; all the python modules Arches requires seemed to be there.

Here's what I did next (assumes that all the dependencies have been loaded: https://github.com/archesproject/arches/wiki/Developer-Installation#dependencies, make sure you follow the OS specific instructions)
- Make sure you're environment is activated
- I setup a project (https://github.com/archesproject/arches/wiki/Creating-an-Arches-Project)
- Ran bower install from my new project, you need to navigate to the new project directory that has the bower.json file in it. (this should have been done by just creating a project, but didn't work for me) 
- Updated the database settings in my new project's settings.py file
- Installed ElasticSearch (https://github.com/archesproject/arches/wiki/Installing-Elasticsearch)
- Ran ElasticSearch (https://github.com/archesproject/arches/wiki/Installing-Elasticsearch#running-elasticsearch)
- Ran the command to setup Arches ```python mange.py packages -o setup```.  Done from the new project directory where the manage.py file resides:
- Ran the command to install the base graphs (for testing).  ```python manage.py packages -o import_graphs```
- Started the test server.  ```python manage.py runserver```

At that point I was able to hit the site at ```localhost:8000```

I did notice some issue hitting the graph page at ```localhost:8000/graph/```.  Let me know if you see this issue as well.

**Comment by mradamcox** [comment]
For what it's worth, in my experience, when trying to install on Windows 10 with the recent version of pip (9.0.1 for me), pip first tries to use the wheel-building process. This seems to always fail with the `requirements.txt` error you are seeing. However, then it seems to install successfully using the setup.py method:
![image](https://cloud.githubusercontent.com/assets/10427268/26028919/ded90426-3829-11e7-98dd-fcdd7c6d689c.png)
(I made a note about this in step 4 of [this installation section](https://arches4.readthedocs.io/en/latest/installation/#installing-arches)).

**Comment by mradamcox** [comment]
@azaroth42 could you please test this out again on your environment using the "no-binaries" argument that I have in the documentation? Hopefully your output will look like this
![image](https://user-images.githubusercontent.com/10427268/27961210-9b630224-62f3-11e7-8170-cd4fe3328b65.png)
Remember, you'll have to install Shapely separately before pip installing Arches into a new virtual environment.
