### ISSUE TITLE
crypto.py issues

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#2620]
### Bug Report

After https://github.com/archesproject/arches/commit/2c174e90181703590abde955c419ef1015a278a5, Running Arches will cause some sort of collision and will refuse to import crypto libraries and cause other setup issues:
```
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/web_root/arches/arches/urls.py", line 21, in <module>
    from arches.app.views import concept, main, map, search, graph, tileserver
  File "/web_root/arches/arches/app/views/main.py", line 37, in <module>
    from arches.app.utils.crypto import AESCipher
    from Crypto.Cipher import AES
```

**Comment by jmunowitch** [comment]
Renaming crypto.py to crypto2.py and adjusting the references seems to solve this issue.

**Comment by jmunowitch** [comment]
Confirmed working on my system with Docker.
