### ISSUE TITLE
json import issue with parenttile_id

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2882]
When importing a json formatted business data into a resource model, importer seems not to populate parent ahead of child tiles therefore resulting in recursive key error.  Matching sample resource model and data content files attached in the zip.  Also, error thrown by Arches pasted below.

117 of 1308 resources saved
118 of 1308 resources saved
Resources for Import: 1308, Resources Saved: 118, Tiles for Import: 781, Tiles Saved: 774, Relations for Import: 0, Relations Saved: 0
Traceback (most recent call last):
 File "manage.py", line 29, in <module>
   execute_from_command_line(sys.argv)
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
   utility.execute()
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
   self.execute(*args, **cmd_options)
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
   output = self.handle(*args, **options)
 File "/Users/adamlodge/repos/projects/arches/management/commands/packages.py", line 172, in handle
   self.import_business_data(options['source'], options['config_file'], options['overwrite'], options['bulk_load'], options['create_concepts'])
 File "/Users/adamlodge/repos/projects/arches/management/commands/packages.py", line 795, in import_business_data
   BusinessDataImporter(path, config_file).import_business_data(overwrite=overwrite, bulk=bulk_load, create_concepts=create_concepts, create_collections=create_collections)
 File "/Users/adamlodge/repos/projects/arches/app/utils/data_management/resources/importer.py", line 143, in import_business_data
   reader.import_business_data(business_data, mapping)
 File "/Users/adamlodge/repos/projects/arches/app/utils/data_management/resources/formats/archesfile.py", line 128, in import_business_data
   'data': tile['data']
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
   return getattr(self.get_queryset(), name)(*args, **kwargs)
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 487, in update_or_create
   obj.save(using=self.db)
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/db/transaction.py", line 223, in __exit__
   connection.commit()
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/db/backends/base/base.py", line 262, in commit
   self._commit()
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/db/backends/base/base.py", line 236, in _commit
   return self.connection.commit()
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
   six.reraise(dj_exc_type, dj_exc_value, traceback)
 File "/Users/adamlodge/repos/projects/ENV/lib/python2.7/site-packages/django/db/backends/base/base.py", line 236, in _commit
   return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "tiles" violates foreign key constraint "tiles_parenttileid_b85c3d9c_fk_tiles_tileid"
DETAIL:  Key (parenttileid)=(627e3fe8-055e-43c5-bc14-3e973385df92) is not present in table "tiles".

[Archive.zip](https://github.com/archesproject/arches/files/1602194/Archive.zip)

**Comment by adamlodge** [comment]
fixed
