### ISSUE TITLE
Docker: When running arbitrary commands on bash, the project folder is not respected

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3030]
### Bug Report
If a project is being used, an arbitrary cli command (i.e. anything outside the commands set in `entrypoint.sh`) is not run in in the project directory.

This means that loading of a package will fail. For example:
`docker run arches python manage.py packages -o load_package -s https://github.com/archesproject/disco_data/archive/master.zip -db true`

**Comment by jmunowitch** [comment]
Failure looks like this:
```
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/web_root/arches/arches/management/commands/packages.py", line 202, in handle
    self.load_package(options['source'], options['setup_db'], options['overwrite'], options['stage'])
  File "/web_root/arches/arches/management/commands/packages.py", line 480, in load_package
    load_widgets(package_location)
  File "/web_root/arches/arches/management/commands/packages.py", line 430, in load_widgets
    load_extensions(package_dir, 'widgets', 'widget')
  File "/web_root/arches/arches/management/commands/packages.py", line 404, in load_extensions
    root = settings.APP_ROOT if settings.APP_ROOT != None else os.path.join(settings.ROOT_DIR, 'app')
  File "/web_root/arches/arches/app/models/system_settings.py", line 69, in __getattr__
    return super(SystemSettings, self).__getattr__(name) #getattr(self, name, True)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'APP_ROOT'
```

**Comment by jmunowitch** [comment]
Fixed. Loading a package within a project in docker now works from the docker command:
`docker-compose run arches python manage.py packages -o load_package -s https://github.com/archesproject/disco_data/archive/master.zip -db true`
