### ISSUE TITLE
Graceful error if there is difficulty downloading a package during `load_package`

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#3122]
### User Story
I was trying to load a package from a git repository with the following command

`python manage.py packages -o load_package -s http://github.com/archesproject/arches4-example-pkg/archive/stable/4.1.x.zip -db true`

But got a basic "invalid package source" error. I commented out this try/except block https://github.com/archesproject/arches/blob/master/arches/management/commands/packages.py#L456 and then got this error:

operation: load_package
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "C:\arches\test\env\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\arches\test\env\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\arches\test\env\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\arches\test\env\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\arches\test\env\lib\site-packages\arches\management\commands\packages.py", line 202, in handle
    self.load_package(options['source'], options['setup_db'], options['overwrite'], options['stage'])
  File "C:\arches\test\env\lib\site-packages\arches\management\commands\packages.py", line 467, in load_package
    package_location = handle_source(source)
  File "C:\arches\test\env\lib\site-packages\arches\management\commands\packages.py", line 451, in handle_source
    urllib.urlretrieve(source, zip_file)
  File "c:\python27\Lib\urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "c:\python27\Lib\urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "c:\python27\Lib\urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "c:\python27\Lib\urllib.py", line 359, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "c:\python27\Lib\urllib.py", line 372, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "c:\python27\Lib\urllib.py", line 665, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "c:\python27\Lib\urllib.py", line 635, in http_error_302
    data)
  File "c:\python27\Lib\urllib.py", line 661, in redirect_internal
    return self.open(newurl)
  File "c:\python27\Lib\urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "c:\python27\Lib\urllib.py", line 437, in open_https
    h.endheaders(data)
  File "c:\python27\Lib\httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "c:\python27\Lib\httplib.py", line 829, in _send_output
    self.send(msg)
  File "c:\python27\Lib\httplib.py", line 791, in send
    self.connect()
  File "c:\python27\Lib\httplib.py", line 1176, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "c:\python27\Lib\ssl.py", line 387, in wrap_socket
    ciphers=ciphers)
  File "c:\python27\Lib\ssl.py", line 143, in __init__
    self.do_handshake()
  File "c:\python27\Lib\ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

This is a strange SSL error, which I haven't encountered before, and I don't think has anything to do with the Arches codebase. However, in cases such as this it would be much better if the response from Arches was a message along the lines of "error downloading the zip file, you'll need to manually download this file and then...." etc.

#### Your Arches Information

* Version used: 4.1

**Comment by party98** [comment]
Hey, I'd like to take this up. Since I am a new, please help me by pointing me in the general direction of where to start.

**Comment by chiatt** [comment]
Hi @party98. Thanks for your interest in contributing to Arches!  This is a great ticket to get acquainted with the application. The contribution guidelines are a great place to get started:  https://github.com/archesproject/arches/wiki#contributing-to-arches

Once you fork and pull down the code, just follow these instructions to set up your development environment here: https://arches.readthedocs.io/en/latest/creating-a-development-environment/
If you have any specific questions about this ticket, feel free to post them here. 

If you run into any issues installing Arches, you can post questions on the Arches forum here:
https://groups.google.com/forum/#!forum/archesproject

- Cyrus

**Comment by mradamcox** [comment]
@party98, I'm rereading the issue as I wrote it, and I would like to clarify something that I'm not sure I made clear. The url I mentioned in fact *is* a valid package source, but because an error occurred during download, the error message I got from Arches was unclear. Good luck!

**Comment by chiatt** [comment]
I think in the latest version of the package loader the try block mentioned by @mradamcox starts here: https://github.com/archesproject/arches/blob/adf6476a20aaae34596eb75a4e8c14cc7bbe05dc/arches/management/commands/packages.py#L547
