### ISSUE TITLE
Display value function errors on bulk import of null value

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#3220]
The display value function throws the following error on bulk import if one of the nodes participating in the function is null or is not mapped in the mapping file.

```
Traceback (most recent call last):

  File ".../arches/arches/app/utils/data_management/resources/formats/csvfile.py", line 777, in import_business_data
    Resource.bulk_save(resources=resources)

  File ".../arches/arches/app/models/resource.py", line 150, in bulk_save
    document, terms = resource.get_documents_to_index(fetchTiles=False, datatype_factory=datatype_factory, node_datatypes=node_datatypes)

  File ".../arches/arches/app/models/resource.py", line 190, in get_documents_to_index
    document = JSONSerializer().serializeToPython(self)

  File ".../arches/arches/app/utils/betterJSONSerializer.py", line 47, in serializeToPython
    return self.handle_object(obj, self.selected_fields, self.exclude)

  File ".../arches/arches/app/utils/betterJSONSerializer.py", line 86, in handle_object
    return self.handle_object(getattr(object, 'serialize')(fields, exclude), fields, exclude)

  File ".../arches/arches/app/models/resource.py", line 361, in serialize
    ret = JSONSerializer().handle_model(self)

  File ".../arches/arches/app/utils/betterJSONSerializer.py", line 168, in handle_model
    data[property_name] = self.handle_object(getattr(instance, property_name))

  File ".../arches/arches/app/models/resource.py", line 68, in displayname
    return self.get_descriptor('name')

  File ".../arches/arches/app/models/resource.py", line 54, in get_descriptor
    return PrimaryDescriptorsFunction.get_primary_descriptor_from_nodes(self, functionConfig[0].config[descriptor])

  File ".../arches/arches/app/functions/primary_descriptors.py", line 16, in get_primary_descriptor_from_nodes
    value = datatype.get_display_value(tile, node)

  File ".../arches/arches/app/datatypes/concept_types.py", line 146, in get_display_value
    for val in tile.data[str(node.nodeid)]:

TypeError: 'NoneType' object is not iterable
```
Ex. Function is assigned to Name and Name Type nodes. Name is mapped and has a value in the csv, Name Type is either not mapped or is mapped but contains a null value.

Display value function should be able to gracefully handle a null or unmapped value from bulk import.

**Comment by ryan86** [comment]
Expected Behavior: 
- Import should alert the user to the nodes that participate in the display value function.
- If a node participating in the display value function is not mapped or contains a null value the resource import log should reflect this.

**Comment by dwuthrich** [comment]
meets requirements
