### ISSUE TITLE
Import: Bulk import of EDTF datatype not working

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#3228]
Bulk import of EDTF datatype throws the following error:

```
Traceback (most recent call last):

  File ".../arches/arches/app/utils/data_management/resources/formats/csvfile.py", line 636, in import_business_data
    self.save_resource(populated_tiles, resourceinstanceid, legacyid, resources, target_resource_model, bulk, save_count)

  File ".../arches/arches/app/utils/data_management/resources/formats/csvfile.py", line 307, in save_resource
    Resource.bulk_save(resources=resources)

  File ".../arches/arches/app/models/resource.py", line 157, in bulk_save
    tile.save_edit(edit_type='tile create', new_value=tile.data)

  File ".../arches/arches/app/models/tile.py", line 118, in save_edit
    edit.save()

  File ".../arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)

  File ".../arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

  File ".../arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 905, in _save_table
    forced_update)

  File ".../arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 955, in _do_update
    return filtered._update(values) > 0

  File ".../arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 664, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)

  File ".../arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1199, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)

  File ".../arches/virtualenv/ENV/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception

TypeError: UUID('b84998d1-3609-11e8-ba2a-dca90488358a') is not JSON serializable
```

python manage.py packages -o import_business_data -s file -ow overwrite --bulk

**Comment by dwuthrich** [comment]
meets requirements
