### ISSUE TITLE
Create API endpoint to GET a single resource instance

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3313]
GET `/resources/{resource_instance_id}?f=json-ld`

output formats supported: 
- json-ld
- json (our current format)

The following file written by Rob Sanderson may lend some insight into how to implement this:

[https://app.zenhub.com/files/49451058/f8995c5c-89e0-467c-830b-988244890abb/download](https://app.zenhub.com/files/49451058/f8995c5c-89e0-467c-830b-988244890abb/download)

**Comment by apeters** [comment]
see https://arches4.readthedocs.io/en/latest/api/#resources for info on how to test

**Comment by jmunowitch** [comment]
It looks like there are two issues:

- [ ] Once a token has been received, a non-valid token can be used to get a resource. All of the following worked:
```
curl -H "Authorization: Bearer S8e9Ibi32Zeo2PNNjL3Ar4FM6FfcY3" -X GET http://localhost:8000/resources/154a25f2-3ee5-41ca-b264-c6c93852b7d5?f=json-ld
curl -H "Authorization: Bearer S8e9Ibi32Zeo2PNNjL3Ar4FM6FfcY1" -X GET http://localhost:8000/resources/154a25f2-3ee5-41ca-b264-c6c93852b7d5?f=json-ld
curl -H "Authorization: Bearer S8e9Ibi32Zeo2PNNjL3Ar4FM6FfcY2" -X GET http://localhost:8000/resources/154a25f2-3ee5-41ca-b264-c6c93852b7d5?f=json-ld
```
- [ ] There is no error handling for a resource that someone does not have access to or does not exist:
```
Traceback (most recent call last):
  File "/Users/jmunowitch/Repositories/ENV/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jmunowitch/Repositories/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jmunowitch/Repositories/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jmunowitch/Repositories/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/jmunowitch/Repositories/arches/arches/app/views/api.py", line 33, in dispatch
    return super(APIBase, self).dispatch(request, *args, **kwargs)
  File "/Users/jmunowitch/Repositories/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/jmunowitch/Repositories/arches/arches/app/views/api.py", line 82, in get
    output = exporter.writer.write_resources(resourceinstanceids=[resourceid], indent=indent, user=request.user)
  File "/Users/jmunowitch/Repositories/arches/arches/app/utils/data_management/resources/formats/archesfile.py", line 53, in write_resources
    super(ArchesFileWriter, self).write_resources(graph_id=graph_id, resourceinstanceids=resourceinstanceids, **kwargs)
  File "/Users/jmunowitch/Repositories/arches/arches/app/utils/data_management/resources/formats/format.py", line 201, in write_resources
    self.get_tiles(graph_id=graph_id, resourceinstanceids=resourceinstanceids, **kwargs)
  File "/Users/jmunowitch/Repositories/arches/arches/app/utils/data_management/resources/formats/format.py", line 246, in get_tiles
    self.graph_id = models.ResourceInstance.objects.get(resourceinstanceid=resourceinstanceids[0]).graph_id
  File "/Users/jmunowitch/Repositories/ENV/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jmunowitch/Repositories/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: ResourceInstance matching query does not exist.
```

**Comment by azaroth42** [comment]
As well as the query param on the end of the URI, it would be great to allow the use of the `Accept` HTTP request header to set the media-type.

eg:
> `curl -X GET -H "Accept:  application/ld+json" http://.../resources/uuid`  

should have the same functionality as the `?format=json-ld` param

**Comment by apeters** [comment]
@azaroth42 that's a good idea.  See this ticket: https://github.com/archesproject/arches/issues/3494

**Comment by jmunowitch** [comment]
Reviewed and looks good.

It looks like the API endpoint properly handles these two issues:
- Once a token has been received, a non-valid token can be used to get a resource.
- There is no error handling for a resource that someone does not have access to or does not exist:
