### ISSUE TITLE
Sometimes, when editing cards and widgets, save fails with an Integrity Error

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3892]
```
IntegrityError at /card/dd9630ca-9f40-11e8-b6bf-14109fd34195
duplicate key value violates unique constraint "cards_x_nodes_x_widgets_nodeid_cardid_widgetid_976dc542_uniq"
DETAIL:  Key (nodeid, cardid, widgetid)=(d63847f8-9f40-11e8-a13f-14109fd34195, dd9630ca-9f40-11e8-b6bf-14109fd34195, 10000000-0000-0000-0000-000000000004) already exists.
```

http://recordit.co/8FTqb0DzaL

**Comment by azaroth42** [comment]
I get this a lot!  Is the last "uuid" significant? I sometimes get ...2 and sometimes ...4 as above.

**Comment by robgaston** [comment]
@apeters I was unable to reproduce this - do you have any details on the steps required to see this issue?

**Comment by apeters** [comment]
@robgaston I can't reproduce this anymore either, I'll close for now

**Comment by azaroth42** [comment]
I still get this constantly.

Steps to reproduce:

* Initialize the database.
* Create a branch.
* Add a few nodes to the model.
* Go to cards.
* Set up some cards, including reordering.
* Splat.

**Comment by azaroth42** [comment]
Explicitly:

* Initialize DB.
* Create new Branch with Ontology, and class of E22 Man Made Object
* Add a node, rdf:Literal, relationship of p3_has_note, data type string
* Add a node, E55 Type, relationship of P2_has_type, data type resource-instance-list
* Add a node, E57 Material, relationship of P45_consists_of, data type resource-instance-list
* Go to cards
* Set note card to not be visible, with default value of "note"
* Reorder the nodes to Type, note, Material by dragging and dropping on the tree in the left pane.
* the POST to /card/xxx results in HTTP 500, with the IntegrityError.

Stack trace:

```
Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/views/graph.py", line 474, in post
    card = Card(data)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/models/card.py", line 104, in __init__
    widget_model.save()
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "cards_x_nodes_x_widgets_nodeid_cardid_widgetid_976dc542_uniq"
DETAIL:  Key (nodeid, cardid, widgetid)=(77a40c94-ad4a-11e8-a047-a4d18cec433a, 5a57c6a8-ad4a-11e8-be88-a4d18cec433a, ff3c400a-76ec-11e7-a793-784f435179ea) already exists.
```

Whatisthis 77a40c94-ad4a-11e8-a047-a4d18cec433a 

```
Node object
_state
  <django.db.models.base.ModelState object at 0x1148ad810>
config
  {u'graphid': None}
datatype
  resource-instance-list
description
  None
graph_id
  5a55a37a-ad4a-11e8-84f4-a4d18cec433a
isrequired
  False
issearchable
  True
istopnode
  False
name
  Classification
nodegroup_id
  5a53d459-ad4a-11e8-bf36-a4d18cec433a
nodeid
  77a40c94-ad4a-11e8-a047-a4d18cec433a
ontologyclass
  http://www.cidoc-crm.org/cidoc-crm/E55_Type
sortorder
  0
```

whatisthis 5a57c6a8-ad4a-11e8-be88-a4d18cec433a

```
================================================================================
This UUID is the primary key for 2 objects:
--------------------------------------------------------------------------------
CardModel object
_state
  <django.db.models.base.ModelState object at 0x114604bd0>
active
  True
cardid
  5a57c6a8-ad4a-11e8-be88-a4d18cec433a
component_id
  f05e4d3a-53c1-11e8-b0ea-784f435179ea
config
  None
cssclass
  None
description
  
graph_id
  5a55a37a-ad4a-11e8-84f4-a4d18cec433a
helpenabled
  False
helptext
  None
helptitle
  None
instructions
  None
name
  Test Object
nodegroup_id
  5a53d459-ad4a-11e8-bf36-a4d18cec433a
sortorder
  None
visible
  True
--------------------------------------------------------------------------------
Card object
_nodegroup_cache
  NodeGroup object
_state
  <django.db.models.base.ModelState object at 0x11463be90>
active
  True
cardid
  5a57c6a8-ad4a-11e8-be88-a4d18cec433a
cardinality
  1
cards
  []
component_id
  f05e4d3a-53c1-11e8-b0ea-784f435179ea
config
  None
cssclass
  None
description
  
disabled
  False
graph_id
  5a55a37a-ad4a-11e8-84f4-a4d18cec433a
helpenabled
  False
helptext
  None
helptitle
  None
instructions
  None
name
  Test Object
nodegroup_id
  5a53d459-ad4a-11e8-bf36-a4d18cec433a
nodes
  []
ontologyproperty
  None
sortorder
  None
visible
  True
widgets
  [<CardXNodeXWidget: CardXNodeXWidget object>, <CardXNodeXWidget: CardXNodeXWidget object>, <CardXNodeXWidget: CardXNodeXWidget object>]
================================================================================
```

whatisthis ff3c400a-76ec-11e7-a793-784f435179ea

```
================================================================================
This UUID is the primary key for 1 object:
--------------------------------------------------------------------------------
Widget object
_state
  <django.db.models.base.ModelState object at 0x10a97da50>
component
  views/components/widgets/resource-instance-multiselect
datatype
  resource-instance-list
defaultconfig
  {u'placeholder': u''}
helptext
  None
name
  resource-instance-multiselect-widget
widgetid
  ff3c400a-76ec-11e7-a793-784f435179ea
================================================================================
```

**Comment by azaroth42** [comment]
FWIW,  args[0][widgets] is that's iterated at line 94 of models/card.py...

```
[
 {u'widget_id': u'10000000-0000-0000-0000-000000000001', u'card_id': u'5a57c6a8-ad4a-11e8-be88-a4d18cec433a', u'label': u'note', u'disabled': False, u'visible': False, u'node_id': u'678c27ee-ad4a-11e8-bc5a-a4d18cec433a', u'sortorder': 0, u'config': {u'width': u'100%', u'defaultValue': u'Note about thing', u'maxLength': None, u'placeholder': u'Enter text', u'label': u'note'}, u'id': None},
 {u'widget_id': u'ff3c400a-76ec-11e7-a793-784f435179ea', u'card_id': u'5a57c6a8-ad4a-11e8-be88-a4d18cec433a', u'label': u'Material', u'disabled': False, u'visible': True, u'node_id': u'8e5f3eeb-ad4a-11e8-90d9-a4d18cec433a', u'sortorder': 1, u'config': {u'placeholder': u'', u'label': u'Material'}, u'id': None}, 
 {u'widget_id': u'ff3c400a-76ec-11e7-a793-784f435179ea', u'card_id': u'5a57c6a8-ad4a-11e8-be88-a4d18cec433a', u'label': u'Classification', u'disabled': False, u'visible': True, u'node_id': u'77a40c94-ad4a-11e8-a047-a4d18cec433a', u'sortorder': 2, u'config': {u'placeholder': u'', u'label': u'Classification'}, u'id': None}
]
```

**Comment by dwuthrich** [comment]
I can reproduce @azaroth42 error.  Note that refreshing the browser allows user to complete the card re-order.  Wondering whether if there the knockout memory issue might have something to do with the issue.

**Comment by azaroth42** [comment]
Noting again that this is blocking work on the Provenance Index, AATA, and ARM. After the graph shape is built, changes to the cards are only inconsistently persisted.  The cards end up in a seemingly random state despite saving.

**Comment by apeters** [comment]
@azaroth42 I submitted a fix for this.  You'll have to switch to the stable/4.3.x branch to test it.

**Comment by azaroth42** [comment]
It's MUCH less frequent however (and of course much harder to reproduce consistently :( )

**Comment by azaroth42** [comment]
@apeters Can we merge to master, as it does make significant improvements, but leave the issue open to investigate?

**Comment by azaroth42** [comment]
:+1: Great, I'll keep trying to reproduce.

**Comment by azaroth42** [comment]
Hit it again without ever moving a card in a fresh-ish database with very simple branches. Will try and reproduce this afternoon.

**Comment by azaroth42** [comment]
Okay, here is what I did this time that generated the error:

* Create a new branch:
  * Called label, CRM ontology (with linked art extension), class of xsd:string, datatype of string
  * Edited the card in the branch to set 
    * title: Label for Resource
    * subtitle: (internal use only)

* Create a new branch:
  * Called classification, CRM ontology, class of E55_Type, datatype of concept
  * Edited the card in the branch to set
    * title: Classification

* Create a new model:
  * Called Physical Object, CRM ontology, class of E22 Man Made Object, datatype of semantic, set as active
  * Add the classification branch
  * Add the label branch
  * Edited the cards in the model to set
    * label default value:  Label for Object
    * placeholder: Enter label

And saving placeholder generated the error:

```
$ python ./manage.py packages -o setup_db
$ python manage.py runserver
  [ ... ]
Internal Server Error: /card/63795ae1-bd13-11e8-8655-a4d18cec433a
Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ben/arches/arches/app/views/graph.py", line 477, in post
    card = Card(data)
  File "/Users/rsanderson/Development/getty/arches/dev/ben/arches/arches/app/models/card.py", line 104, in __init__
    widget_model.save()
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "cards_x_nodes_x_widgets_nodeid_cardid_widgetid_976dc542_uniq"
DETAIL:  Key (nodeid, cardid, widgetid)=(6379550f-bd13-11e8-bd9b-a4d18cec433a, 63795ae1-bd13-11e8-8655-a4d18cec433a, 10000000-0000-0000-0000-000000000001) already exists.

[20/Sep/2018 15:27:10] "POST /card/63795ae1-bd13-11e8-8655-a4d18cec433a HTTP/1.1" 500 27860
```

**Comment by azaroth42** [comment]
And duplicated following those steps.

**Comment by apeters** [comment]
Thanks @azaroth42 this is great!  I'll look into this asap!

**Comment by apeters** [comment]
I tried this, but without the Linked art extension, and I couldn't reproduce this.
Can you send me the linked art extension?

**Comment by adamlodge** [comment]
I've run into this on a non-ontology graph, and I made a hacky solution.  

Looks like the issue is that when I change a data-collecting node's widget from (for example) text-widget to rich-text-widget, the system adds a record to the cards_x_nodes_x_widgets table, but does not delete the old record indicating what the widget was.  At that point, the system will just use whatever widget it finds in the db first, and no integrity constraint is broken in the db.  In my case, the system continued using the old record pointing to text-widget.

Since my change wasnt effected in the UI, I tried again to change the widget to rich-text-widget but then it throws the integrity constraint because the record does exist - it's just not being used.

My hacky solution was to find the offending/old record in the db table and delete it with sql.  With that, the system uses the "right" record to effect the correct widget.  The real solution (I think) should be to just update code to delete the cruft record in the table when widget is modified.

**Comment by adamlodge** [comment]
@azaroth42 : after some superficial and quick testing, this is looking good.  Would be great to get your two cents before I close this out though.

**Comment by azaroth42** [comment]
Yup, also superficial, but can't generate the errors I used to be able to.

OTOH, it does not also solve #4188.
