### ISSUE TITLE
Graph manager crashes on save

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4162]
While trying to configure a new node on a model (details below), on clicking Save Edits, I get the following error:

```
Internal Server Error: /node/e2bac5e8-bd16-11e8-9c5a-a4d18cec433a
Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/dev/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/views/graph.py", line 367, in post
    return JSONResponse(ret)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/utils/response.py", line 34, in __init__
    self.content = JSONSerializer().serialize(content, **options)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/utils/betterJSONSerializer.py", line 50, in serialize
    obj = self.serializeToPython(obj, **options)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/utils/betterJSONSerializer.py", line 47, in serializeToPython
    return self.handle_object(obj, self.selected_fields, self.exclude)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/utils/betterJSONSerializer.py", line 86, in handle_object
    return self.handle_object(getattr(object, 'serialize')(fields, exclude), fields, exclude)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/models/graph.py", line 1188, in serialize
    ret['cards'] = self.get_cards() if 'cards' not in exclude else ret.pop('cards', None)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/models/graph.py", line 1153, in get_cards
    card.description = self.nodes[card.nodegroup_id].description
KeyError: UUID('ca3561fd-c757-11e8-b506-a4d18cec433a')
```
Resulting in an HTTP 500 Internal Server response to the POST, and a spinning ball of doom in the UI.

Details of the configuration:

I created a branch for E22 Man Made Object, and added a bunch of pre-configured branches (Name, Description, Identifier, Production, etc).  I then added 3 new nodes. Now I can select one of the new nodes and set it up as: 
* Name:  Current Location
* Class: Place
* Property: P55 has current location
* Datatype: resource-instance
* Model: Place

And it crashes on save with the above error, but the changes are persisted in the db.

**Comment by azaroth42** [comment]
The card view of the same model has not updated (despite shift reloading) and has many new_node entries.  Could be part of the issue?

![screen shot 2018-10-03 at 4 25 52 pm](https://user-images.githubusercontent.com/871868/46444924-200b5400-c729-11e8-91d1-0c9812cbf2a2.png)

**Comment by azaroth42** [comment]
Can't reproduce in clean instance. Closing until I can!
