### ISSUE TITLE
Delete concept error: This backend doesn't support absolute paths

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4168]
`This backend doesn't support absolute paths`

**Describe the bug**
Deleting a concept results in a `500` error with the following server logs:
```
nginx            | 2018-10-05T08:36:36.087156500Z 172.19.0.1 - - [05/Oct/2018:10:36:36 +0200] "GET /concepts/fe30a8b6-5815-4630-b8df-79d433a05ac5/confirm_delete/ HTTP/1.1" 200 100 "http://localhost/rdm/4e5ceaa5-441d-4c14-b6fd-672127c18764" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" "-"
arches           | 2018-10-05T08:36:42.764796800Z Internal Server Error: /concepts/4e5ceaa5-441d-4c14-b6fd-672127c18764
arches           | 2018-10-05T08:36:42.764852600Z Traceback (most recent call last):
arches           | 2018-10-05T08:36:42.764860800Z   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
arches           | 2018-10-05T08:36:42.764864700Z     response = get_response(request)
arches           | 2018-10-05T08:36:42.764867900Z   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
arches           | 2018-10-05T08:36:42.764871400Z     response = self.process_exception_by_middleware(e, request)
arches           | 2018-10-05T08:36:42.764874600Z   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
arches           | 2018-10-05T08:36:42.764877700Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
arches           | 2018-10-05T08:36:42.764880700Z   File "/web_root/ENV/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
arches           | 2018-10-05T08:36:42.764897800Z     return view_func(request, *args, **kwargs)
arches           | 2018-10-05T08:36:42.764901000Z   File "/web_root/arches/arches/app/views/concept.py", line 236, in concept
arches           | 2018-10-05T08:36:42.764904200Z     concept.delete(delete_self=delete_self)
arches           | 2018-10-05T08:36:42.764907200Z   File "/web_root/arches/arches/app/models/concept.py", line 267, in delete
arches           | 2018-10-05T08:36:42.764910300Z     models.Concept.objects.get(pk=key).delete()
arches           | 2018-10-05T08:36:42.764913200Z   File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/models/base.py", line 974, in delete
arches           | 2018-10-05T08:36:42.764916700Z     return collector.delete()
arches           | 2018-10-05T08:36:42.764919800Z   File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 308, in delete
arches           | 2018-10-05T08:36:42.764931100Z     sender=model, instance=obj, using=self.using
arches           | 2018-10-05T08:36:42.764934200Z   File "/web_root/ENV/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
arches           | 2018-10-05T08:36:42.764937100Z     for receiver in self._live_receivers(sender)
arches           | 2018-10-05T08:36:42.764939800Z   File "/web_root/arches/arches/app/models/models.py", line 705, in auto_delete_file_on_delete
arches           | 2018-10-05T08:36:42.764942600Z     if instance.value.path:
arches           | 2018-10-05T08:36:42.764945200Z   File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 65, in path
arches           | 2018-10-05T08:36:42.764948100Z     return self.storage.path(self.name)
arches           | 2018-10-05T08:36:42.764950700Z   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/files/storage.py", line 111, in path
arches           | 2018-10-05T08:36:42.764953600Z     raise NotImplementedError("This backend doesn't support absolute paths.")
arches           | 2018-10-05T08:36:42.764956400Z NotImplementedError: This backend doesn't support absolute paths.
nginx            | 2018-10-05T08:36:42.784525400Z 172.19.0.1 - - [05/Oct/2018:10:36:42 +0200] "DELETE /concepts/4e5ceaa5-441d-4c14-b6fd-672127c18764 HTTP/1.1" 500 21652 "http://localhost/rdm/4e5ceaa5-441d-4c14-b6fd-672127c18764" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" "-"
```

**To Reproduce**
1. Click the delete icon (red circle with white cross) to the left of a concept
2. Click 'Yes' in the confirmation dialog box

**Expected behavior**
The concept should be deleted.

**Your Arches Information**

*   Version used: master branch #bba6bd7dbc2bfe7381f68da90e0f5a97783f9ffe 
*   Operating System and version (desktop or mobile): Ubuntu 16.04 (Docker for Windows)
*   Browser Name and version: Chrome

**Comment by EnisBerk** [comment]
Hi @veuncent, were you able to solve this issue? I am facing the same problem.

**Comment by EnisBerk** [comment]
I temporarily solved it using another try/except to check if it has a path or name in the function auto_delete_file_on_delete ([line](https://github.com/archesproject/arches/blob/209a12fef16a0f08daa7fdd5b4698772b7cd2e0d/arches/app/models/models.py#L945))

I am not familiar with storage API, how can we do this in a cleaner way ?

```python
# from http://stackoverflow.com/questions/16041232/django-delete-filefield
@receiver(post_delete, sender=FileValue)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `FileValue` object is deleted.
    """
    try:
        if instance.value.path:
            try:
                if os.path.isfile(instance.value.path):
                    os.remove(instance.value.path)
            # except block added to deal with S3 file deletion
            # see comments on 2nd answer below
            # http://stackoverflow.com/questions/5372934/how-do-i-get-django-admin-to-delete-files-when-i-remove-an-object-from-the-datab
            except Exception as e:
                storage, name = instance.value.storage, instance.value.name
                storage.delete(name)
    except Exception as e:
        if instance.value.name:
            try:
                if os.path.isfile(instance.value.path):
                    os.remove(instance.value.path)
            # except block added to deal with S3 file deletion
            # see comments on 2nd answer below
            # http://stackoverflow.com/questions/5372934/how-do-i-get-django-admin-to-delete-files-when-i-remove-an-object-from-the-datab
            except Exception as e:
                storage, name = instance.value.storage, instance.value.name
                storage.delete(name)
```
