### ISSUE TITLE
models.0005_4_0_1 migration fails with integrity error

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4510]
**Describe the bug**

When replacing the default ontology and rerunning setup_db, the load fails with

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "ontologies_pkey"
DETAIL:  Key (ontologyid)=(e6e8db47-2ccf-11e6-927e-b8f6b115d7dd) already exists.
```

During the models.0005_4_0_1 phase.

I can't run `whatisthis` to find out what that refers to, as the state of the system is inconsistent -

```
django.db.utils.ProgrammingError: column cards.cssclass does not exist
LINE 1: ...", "cards"."description", "cards"."instructions", "cards"."c...
```

Does that migration assume that the default ontology has been loaded and is the CRM distributed in the code?

**To Reproduce**

My settings_local environment:
```
ONTOLOGY_PATH = 'ontology/linked_art'
ONTOLOGY_BASE = 'cidoc_crm_v6.2.4.xml'
ONTOLOGY_BASE_NAME = 'Linked Art'
ONTOLOGY_EXT = ['linkedart.xml', 'linkedart_crm_enhancements.xml']
```
(files are attached)

Run the setup_db *twice* and it fails on the second call.

**Screenshots**

```
(ENV) [rsanderson@GT26940 arches (master)]$ python ./manage.py packages -o setup_db
operation: setup_db
 pg_terminate_backend 
----------------------
(0 rows)

psql:/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/db/install/truncate_db.sql:3: NOTICE:  database "arches_linkedart" does not exist, skipping
DROP DATABASE
CREATE DATABASE
deleting index : strings
deleting index : resource
deleting index : resource_relations
creating index : strings
creating index : resource_relations
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, guardian, models, oauth2_provider, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying guardian.0001_initial... OK
  Applying models.0001_initial... OK
  Applying models.0002_40b4... OK
  Applying models.0003_40b4...deleting index : resource
 OK
  Applying models.0004_4_0_1... OK
  Applying models.0005_4_0_1...Traceback (most recent call last):
  File "./manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/management/commands/packages.py", line 140, in handle
    self.setup_db(package_name)
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/management/commands/packages.py", line 798, in setup_db
    management.call_command('migrate')
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/app/models/migrations/0005_4_0_1.py", line 19, in forwards_func
    version=settings.ONTOLOGY_BASE_VERSION, ontology_name=settings.ONTOLOGY_BASE_NAME, id=settings.ONTOLOGY_BASE_ID, extensions=','.join(extensions), verbosity=0)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/management/commands/load_ontology.py", line 87, in handle
    self.run_loader(data_source=options['source'], name=options['ontology_name'], version=options['version'], id=options['id'], extensions=options['extensions'], verbosity=options['verbosity'])
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/management/commands/load_ontology.py", line 132, in run_loader
    ontology = self.add_ontology(id=id, data_source=data_source, version=version, name=name)
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/management/commands/load_ontology.py", line 171, in add_ontology
    ontology, created = models.Ontology.objects.get_or_create(path=path, parentontology=parentontology, defaults={'version': version, 'name': name, 'path': path, 'pk': id})
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 506, in _create_object_from_params
    six.reraise(*exc_info)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 498, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "ontologies_pkey"
DETAIL:  Key (ontologyid)=(e6e8db47-2ccf-11e6-927e-b8f6b115d7dd) already exists.
```

**Expected behavior**

I would have expected this to load the ontology and give it the name "Linked Art"
[ontology.zip](https://github.com/archesproject/arches/files/2830096/ontology.zip)

**Comment by azaroth42** [comment]
Ahh.

When models.0001_initial runs, it creates a copy of the ontology files in arches/db/ontologies/. 
Then the next time setup_db is called, those files are still there, and interfere with the load.

So I think the bug is that setup_db does not clear this cache.

**Comment by mradamcox** [comment]
@azaroth42 we have done work on the `setup_db` process, which is currently in `stable/4.4.x` ahead of `4.4.2` and in `master`. Would you be able to re-test this ticket with the new command to confirm it is still a problem? From your comment above, it seems like it's likely to be, but I'd appreciate a double-check if you get a chance. Thanks!

**Comment by azaroth42** [comment]
Fixed
