### ISSUE TITLE
Exporting/Importing model with invalid JSON-LD context results in inconsistent state

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4736]
**Describe the bug**

Exporting a model from one system that has a local context (e.g. localhost:8001/media/context.json) and importing the model into another system that does not have that URL available, results in what appears to be an inconsistent state.

For me, with current master, the model imports but won't save until you remove the context from the configuration.  For @benosteen running from the docker image, it wouldn't import at all.

When I replace the context with a valid one, I can save changes to the config, but not change the model. It then complains about the description being invalid:

```
[02/Apr/2019 13:32:17] "GET /media/linked-art.json HTTP/1.1" 200 55931
Internal Server Error: /node/41a41e47-2e42-11e9-b5ee-a4d18cec433a
Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/models/graph.py", line 1229, in serialize
    ret['cards'] = self.get_cards() if 'cards' not in exclude else ret.pop('cards', None)
  File "/Users/rsanderson/Development/getty/arches/dev/project/arches/arches/app/models/graph.py", line 1180, in get_cards
    card.description = self.nodes[card.nodegroup_id].description
KeyError: UUID('1227b099-556f-11e9-8558-a4d18cec433a')
[02/Apr/2019 13:32:19] "POST /node/41a41e47-2e42-11e9-b5ee-a4d18cec433a HTTP/1.1" 500 26008
```

**To Reproduce**
1. Create a model with a valid context URL
2. Export the model
3. Make the context URL not point to anything or even not resolve at all
4. Import the model
5. Try to add a node to the model and save changes

**Comment by azaroth42** [comment]
Closing, don't do that then.
