### ISSUE TITLE
Default docker instruction likely incomplete to run arches. 

### ISSUE THREAD

**Issue by Carreau** [archesproject/arches#4790]
When following the default docker instructions, arches is not completely setup (?)

**To Reproduce**
1. Go to https://github.com/archesproject/arches/tree/master/docker#quick-start
2. Follow instructions
3. login as "admin/admin"
4. Go to "settings"
5. Get greeted by a 500

**Screenshots**

Not really relevant, if django switched to debug, the following traceback is available:

```
```
arches           | Internal Server Error: /settings/
arches           | Traceback (most recent call last):
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
arches           |     response = get_response(request)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
arches           |     response = self.process_exception_by_middleware(e, request)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
arches           |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
arches           |     return self.dispatch(request, *args, **kwargs)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
arches           |     return bound_func(*args, **kwargs)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
arches           |     return view_func(request, *args, **kwargs)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
arches           |     return func.__get__(self, type(self))(*args2, **kwargs2)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
arches           |     return handler(request, *args, **kwargs)
arches           |   File "/web_root/arches/arches/app/views/resource.py", line 93, in get
arches           |     resource_instance = Resource.objects.get(pk=resourceid)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
arches           |     return getattr(self.get_queryset(), name)(*args, **kwargs)
arches           |   File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
arches           |     self.model._meta.object_name
arches           | DoesNotExist: Resource matching query does not exist.
arches           | 172.18.0.6 - - [20/Apr/2019:14:05:08 -0500] "GET /settings/ HTTP/1.0" 500 112281 "http://localhost/user" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
```

**Expected behavior**

Don't get a 500 and see the settings page. 

**Your Arches Information**

*   Version used: 01aa133d07bbd33 (April 17) and  4.4.1
*   Operating System and version (desktop or mobile): macOS and Ubuntu
*   Browser Name and version: Chrome latest.

**Additional context**

Tried updating the docker-compose with a locally built arches from above commit. Same.
Docker volumes pruned to be sure to start from start. 

--- 

I'm likely missing something to correctly deploy arches. Note that I'm not a user and just deploying for somebody else, so I might be doing something wrong, I was just under the impression from the docker page that /settings/ should work without further modification.

**Comment by Carreau** [comment]
I have no real clues of what I am doing but it seem like running `docker-compose run arches setup_arches` in a separate terminal  helps. I can now get to the settings. 

Would something like `entrypoints.sh` need an update ? or the documentation ?

**Comment by Carreau** [comment]
> Would something like `entrypoints.sh`

Maybe  the following ? 
```diff
if [[ $#  -eq 0 ]]; then
+       wait_for_db
	run_arches
fi
```

**Comment by benosteen** [comment]
If you have already created an arches container image, then docker will opt
for that one unless you tell it otherwise (ie by making it use a specific
tagged version). If you change the arches branch (and so the codebase), you
might want to rebuild the image based on the current state of the code.

eg docker-compose build --no-cache arches

The default entrypoint.sh script tries to detect a few details to determine
what it will actually do. A lot of these things are drawn from the
environment variables that gets passed to the container (in 'environment:'
in the docker-compose). I'm going to assume that this is unchanged from the
git repository version, and that you do not have a ".env" file in the
directory overriding the environment variable settings.

By default then:

- it will test if the database and the elasticsearch service are up with
some simple commands. It will wait for these to succeed.
- Does the arches database exist? If yes, skip setting it up.
- Setting up the arches database ('setup_db' command) It will attempt
'python manage.py migrate', but will continue whether or not this succeeds.
By default, it will then load in the base system settings, as well as some
default models, concepts and graphs
     - set INSTALL_DEFAULT_GRAPHS=False and INSTALL_DEFAULT_CONCEPTS=False
to avoid adding in these default 'demo' graphs and concepts. It will then
do a 'yarn install' and download the required modules to a specified
directory.

- If the database is now set up, run the server. By default, this will run
with DJANGO_MODE=PROD, and will run a python manage.py collectstatic
command, before using gunicorn to run the application. The nginx proxy
server will serve the application to the outside world.

All of this takes quite a bit of time. I recommend running 'docker logs -f
arches' in a commandline window after doing the docker-compose up, to watch
what the arches container actually does.

Not saying this will address the issue you are hitting but I hope it gives
you more information to track down why this is happening to you.

Ben

**Comment by bptarpley** [comment]
FWIW, I had to do the following to get the latest commit (55cdfa9) of Arches up and running using the docker-compose file in the repo:

After setting all the environment variables correctly, I commented out "command: run_arches" and replaced it with "command: tail -F /dev/null". I then ran docker-compose up, which initializes all the containers and runs the "arches" container in a kind of standby mode (it's just tailing nothing).

In a separate terminal window, i ran: "docker exec -it arches bash" in order to access the bash shell of arches container. I then ran the following commands to create the postgis template database:

psql -U postgres -c "CREATE DATABASE template_postgis;"
psql -U postgres -d template_postgis -c "CREATE EXTENSION postgis;"

I then exited docker-compose up, and edited the docker-compose.yml file, deleting the "command: tail -F /dev/null" line and adding "command: setup_arches". I then restarted docker-compose, let it run through the setup stuff, and then exited docker-compose. I then edited docker-compose.yml again, this time deleting "command: setup_arches," and uncommenting out "command: run_arches." Things seemed to run fine at that point.

It seems to be incorrectly assumed that the template database will already exist given the current docker-compose.yml. I should also point out that the data persistence directory for the couchdb image should be /opt/couchdb/data instead of what's actually specified in the docker-compose file (https://hub.docker.com/_/couchdb).

**Comment by benosteen** [comment]
Yes, the templace needs to be set up by a superuser/similar on the postgres instance. The PG SQL file at https://github.com/archesproject/arches/blob/master/arches/install/init-unix.sql contains what I believe is necessary for the template database. If you are running as a privileged postgres account, then the permission setting may not be necessary. The GIS side of it is not something I use though.

The docker-compose file should bind mount that file in so that the postgres entrypoint script should run it at boot - is this not being successfully executed?

**Comment by bptarpley** [comment]
I verified that the .sql file in question was indeed bind mounted in the db container, but for some reason every time I started with fresh volumes and tried to run "setup_arches" it complained that the template database didn't exist. It _did_ seem to create a template database called "template0" though, so perhaps it just isn't getting named properly?
