### ISSUE TITLE
es setup_indexes raises UnboundLocalError for 'status'

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5034]
**Describe the bug**

Running `python manage.py es index_database` results in the following error:

```
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rsanderson/Development/getty/arches/linked_art/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/management/commands/es.py", line 76, in handle
    index_database.index_db(clear_index=options['clear_index'], batch_size=options['batch_size'])
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/app/utils/index_database.py", line 25, in index_db
    index_resources(clear_index=clear_index, batch_size=batch_size)
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/app/utils/index_database.py", line 45, in index_resources
    index_resources_by_type(resource_types, clear_index=clear_index, batch_size=batch_size)
  File "/Users/rsanderson/Development/getty/arches/linked_art/arches/arches/app/utils/index_database.py", line 90, in index_resources_by_type
    return status
UnboundLocalError: local variable 'status' referenced before assignment
```

**To Reproduce**
Per https://arches.readthedocs.io/en/stable/arches-and-elasticsearch/, run the delete, setup and reindex commands.

**Comment by azaroth42** [comment]
Haven't seen this recently. Closing.
