### ISSUE TITLE
Thesaurus fails to import to RDM via command line

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5053]
**Describe the bug**

Having exported the Thesaurus and Collections from a 4.1 era installation, the current master does not import the data.

It fails with the following traceback:

```
(ENV) [rsanderson@GT26940 arches (master)]$ python manage.py packages -o import_reference_data -s '~/Development/getty/arches/dev/project/config/rdm/thesaurus.skos.xml' 

operation: import_reference_data
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/rsanderson/Development/getty/arches/test/arches/arches/management/commands/packages.py", line 234, in handle
    self.import_reference_data(options['source'], options['overwrite'], options['stage'])
  File "/Users/rsanderson/Development/getty/arches/test/arches/arches/management/commands/packages.py", line 945, in import_reference_data
    rdf = skos.read_file(data_source)
  File "/Users/rsanderson/Development/getty/arches/test/arches/arches/app/utils/skos.py", line 62, in read_file
    raise Exception('Error occurred while parsing the file %s' % path_to_file)
Exception: Error occurred while parsing the file ~/Development/getty/arches/dev/project/config/rdm/thesaurus.skos.xml
```

**To Reproduce**

* Download attached file: [thesaurus.zip](https://github.com/archesproject/arches/files/3457758/thesaurus.zip)
* Try to import it as per above
* See above error

**Expected behavior**

The (re-)creation of the concepts in the new instance.

**Comment by azaroth42** [comment]
Update to note that the import on the exact same file does work when done via the RDM web interface.

After selecting the file in RDM/tools to import, it uploads and parses correctly, resulting in the expected concept tree.

![Screen Shot 2019-08-01 at 9 52 29 AM](https://user-images.githubusercontent.com/871868/62312093-2d28ca80-b442-11e9-8f79-55e6017dee6d.png)

Thus the bug seems to be somewhere in the command line process ... or PICNIC (Problem in chair, not in computer :D)

**Comment by azaroth42** [comment]
PICNIC - don't use ''s despite the instructions!
