### ISSUE TITLE
API exception manager raises exception

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5116]
**Describe the bug**

There is a bug in the logging of exceptions in `views/api.py`, where logger.exception() is called with the wrong number of arguments at line 263.

```
Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/rsanderson/Development/getty/arches/test/arches/arches/app/views/api.py", line 119, in dispatch
    return super(APIBase, self).dispatch(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/test/arches/arches/app/views/api.py", line 263, in get
    logger.exception()
TypeError: exception() takes at least 2 arguments (1 given)
```

**To Reproduce**

One way to cause the exception is to send data to the JSON-LD import API using a class that does not appear in the model. (blush)

**Comment by benosteen** [comment]
Fixed in pull request #5181
