### ISSUE TITLE
Setting ONTOLOGY_BASE_ID to a non-default value causes migrations to fail on a new install

### ISSUE THREAD

**Issue by benosteen** [archesproject/arches#5268]
**Describe the bug**
New install, empty database, but with ONTOLOGY_BASE_ID set in `settings.py or overridden by`settings_local.py` to something other than the default ("e6e8db47-2ccf-11e6-927e-b8f6b115d7dd").

Migrations then fail, as at least one of them explicitly uses the default ontology ID:

```deleting index : arches_terms
deleting index : arches_concepts
deleting index : arches_resources
deleting index : arches_resource_relations
creating index : arches_terms
creating index : arches_concepts
creating index : arches_resource_relations
creating index : arches_resources
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, guardian, models, oauth2_provider, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying guardian.0001_initial... OK
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/web_root/arches/arches/management/commands/setup_db.py", line 50, in handle
    self.setup_db()
  File "/web_root/arches/arches/management/commands/setup_db.py", line 185, in setup_db
    management.call_command('migrate')
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 109, in __exit__
    self.execute(sql)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/web_root/ENV/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: insert or update on table "graphs" violates foreign key constraint "graphs_ontologyid_2bd4ec07_fk_ontologies_ontologyid"
DETAIL:  Key (ontologyid)=(e6e8db47-2ccf-11e6-927e-b8f6b115d7dd) is not present in table "ontologies".

  Applying models.0001_initial...
```

I think https://github.com/archesproject/arches/blob/master/arches/app/models/migrations/3201_replace_node_and_nodetype_branches.py causes a key error here (due to its use of a hard-coded ontology UUID) but there may be other migrations that are problematic.

**Expected behavior**
Changing an open setting in `settings.py` such as ONTOLOGY_BASE_ID shouldn't cause a opaque error. If ONTOLOGY_BASE_ID must always be equal to `e6e8db47-2ccf-11e6-927e-b8f6b115d7dd` then it shouldn't be a configurable setting.

**Your Arches Information**

*   Version used: master
*   Operating System and version: dockerized install

**Comment by chiatt** [comment]
I think the thing to do here might be to hard-code the default ontology id in the migration rather than use the setting variable given that whatever gets loaded in the migration is going to get deleted anyhow.

**Comment by chiatt** [comment]
I'm going to close this because the ONTOLOGY_BASE_ID is no longer used in Arches.
