### ISSUE TITLE
search_engine_factory issue

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5369]
post python3 upgrade, arches Search breaks which implicates any lookup or creation of a resource. In reproducing by going to the Search page, one of the exceptions is traced to: `search_engine_factory.py`

```
Traceback (most recent call last):
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/galenmancino/repos/arches/arches/app/views/search.py", line 298, in time_wheel_config
    config = time_wheel.time_wheel_config(request.user)
  File "/Users/galenmancino/repos/arches/arches/app/search/time_wheel.py", line 12, in time_wheel_config
    se = SearchEngineFactory().create()
  File "/Users/galenmancino/repos/arches/arches/app/search/search_engine_factory.py", line 29, in create
    _temp = __import__(modulename, globals(), locals(), [classname], -1)
ValueError: level must be >= 0
```

**Comment by whatisgalen** [comment]
resolved by setting `level` to 0. See docs for change in method signature:
https://docs.python.org/2/library/functions.html#__import__
https://docs.python.org/3/library/functions.html#__import__
