### ISSUE TITLE
Error on tile save in resource editor

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5380]
saving a new tile to a resource in resource editor returns this error:
```
Failed to fetch resource instance descriptors
Traceback (most recent call last):
  File "/Users/galenmancino/Projects/consultations-prj/consultations_prj/views/resource.py", line 57, in get
    document = se.search(index='resources', id=resourceid)
  File "/Users/galenmancino/repos/arches/arches/app/search/search.py", line 120, in search
    return self.es.get(**kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: get() missing 1 required positional argument: 'doc_type'
Not Found: /resource/descriptors/9d736d90-eea8-11e9-8f61-784f435179ea
```

**Comment by whatisgalen** [comment]
no longer occurring, closing
