### ISSUE TITLE
cannot delete tiles

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5408]
no alert occurs when "delete" fails

Full stack trace:
```
Internal Server Error: /tile
Traceback (most recent call last):
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/galenmancino/repos/arches/arches/app/views/tile.py", line 239, in delete
    tile.delete(request=request)
  File "/Users/galenmancino/repos/arches/arches/app/models/tile.py", line 394, in delete
    self.__preDelete(request)
  File "/Users/galenmancino/repos/arches/arches/app/models/tile.py", line 489, in __preDelete
    for function in self.__getFunctionClassInstances():
  File "/Users/galenmancino/repos/arches/arches/app/models/tile.py", line 503, in __getFunctionClassInstances
    for functionXgraph in functionXgraphs:
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/psycopg2/_json.py", line 101, in getquoted
    s = self.dumps(self.adapted)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/contrib/postgres/fields/jsonb.py", line 27, in dumps
    return json.dumps(obj, **options)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UUID is not JSON serializable
[18/Oct/2019 16:11:55] "DELETE /tile HTTP/1.1" 500 25764
Internal Server Error: /tile
Traceback (most recent call last):
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/galenmancino/repos/arches/arches/app/views/tile.py", line 239, in delete
    tile.delete(request=request)
  File "/Users/galenmancino/repos/arches/arches/app/models/tile.py", line 394, in delete
    self.__preDelete(request)
  File "/Users/galenmancino/repos/arches/arches/app/models/tile.py", line 489, in __preDelete
    for function in self.__getFunctionClassInstances():
  File "/Users/galenmancino/repos/arches/arches/app/models/tile.py", line 503, in __getFunctionClassInstances
    for functionXgraph in functionXgraphs:
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/psycopg2/_json.py", line 101, in getquoted
    s = self.dumps(self.adapted)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/contrib/postgres/fields/jsonb.py", line 27, in dumps
    return json.dumps(obj, **options)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UUID is not JSON serializable
```

**Comment by chiatt** [comment]
Hey @whatisgalen, this should be working now in the latest on python3. I think I inadvertently fixed it while working on another issue. Can you confirm?

**Comment by whatisgalen** [comment]
I can confirm tile save works as expected. Closing
