### ISSUE TITLE
can edit relatable resources on model after model instances exist

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5422]
After a model has been made "active" and resource instances have been created, a user can still edit a graph to amend or remove other models to relate to it. 

When a user tries to relate resources to a new instance, resources may appear to be appended in the select2 input, but when the user clicks "add", the input clears and no error appears onscreen. On the backend, the following error:
```
Internal Server Error: /resource/related/
Traceback (most recent call last):
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/galenmancino/repos/arches/arches/app/views/resource.py", line 831, in post
    permitted = confirm_relationship_permitted(instanceid, root_resourceinstanceid[0])
  File "/Users/galenmancino/repos/arches/arches/app/views/resource.py", line 824, in confirm_relationship_permitted
    relatable_to = get_relatable_resources(resource_instance_to.graph_id)
  File "/Users/galenmancino/repos/arches/arches/app/views/resource.py", line 818, in get_relatable_resources
    relatable_resources = [str(node.graph_id) for node in top_node.get_relatable_resources()]
  File "/Users/galenmancino/repos/arches/arches/app/views/resource.py", line 818, in <listcomp>
    relatable_resources = [str(node.graph_id) for node in top_node.get_relatable_resources()]
AttributeError: 'NoneType' object has no attribute 'graph_id'
```

**Comment by apeters** [comment]
is there anything to review here?
