### ISSUE TITLE
cannot edit mobile survey (collector project) after activated

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5424]
From collector manager:
```
Internal Server Error: /collector_designer/5df97e93-417f-41e8-ac8c-f9f2c52a5bdc
Traceback (most recent call last):
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/galenmancino/repos/arches/arches/app/views/mobile_survey.py", line 182, in get
    history = get_history(survey, history)
  File "/Users/galenmancino/repos/arches/arches/app/views/mobile_survey.py", line 138, in get_history
    sync_log_records = list(models.MobileSyncLog.objects.order_by('-finished').values()).filter(survey=survey)
AttributeError: 'list' object has no attribute 'filter'
```

**Comment by apeters** [comment]
fixed in the latest
