### ISSUE TITLE
graph designer breaks due to relatable resource issue

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5425]
from graph designer:
```
Internal Server Error: /graph_designer/8d41e49e-a250-11e9-9eab-00224800b26d
Traceback (most recent call last):
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/galenmancino/repos/arches/arches/app/views/graph.py", line 227, in get
    '_functions'])
  File "/Users/galenmancino/repos/arches/arches/app/utils/betterJSONSerializer.py", line 50, in serialize
    obj = self.serializeToPython(obj, **options)
  File "/Users/galenmancino/repos/arches/arches/app/utils/betterJSONSerializer.py", line 47, in serializeToPython
    return self.handle_object(obj, self.selected_fields, self.exclude)
  File "/Users/galenmancino/repos/arches/arches/app/utils/betterJSONSerializer.py", line 86, in handle_object
    return self.handle_object(getattr(object, 'serialize')(fields, exclude), fields, exclude)
  File "/Users/galenmancino/repos/arches/arches/app/models/graph.py", line 1230, in serialize
    ret['relatable_resource_model_ids'] = [str(relatable_node.graph_id) for relatable_node in self.root.get_relatable_resources()]
  File "/Users/galenmancino/repos/arches/arches/app/models/graph.py", line 1230, in <listcomp>
    ret['relatable_resource_model_ids'] = [str(relatable_node.graph_id) for relatable_node in self.root.get_relatable_resources()]
AttributeError: 'NoneType' object has no attribute 'graph_id'
```

**Comment by apeters** [comment]
fixed in the latest
