### ISSUE TITLE
arches-project create fails on python3

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5435]

**Comment by apeters** [comment]
this fails for me with the following error
```(ENV) Alexeis-MacBook-Pro:arches4 alexei$ arches-project create taco
Traceback (most recent call last):
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (arches 5.0 (/Users/alexei/Work/Projects/arches4), Requirement.parse('arches==4.4.1'))

**Comment by chiatt** [comment]
This is working for me, but I seem to remember getting a similar error. It's not clear to me how django admin commands that do not use manage.py point to their code. There must be some stale link to your v4 install. Can you try creating an entirely new virtualenv, installing arches in it and the command again? Uninstalling and then reinstalling arches in your virutalenv might work too.

**Comment by chiatt** [comment]
@apeters I'm going to assign to @whatisgalen to see if he is getting the same error that you are.

**Comment by whatisgalen** [comment]
works as expected on latest, closing
