### ISSUE TITLE
search is broken in master

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5450]
```
Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rsanderson/Development/getty/arches/test/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rsanderson/Development/getty/arches/test/arches/arches/app/views/search.py", line 208, in search_results
    search_filter.post_search_hook(search_results_object, results, permitted_nodegroups)
  File "/Users/rsanderson/Development/getty/arches/test/arches/arches/app/search/components/paging_filter.py", line 37, in post_search_hook
    total = results['hits']['total']['value'] if results['hits']['total']['value'] <= settings.SEARCH_RESULT_LIMIT else settings.SEARCH_RESULT_LIMIT
TypeError: 'int' object has no attribute '__getitem__'```

**Comment by chiatt** [comment]
Works as expected
