### ISSUE TITLE
unable to save collector project

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5456]
in admin account running consultations, set up a collector project with only consultations model instances, picked 
- Name
- Dates
- Consultation Details
- Map
- Conditions

Available to crowdsource editors

start: 2019-09-01
end: 2019-11-30

on saving "activate", received the following errors:
```
bounds is not a string
Internal Server Error: /collector_designer/3493bc1f-ada9-4a89-842b-00953b87fb2b
Traceback (most recent call last):
  File "/Users/galenmancino/repos/arches/arches/app/models/mobile_survey.py", line 389, in collect_resource_instances_for_couch
    self.append_to_instances(request, instances, res_type)
  File "/Users/galenmancino/repos/arches/arches/app/models/mobile_survey.py", line 350, in append_to_instances
    for hit in search_res['results']['hits']['hits']:
KeyError: 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/galenmancino/repos/arches/arches/app/views/mobile_survey.py", line 347, in post
    mobile_survey.save()
  File "/Users/galenmancino/repos/arches/arches/app/models/mobile_survey.py", line 74, in save
    self.load_data_into_couch()
  File "/Users/galenmancino/repos/arches/arches/app/models/mobile_survey.py", line 449, in load_data_into_couch
    instances = self.collect_resource_instances_for_couch()
  File "/Users/galenmancino/repos/arches/arches/app/models/mobile_survey.py", line 393, in collect_resource_instances_for_couch
    print('no instances found in', search_res)
UnboundLocalError: local variable 'search_res' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/galenmancino/repos/arches/arches/app/views/mobile_survey.py", line 351, in post
    if 'strerror' in e and e.strerror == 'Connection refused' or 'Connection refused' in e:
TypeError: argument of type 'UnboundLocalError' is not iterable

```

**Comment by chiatt** [comment]
Mobile surveys are saving as expected
