### ISSUE TITLE
Ensure collector sync works with dependency upgrades

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5508]

**Comment by apeters** [comment]
I"m getting this error in the latest when trying to connect
```Internal Server Error: /auth/get_client_id
Traceback (most recent call last):
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/alexei/Work/Projects/arches4/arches/app/views/auth.py", line 253, in post
    is_reviewer = user_is_resource_reviewer(user.userprofile)
  File "/Users/alexei/Work/Projects/arches4/arches/app/utils/permission_backend.py", line 194, in user_is_resource_reviewer
    return user.groups.filter(name='Resource Reviewer').exists()
AttributeError: 'UserProfile' object has no attribute 'groups'```

**Comment by apeters** [comment]
fixed in the latest
