### ISSUE TITLE
datatype update tries to update non-existent issearchable

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5557]
**Describe the bug**

On line 114 of arches/management/commands/datatype.py, it tries to set instance.issearchable ... which is not created by the datatype registration function at line 55.

Thus it fails to update.

Solution seems to be just to delete that line :)

**To Reproduce**

* Register a datatype
* Try to update it.

**Screenshots**

```
(ENV) [rsanderson!GT29625 tests_prj]$ python manage.py datatype update --source tests_prj/datatypes/semantic_like.py 
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/management/commands/datatype.py", line 47, in handle
    self.update(source=options['dt_source'])
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/management/commands/datatype.py", line 114, in update
    instance.issearchable = details['issearchable']
KeyError: 'issearchable'
```

**Comment by apeters** [comment]
should we really be checking for this one missing property?  What about all the other properties?

**Comment by chiatt** [comment]
@apeters This is the only important one because it was missing from the sample datatype and documentation.

**Comment by apeters** [comment]
fixed in the latest
