### ISSUE TITLE
Setting Slug for a model prevents it being cloned

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#5589]
**Describe the bug**

When an import URI slug has been set for a model, the `slug` field in the exported model JSON, it becomes impossible to clone the model.  This is because the system tries to duplicate the slug, and the slug is set to be (necessarily) unique, thus is prevented to avoid the inconsistency.

This would not be a problem if:

a) there was a UI to set the slug for the model, it could be set to "" before cloning.
b) better, the clone operation would not attempt to set the slug and just leave it blank

**To Reproduce**

* Create a model.
* Either:
  * a) go into postgres and set the slug field for the model
  * b) export the model to JSON, edit the file to set the slug, reload the model
* Try to clone the model
 
**Screenshots**

```
Internal Server Error: /graph/a7b1a7c5-b25b-11e9-8a4e-a4d18cec433a/clone
Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "graphs_slug_key"
DETAIL:  Key (slug)=(textual_work) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/views/graph.py", line 349, in post
    ret.save()
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/models/graph.py", line 343, in save
    super(Graph, self).save()
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/base.py", line 740, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/base.py", line 777, in save_base
    updated = self._save_table(
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/base.py", line 907, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "graphs_slug_key"
DETAIL:  Key (slug)=(textual_work) already exists.
```

**Expected behavior**

The model should be cloned.

**Your Arches Information**

master branch

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
re #6071

**Comment by ryan86** [comment]
meets requirements
