### ISSUE TITLE
use celery (where available) to refresh geometry materialized view

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches#5602]
The refreshing of the geometry materialized view that occurs here can take a long time w/ very large datasets: https://github.com/archesproject/arches/blob/master/arches/app/datatypes/datatypes.py#L977-L983

We should take advantage of celery (if available) to refresh this view asynchronously.

**Comment by robgaston** [comment]
@whatisgalen after pulling the latest, package load seems to be broken when executed w/o celery running - can you please take a look?

**Comment by robgaston** [comment]
actually, this seems to cause errors w/ package load even if celery is running

**Comment by robgaston** [comment]
here's the traceback I'm seeing:
```
***** Errors occured during import. Some data may not have been imported. For more information, check resource import error log: /Users/rgaston/Projects/arches4/consultations-prj/consultations_prj/logs/resource_import.log
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/rgaston/Projects/arches4/arches/arches/management/commands/packages.py", line 296, in handle
    options["source"], options["setup_db"], options["overwrite"], options["bulk_load"], options["stage"], options["yes"]
  File "/Users/rgaston/Projects/arches4/arches/arches/management/commands/packages.py", line 796, in load_package
    load_business_data(package_location)
  File "/Users/rgaston/Projects/arches4/arches/arches/management/commands/packages.py", line 627, in load_business_data
    self.import_business_data(path, overwrite=True, bulk_load=bulk_load)
  File "/Users/rgaston/Projects/arches4/arches/arches/management/commands/packages.py", line 948, in import_business_data
    use_multiprocessing=use_multiprocessing,
  File "/Users/rgaston/Projects/arches4/arches/arches/app/utils/data_management/resources/importer.py", line 237, in import_business_data
    datatype_instance.after_update_all()
  File "/Users/rgaston/Projects/arches4/arches/arches/app/datatypes/datatypes.py", line 990, in after_update_all
    celery_worker_running = task_management.check_if_celery_available()
  File "/Users/rgaston/Projects/arches4/arches/arches/app/utils/task_management.py", line 18, in check_if_celery_available
    result = inspect.ping()
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/celery/app/control.py", line 138, in ping
    return self._request('ping')
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/celery/app/control.py", line 106, in _request
    pattern=self.pattern, matcher=self.matcher,
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/celery/app/control.py", line 477, in broadcast
    limit, callback, channel=channel,
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/kombu/pidbox.py", line 346, in _broadcast
    matcher=matcher)
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/kombu/pidbox.py", line 302, in _publish
    maybe_declare(self.reply_queue(channel))
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/kombu/common.py", line 121, in maybe_declare
    return _maybe_declare(entity, channel)
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/kombu/common.py", line 161, in _maybe_declare
    entity.declare(channel=channel)
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/kombu/entity.py", line 608, in declare
    self._create_exchange(nowait=nowait, channel=channel)
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/kombu/entity.py", line 615, in _create_exchange
    self.exchange.declare(nowait=nowait, channel=channel)
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/kombu/entity.py", line 186, in declare
    nowait=nowait, passive=passive,
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/amqp/channel.py", line 614, in exchange_declare
    wait=None if nowait else spec.Exchange.DeclareOk,
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/amqp/abstract_channel.py", line 59, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/amqp/method_framing.py", line 172, in write_frame
    write(view[:offset])
  File "/Users/rgaston/Projects/arches4/env3/lib/python3.7/site-packages/amqp/transport.py", line 284, in write
    self._write(s)
BrokenPipeError: [Errno 32] Broken pipe```

**Comment by chiatt** [comment]
Works as expected
