### ISSUE TITLE
search export (download) breaks on FileNotFoundError if zip file path isn't correct

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5678]
Trace:

```
2019-12-11 19:30:57,729 arches.app.tasks WARNING  [Errno 2] No such file or directory: '/Users/galenmancino/Projects/lincoln-prj/lincoln/uploadedfiles/Arches_2019-12-11T19:30:57.709283.zip'
[2019-12-11 19:30:57,729: WARNING/ForkPoolWorker-8] [Errno 2] No such file or directory: '/Users/galenmancino/Projects/lincoln-prj/lincoln/uploadedfiles/Arches_2019-12-11T19:30:57.709283.zip'
[2019-12-11 19:30:57,739: ERROR/ForkPoolWorker-8] Task arches.app.tasks.export_search_results[a93f1ee2-8e0e-4083-89d9-ba955e3125f8] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/galenmancino/repos/venv/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/galenmancino/repos/arches/arches/app/tasks.py", line 33, in export_search_results
    msg = zip_utils.write_zip_file(exporter.export(format), return_relative_url=True)
  File "/Users/galenmancino/repos/arches/arches/app/utils/data_management/zip.py", line 64, in write_zip_file
    with open(location, "wb") as f:  # use `wb` mode
FileNotFoundError: [Errno 2] No such file or directory: '/Users/galenmancino/Projects/lincoln-prj/lincoln/uploadedfiles/Arches_2019-12-11T19:30:57.709283.zip'
```

**Comment by whatisgalen** [comment]
was resolved by adding `uploadedfiles` dir to the `lincoln-prj` repo (via changing the gitignore), closing
