### ISSUE TITLE
Installation error elasticsearch.exceptions on setup_db

### ISSUE THREAD

**Issue by natuk** [archesproject/arches#5731]
**Describe the bug**
The installation process on Ubuntu 18.04 Desktop stops with an error:
```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception', u'Root mapping definition has unsupported parameters:  [concept : {properties={provisional={type=boolean}, top_concept={type=keyword}, conceptid={type=keyword}, language={type=keyword}, id={type=keyword}, category={type=keyword}, type={type=keyword}, value={analyzer=standard, fields={raw={type=keyword}, folded={analyzer=folding, type=text}}, type=text}}}] [term : {properties={provisional={type=boolean}, resourceinstanceid={type=keyword}, nodegroupid={type=keyword}, tileid={type=keyword}, nodeid={type=keyword}, value={analyzer=standard, fields={raw={type=keyword}, folded={analyzer=folding, type=text}}, type=text}}}]')
```

**To Reproduce**
1. Follow installation instructions from [here](https://arches.readthedocs.io/en/stable/installation/).
2. Update `settings_local.py` by
* uncommenting the `DATABASE` block and
* renaming the template by changing from `"POSTGIS_TEMPLATE": "template_postgis_20"` to `"POSTGIS_TEMPLATE": "template_postgis"`
3. Check ElasticSearch service is running.
4. Enter `python manage.py packages -o setup_db`
5. Process stops with the above error.

**Expected behavior**
The process to complete with the database setup properly.

**Your Arches Information**
*   Version used: 4
*   Operating System and version (desktop or mobile): Ubuntu 18.04 Desktop

**Additional context**
Dependencies installed using the `ubuntu_setup.sh` script.

**Comment by mradamcox** [comment]
Hm, this doesn't seem like a common error. Could you post a little more of the console output, just so we can see what's happening before the error?
(btw thanks for all the tickets in the docs repo :))

**Comment by natuk** [comment]
I hope I have not missed anything obvious. Here is the complete command line output:
```sh
thanasis@arches:~$ cd Projects
thanasis@arches:~/Projects$ source ENV/bin/activate
(ENV) thanasis@arches:~/Projects$ cd my_project/
(ENV) thanasis@arches:~/Projects/my_project$ systemctl status elasticsearch
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendo
   Active: active (running) since Fri 2019-12-20 09:17:09 GMT; 5min ago
     Docs: http://www.elastic.co
 Main PID: 1190 (java)
    Tasks: 70 (limit: 4915)
   CGroup: /system.slice/elasticsearch.service
           ├─1190 /usr/share/elasticsearch/jdk/bin/java -Des.networkaddress.cach
           └─2375 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_

Dec 20 09:16:45 arches systemd[1]: Starting Elasticsearch...
Dec 20 09:16:46 arches elasticsearch[1190]: OpenJDK 64-Bit Server VM warning: Op
Dec 20 09:17:09 arches systemd[1]: Started Elasticsearch.
(ENV) thanasis@arches:~/Projects/my_project$ python manage.py packages -o setup_db
2019-12-20 03:23:01,835 arches.app.views.api DEBUG    Dispatching Couch Proxy
operation: setup_db
Drop and recreate the database...

SELECT pg_terminate_backend(pid) FROM pg_stat_activity
    WHERE datname IN ('arches', 'template_postgis');

DROP DATABASE IF EXISTS arches;

CREATE DATABASE arches
    WITH OWNER = postgres
        ENCODING = 'UTF8'
        CONNECTION LIMIT=-1
        TEMPLATE = template_postgis;

deleting index : my_project_strings
deleting index : my_project_resource
deleting index : my_project_resource_relations
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/arches/management/commands/packages.py", line 169, in handle
    self.setup_db(package_name)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/arches/management/commands/packages.py", line 702, in setup_db
    management.call_command("setup_db", force=True)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/arches/management/commands/setup_db.py", line 51, in handle
    self.setup_db()
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/arches/management/commands/setup_db.py", line 183, in setup_db
    prepare_term_index(create=True)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/arches/app/search/mappings.py", line 87, in prepare_term_index
    se.create_index(index='strings', body=index_settings)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/arches/app/search/search.py", line 161, in create_index
    self.es.indices.create(**kwargs)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 107, in create
    params=params, body=body)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/thanasis/Projects/ENV/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception', u'Root mapping definition has unsupported parameters:  [concept : {properties={provisional={type=boolean}, top_concept={type=keyword}, conceptid={type=keyword}, language={type=keyword}, id={type=keyword}, category={type=keyword}, type={type=keyword}, value={analyzer=standard, fields={raw={type=keyword}, folded={analyzer=folding, type=text}}, type=text}}}] [term : {properties={provisional={type=boolean}, resourceinstanceid={type=keyword}, nodegroupid={type=keyword}, tileid={type=keyword}, nodeid={type=keyword}, value={analyzer=standard, fields={raw={type=keyword}, folded={analyzer=folding, type=text}}, type=text}}}]')
(ENV) thanasis@arches:~/Projects/my_project$ 
```

**Comment by mradamcox** [comment]
Hmm, I expect this has to do with the ES version. Which release are you using, and which arches branch are you using? On the master branch of arches you must use ES 7, on the stable/4.4.x branch, and if you pip install arches, you must use ES 5.x

**Comment by natuk** [comment]
Yes, this is it. I changed the ubuntu_setup.sh script to version 5.x of elasticsearch repos and went through the same process and the database seems to have been setup properly. Perhaps clarify in the documentation that the current ubuntu_setup.sh script is compatible with the master branch and create a separate one with version 5.x for the stable branch dependencies. Will post again if I notice anything else. Many thanks.

**Comment by mradamcox** [comment]
We did consider that but decided to keep a single setup script. If you are on the stable branch, then that script just won't have ES included in it (as that's a v5 addition), and you should be using the /stable documentation.

**Comment by natuk** [comment]
OK, in which case the problem may be that the link to the Linux installation scripts (stable documentation) in this page:

https://arches.readthedocs.io/en/stable/requirements-and-dependencies/

points to the master branch as opposed to stable.

**Comment by mradamcox** [comment]
@natuk great catch. I'll fix that.
