### ISSUE TITLE
syntax error with ontology load command

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5809]
when calling the command `python manage.py load_ontology -s cidoc_crm` a syntax error is thrown
```Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/alexei/Work/Projects/arches4/virtualenv/ENV/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/alexei/Work/Projects/arches4/arches/management/commands/load_ontology.py", line 77, in handle
    if ontology_version is None:
UnboundLocalError: local variable 'ontology_version' referenced before assignment
```

**Comment by njkim** [comment]
It works as expected
