### ISSUE TITLE
psycopg2.errors.AdminShutdown when running setup_db

### ISSUE THREAD

**Issue by ekeydar** [archesproject/arches#6219]
I'm trying to install arches on ubuntu 20.04
When I ran the python manage.py db_setup I get the following:

```
(arches1) ubuntu@ip-172-30-0-60:~/projects/my_project$ python manage.py setup_db
Are you sure you want to destroy and rebuild your database? [y/N] y
Drop and recreate the database...

SELECT pg_terminate_backend(pid) FROM pg_stat_activity
    WHERE datname IN ('my_project', 'template_postgis');
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/envs/arches1/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/envs/arches1/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/envs/arches1/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/envs/arches1/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/envs/arches1/lib/python3.8/site-packages/arches/management/commands/setup_db.py", line 52, in handle
    self.setup_db()
  File "/home/ubuntu/envs/arches1/lib/python3.8/site-packages/arches/management/commands/setup_db.py", line 186, in setup_db
    self.drop_and_recreate_db(cursor)
  File "/home/ubuntu/envs/arches1/lib/python3.8/site-packages/arches/management/commands/setup_db.py", line 137, in drop_and_recreate_db
    cursor.execute(terminate_sql)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
SSL connection has been closed unexpectedly
```

**Comment by chiatt** [comment]
Hi @ekeydar - sorry to get to this so late. Are you still having this problem? 
If you run into other installation issues, you can post your issue on the forum: https://groups.google.com/u/1/g/archesproject?pli=1
There is a larger segment of the community in the forum that can assist with these kind of problems.

**Comment by chiatt** [comment]
Closing because this issue has not come up again.
