### ISSUE TITLE
(6263) tiledata assumed to be list, can be dict

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6276]
**Describe the bug**

The resource-instance datatype assumes that the incoming tile data is a list ... which is true when the information comes from a resource-instance-list, but not when it's a real resource-instance.

The symptom is that it iterates over the keys of the dictionary rather than the dict items in a list, resulting in this traceback:

```
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/rsanderson/Development/getty/arches/current/projects/provenance2/provenance2/management/commands/load_jsonld.py", line 108, in handle
    self.load_resources(
  File "/Users/rsanderson/Development/getty/arches/current/projects/provenance2/provenance2/management/commands/load_jsonld.py", line 215, in load_resources
    self.import_resource(uu, graphid, jsdata, reload=force, quiet=quiet)
  File "/Users/rsanderson/Development/getty/arches/current/projects/provenance2/provenance2/management/commands/load_jsonld.py", line 317, in import_resource
    resource.save(request=None)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/models/resource.py", line 113, in save
    saved_tile = tile.save(request=request, index=False)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/models/tile.py", line 339, in save
    datatype.pre_tile_save(self, nodeid)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/datatypes/datatypes.py", line 1670, in pre_tile_save
    "resourceinstanceidto_id": related_resource["resourceId"],
TypeError: string indices must be integers
```

The solution is to change line 1647+ in datatypes/datatypes.py, the pre_tile_save() function for resource instance datatype:

```
    def pre_tile_save(self, tile, nodeid):
        tiledata = tile.data[str(nodeid)]
        # Ensure tiledata is a list
        if type(tiledata) != list:
            tiledata = [tiledata]
```

And the same in append_to_document():

```
    def append_to_document(self, document, nodevalue, nodeid, tile, provisional=False):
        if type(nodevalue) != list:
            nodevalue = [nodevalue]
```

**Comment by azaroth42** [comment]
Fixed, closing
