### ISSUE TITLE
Addition of a pre-existing branch to another branch causing error

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6347]
@Philbox commented on [Fri Jun 26 2020](https://github.com/archesproject/arches-her/issues/516)

When adding a branch to another branch the new branch won't save any node except the root node if the 'Place node(s) in separate card' is toggled to off.

1. Open any branch to be modified (eg. Designation and Protection Assignment)
2. Select Root Node
3. Click 'Add branch' icon - Branch library opens
4. Select Type branch
5. Select 'P2 has type'
6. Toggle 'Place node(s) in a separate card' to off

![image](https://user-images.githubusercontent.com/16647003/85846853-6080f000-b79e-11ea-9117-7d4a53418fca.png)

7. Save edits
8. Click cards tab - New branch nodes appear on card.

![image](https://user-images.githubusercontent.com/16647003/85846934-87d7bd00-b79e-11ea-873a-91289beb4138.png)

9. Quit Designer
10. Open branch again
11. The root node Type appears in the graph and card but not the child node

![image](https://user-images.githubusercontent.com/16647003/85847056-b9e91f00-b79e-11ea-94ee-3a3a3d4bd6d5.png)

![image](https://user-images.githubusercontent.com/16647003/85847113-cec5b280-b79e-11ea-98b1-5770fd9919fa.png)

This change in functionality has happened following recent update from archesproject: master.

It appears that some changes to the card designer have taken place and these changes may or may not be related to this issue.

The ability to add fully developed branches to each other is essential as otherwise each complex branch has to be built from sctratch.

@Habennin has verified that this bug appears in his instance as well

---

@Habennin commented on [Fri Jun 26 2020](https://github.com/archesproject/arches-her/issues/516#issuecomment-650117226)

Hi all, just verifying that I also experience this behaviour.

**Comment by azaroth42** [comment]
With current master, I get the following exception:

```
Internal Server Error: /node/c4d1d196-c068-11ea-8953-3af9d3b32b71
Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 164, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'parentnodegroup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/views/graph.py", line 335, in post
    graph.save()
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/models/graph.py", line 403, in save
    cache.set(f"graph_{self.graphid}", JSONSerializer().serializeToPython(self), settings.GRAPH_MODEL_CACHE_TIMEOUT)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/utils/betterJSONSerializer.py", line 52, in serializeToPython
    return self.handle_object(obj, self.selected_fields, self.exclude)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/utils/betterJSONSerializer.py", line 86, in handle_object
    return self.handle_object(getattr(object, "serialize")(fields, exclude), fields, exclude)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/models/graph.py", line 1237, in serialize
    ret["cards"] = self.get_cards() if "cards" not in exclude else ret.pop("cards", None)
  File "/Users/rsanderson/Development/getty/arches/current/arches/arches/app/models/graph.py", line 1191, in get_cards
    if card.nodegroup.parentnodegroup is None:
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
    rel_obj = self.get_object(instance)
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 145, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/Users/rsanderson/Development/getty/arches/current/ENV/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
arches.app.models.models.NodeGroup.DoesNotExist: NodeGroup matching query does not exist.
[07/Jul/2020 10:45:44] "POST /node/c4d1d196-c068-11ea-8953-3af9d3b32b71 HTTP/1.1" 500 27922
```

When trying to save the card at step 7.

**Comment by azaroth42** [comment]
Sometimes this gets back to the browser, where it then gets this exception:

```
card-tree.js?_dc=5.0:449 Uncaught TypeError: Cannot read property 'parentnodegroup_id' of undefined
    at card-tree.js?_dc=5.0:449
    at underscore-min.js?_dc=5.0:5
    at Function.h.find.h.detect (underscore-min.js?_dc=5.0:5)
    at card-tree.js?_dc=5.0:448
    at Array.forEach (<anonymous>)
    at a.gc.kc (card-tree.js?_dc=5.0:444)
    at Function.notifySubscribers (knockout-latest.js?_dc=5.0:38)
    at Function.wa (knockout-latest.js?_dc=5.0:43)
    at c (knockout-latest.js?_dc=5.0:42)
    at constructor.<anonymous> (graph.js?_dc=5.0:186)
```

And occassionally it actually works.  I expect it's a graph caching issue.

**Comment by azaroth42** [comment]
This package has the ontology and branches that do not work consistently for me:

[test_package.zip](https://github.com/archesproject/arches/files/4886006/test_package.zip)

In particular, try and create a branch with root class of E22, and then import Activity Template.

**Comment by ryan86** [comment]
I've recreated the activity template branch with the latest version of Arches and I do not see this issue. @azaroth42 can you try testing with the attached branch and see if it works correctly for you? One note, once you turn off 'Place nodes in separate card' you will be unable to turn it back on again - you'll see an error that the top node in the branch needs to be a collector.


[activity_new.json.zip](https://github.com/archesproject/arches/files/4893410/activity_new.json.zip)

**Comment by azaroth42** [comment]
Cannot reproduce in current master.

**Comment by chiatt** [comment]
@Philbox Could you pull from master and confirm that this is still a problem?

**Comment by Philbox** [comment]
I’ll give it a whirl over the weekend.

Phil

[Historic England Logo]<http://www.historicengland.org.uk/>


We are the public body that helps people care for, enjoy and celebrate England's spectacular historic environment, from beaches and battlefields to parks and pie shops.
Follow us:  Facebook<https://www.facebook.com/HistoricEngland>  |  Twitter<https://twitter.com/HistoricEngland>  |  Instagram<https://www.instagram.com/historicengland/>     Sign up to our newsletter<http://webmail.historicenglandservices.org.uk/k/Historic-England/historic_england_preference_centre>


This e-mail (and any attachments) is confidential and may contain personal views which are not the views of Historic England unless specifically stated. If you have received it in error, please delete it from your system and notify the sender immediately. Do not use, copy or disclose the information in any way nor act in reliance on it. Any information sent to Historic England may become publicly available. We respect your privacy and the use of your information. Please read our full privacy policy<https://www.historicengland.org.uk/terms/privacy-cookies/> for more information.

________________________________

**Comment by chiatt** [comment]
Hey @Philbox - did you get a chance to look into this?

**Comment by Philbox** [comment]
Hi Cyrus,
Yes, sorry the pull from master fixed this.

Phil

[Historic England Logo]<http://www.historicengland.org.uk/>


We are the public body that helps people care for, enjoy and celebrate England's spectacular historic environment, from beaches and battlefields to parks and pie shops.
Follow us:  Facebook<https://www.facebook.com/HistoricEngland>  |  Twitter<https://twitter.com/HistoricEngland>  |  Instagram<https://www.instagram.com/historicengland/>     Sign up to our newsletter<http://webmail.historicenglandservices.org.uk/k/Historic-England/historic_england_preference_centre>


This e-mail (and any attachments) is confidential and may contain personal views which are not the views of Historic England unless specifically stated. If you have received it in error, please delete it from your system and notify the sender immediately. Do not use, copy or disclose the information in any way nor act in reliance on it. Any information sent to Historic England may become publicly available. We respect your privacy and the use of your information. Please read our full privacy policy<https://www.historicengland.org.uk/terms/privacy-cookies/> for more information.

________________________________

**Comment by chiatt** [comment]
@Philbox - Great. Thanks for checking!
