### ISSUE TITLE
Error when searching for dates with advanced search

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6492]
When searching on dates in advanced search the following py error occurs:
```
Traceback (most recent call last):
  File "/Users/cyrus/Documents/projects/GCI/arches4/arches/arches/app/search/search.py", line 134, in search
    ret = self.es.search(**kwargs)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1623, in search
    body=body,
  File "/Users/cyrus/Documents/projects/GCI/arches4/env/lib/python3.7/site-packages/elasticsearch/transport.py", line 362, in perform_request
    timeout=timeout,
  File "/Users/cyrus/Documents/projects/GCI/arches4/env/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 282, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', "failed to parse date field [2020-08-04T00:00:00] with format [-yyyy||yyyy||yyyy-MM||yyyy-MM-dd||yyyy-MM-dd HH:mm:ssZZZZZ||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZZZZ||yyyy-MM-dd'T'HH:mm:ss.SSSZ||yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ]: [failed to parse date field [2020-08-04T00:00:00] with format [-yyyy||yyyy||yyyy-MM||yyyy-MM-dd||yyyy-MM-dd HH:mm:ssZZZZZ||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZZZZ||yyyy-MM-dd'T'HH:mm:ss.SSSZ||yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ]]")
Internal Server Error: /search/resources
```
In this particular case the value in the tile and the value in the ES document was `2020-08-04`. For some reason the time is added during search.

**Comment by apeters** [comment]
fixed by #6499
