### ISSUE TITLE
Search export fails if a tile has a geojson node with no value and a non-geojson node with a value

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#7013]
The following error is produced:

```
Internal Server Error: /search/export_results
Traceback (most recent call last):
  File "/Users/cyrus/Documents/projects/GCI/arches4/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cyrus/Documents/projects/GCI/arches4/arches/arches/app/views/search.py", line 217, in export_results
    export_files, export_info = exporter.export(format)
  File "/Users/cyrus/Documents/projects/GCI/arches4/arches/arches/app/search/search_export.py", line 68, in export
    resource_obj = self.flatten_tiles(
  File "/Users/cyrus/Documents/projects/GCI/arches4/arches/arches/app/search/search_export.py", line 183, in flatten_tiles
    feature_collections = self.get_feature_collections(tile, node, feature_collections, label, datatype)
  File "/Users/cyrus/Documents/projects/GCI/arches4/arches/arches/app/search/search_export.py", line 134, in get_feature_collections
    for feature_index, feature in enumerate(node_value["features"]):
TypeError: 'NoneType' object is not subscriptable
```

**Comment by chiatt** [comment]
Resolved in #7014
