### ISSUE TITLE
Resource model error when user object unavailable

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#7269]
Occurs when 'load_tiles' is called without a user:
```
Internal Server Error: /activeconsultations
Traceback (most recent call last):
...
  File "/Users/cyrus/Documents/projects/GCI/arches4/projects/arches-her/arches_her/views/active_consultations.py", line 80, in get
    grouped_tile_list = build_resource_dict(filtered_consultations, self.active_cons_node_list, datatype_factory, keyword=keyword)
  File "/Users/cyrus/Documents/projects/GCI/arches4/projects/arches-her/arches_her/views/active_consultations.py", line 171, in build_resource_dict
    consultation.load_tiles()
  File "/Users/cyrus/Documents/projects/GCI/arches4/arches/arches/app/models/resource.py", line 162, in load_tiles
    self.tiles = [tile for tile in self.tiles if tile.nodegroup_id is not None and user.has_perm(perm, tile.nodegroup)]
  File "/Users/cyrus/Documents/projects/GCI/arches4/arches/arches/app/models/resource.py", line 162, in <listcomp>
    self.tiles = [tile for tile in self.tiles if tile.nodegroup_id is not None and user.has_perm(perm, tile.nodegroup)]
AttributeError: 'NoneType' object has no attribute 'has_perm'
```

**Comment by chiatt** [comment]
Resolved in #7272
