### ISSUE TITLE
Bug: CRM-compliant graph allowed to save edge w/o property

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#831]
#### Expected Behavior

If the graph is set as CRM-compliant, then it should prevent a save of an edge that doesnt have a property.
#### Current Behavior

When I create a node within a graph that is set to have CRM compatibility, the sw allows me to define a the relationship to the parent w/o specifying a property.  Resulting saved data results in an edge record in the db where the ontologyproperty value is null.
#### Steps to Reproduce (for bugs)

1.  Create a new graph (not resource) and set the ontology to CRM
2.  Add a child node to the initial parent
3.  As you attribute the child, set the "Relationship from [parent node]" to "Choose a property"
4. Save the graph

**Comment by adamlodge** [comment]
@apeters the fix works.  An error message prevents save when this condition exists.  However, the message is non-descript.  It just says contact a system admin.  Any chance the message could say that there is an invalid property based on the graph's ontology?

**Comment by ryan86** [comment]
I believe this change breaks import of the Arches System Settings graph.


`  File "/Users/ryan/Projects/archesv4/arches/app/models/graph.py", line 1100, in validate
    raise ValidationError(_("You must specify an ontology property. Your graph isn't semantically valid. Entity domain '{0}' and Entity range '{1}' can not be related via Property '{2}'.").format(edge.domainnode.ontologyclass, edge.rangenode.ontologyclass, edge.ontologyproperty))
ValidationError: u"You must specify an ontology property. Your graph isn't semantically valid. Entity domain 'E13_Attribute_Assignment' and Entity range 'E13_Attribute_Assignment' can not be related via Property 'None'."`

**Comment by dwuthrich** [comment]
I'm getting a similar error when trying to save configuration on a Map Layer Manager layer:  

ERROR:django.request:Internal Server Error: /node/fad0563b-b8f8-11e6-84a5-026d961c88e6
Traceback (most recent call last):
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/dwuthrich/arches/arches4/virtualenv/ENV/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches4/arches/app/views/graph.py", line 248, in post
    graph.save()
  File "/Users/dwuthrich/arches/arches4/arches/app/models/graph.py", line 301, in save
    self.validate()
  File "/Users/dwuthrich/arches/arches4/arches/app/models/graph.py", line 1100, in validate
    raise ValidationError(_("You must specify an ontology property. Your graph isn't semantically valid. Entity domain '{0}' and Entity range '{1}' can not be related via Property '{2}'.").format(edge.domainnode.ontologyclass, edge.rangenode.ontologyclass, edge.ontologyproperty))
ValidationError: u"You must specify an ontology property. Your graph isn't semantically valid. Entity domain 'E53_Place' and Entity range 'E47_Spatial_Coordinates' can not be related via Property 'None'."

But all the E53/E47 nodes have valid properties.  This does look like an improper implementation of ontology validation

**Comment by apeters** [comment]
@ryan86, The Arches System Setting graph has 10 `null` ontology properties which need to be specified.   This should fix the graph which is currently invalid.

Search for ("ontologyproperty": null) to find all 10 edges.

**Comment by apeters** [comment]
@adamlodge I noticed this too and I totally agree with you about the lack of a decent error message.  We've done this in other places.  I'll see if we can do this easily here too.

**Comment by apeters** [comment]
@dwuthrich, this should be fixed in the latest

**Comment by adamlodge** [comment]
meets requirement
