### ISSUE TITLE
running manage.py packages create_mapping_file in cmd returns errors

### ISSUE THREAD

**Issue by jakub-gorka** [archesproject/arches#8310]
**Describe the bug**

When trying to export mapping files for selected branch in commandline:
`python manage.py packages -o create_mapping_file -d /mnt/arches/dragonfly/dragonfly_data/ -g c2a485b8-a927-11ec-a393-c94be70a832e`
I recieve error:
`operation: create_mapping_file
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/mnt/arches/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/arches/management/commands/packages.py", line 337, in handle
    self.create_mapping_file(options["dest_dir"], options["graphs"])
  File "/mnt/arches/ENV/lib/python3.8/site-packages/arches/management/commands/packages.py", line 1302, in create_mapping_file
    graph_exporter.create_mapping_configuration_file(graphs, include_concepts, dest_dir)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/arches/app/utils/data_management/resource_graphs/exporter.py", line 260, in create_mapping_configuration_file
    with open(os.path.join(data_dir), "w") as config_file:
IsADirectoryError: [Errno 21] Is a directory: '/mnt/arches/dragonfly/dragonfly_data/'
`

**To Reproduce**
1. Activate VENV
2. Cd into folder with manage.py
3. Enter and run command `python manage.py packages -o create_mapping_file -d <folder to export data to> -g <graph_uuid>`

**Expected behavior**
Mapping file and .json file should be generated, zipped and saved in -d directory

**Your Arches Information**

*   Version used: 6.0.1
*   Operating System and version (desktop or mobile): Ubuntu 20.04 LTS
*   Browser Name and version: not applicable
*   Link to your Arches Install (optional): not applicable

**Additional context**
After fixing this issue another error occured:

`operation: create_mapping_file
/mnt/arches/dragonfly/dragonfly_data/
Traceback (most recent call last):
  File "/mnt/arches/ENV/lib/python3.8/site-packages/arches/app/utils/data_management/resource_graphs/exporter.py", line 269, in create_mapping_configuration_file
    zip.writestr(f["name"], f["outputfile"].read())
  File "/usr/lib/python3.8/zipfile.py", line 1816, in writestr
    with self.open(zinfo, mode='w') as dest:
  File "/usr/lib/python3.8/zipfile.py", line 1517, in open
    return self._open_to_write(zinfo, force_zip64=force_zip64)
  File "/usr/lib/python3.8/zipfile.py", line 1614, in _open_to_write
    self.fp.write(zinfo.FileHeader(zip64))
TypeError: string argument expected, got 'bytes'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/mnt/arches/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/arches/management/commands/packages.py", line 337, in handle
    self.create_mapping_file(options["dest_dir"], options["graphs"])
  File "/mnt/arches/ENV/lib/python3.8/site-packages/arches/management/commands/packages.py", line 1302, in create_mapping_file
    graph_exporter.create_mapping_configuration_file(graphs, include_concepts, dest_dir)
  File "/mnt/arches/ENV/lib/python3.8/site-packages/arches/app/utils/data_management/resource_graphs/exporter.py", line 269, in create_mapping_configuration_file
    zip.writestr(f["name"], f["outputfile"].read())
  File "/usr/lib/python3.8/zipfile.py", line 1312, in __exit__
    self.close()
  File "/usr/lib/python3.8/zipfile.py", line 1839, in close
    self._write_end_record()
  File "/usr/lib/python3.8/zipfile.py", line 1943, in _write_end_record
    self.fp.write(endrec)
TypeError: string argument expected, got 'bytes'
`
The "python manage.py packages -o create_mapping_file" still doesn't work with multiple graph id's and "all" keyword

**My fix:**
![image](https://user-images.githubusercontent.com/97510041/160858878-5a91c719-75b5-4a99-b641-b2310cb04647.png)

**Comment by chiatt** [comment]
Resolved in #8315
