### ISSUE TITLE
elasticsearch queries fail if "source_includes" is not included in the request

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8708]
To reproduce:

- Load arches-HER v7
- navigate to the graph designer
- navigate to the application area resource model
- navigate to the cards tab, then the `descriptions` card
- notice the error
```
Internal Server Error: /concepts/get_pref_label
Traceback (most recent call last):
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cbyrd/Projects/arches/arches/app/views/concept.py", line 439, in get_pref_label
    label = get_preflabel_from_valueid(valueid, request.LANGUAGE_CODE)
  File "/Users/cbyrd/Projects/arches/arches/app/models/concept.py", line 1450, in get_preflabel_from_valueid
    concept_label = se.search(index=CONCEPTS_INDEX, id=valueid)
  File "/Users/cbyrd/Projects/arches/arches/app/search/search.py", line 133, in search
    "source_includes": kwargs["source_includes"],
KeyError: 'source_includes'
```

**Comment by chrabyrd** [comment]
fix in #8709
