### ISSUE TITLE
Arches Designer `Create Mapping File` interaction fails with JSON error in v7 with some Resource Models

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8723]
**Describe the bug**

Stacktrace: 
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/graph/b9e0701e-5463-11e9-b5f5-000d3ab1e588/export_mapping_file

Django Version: 3.2.14
Python Version: 3.8.6
Installed Applications:
('webpack_loader',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.gis',
 'arches',
 'arches.app.models',
 'arches.management',
 'guardian',
 'captcha',
 'revproxy',
 'corsheaders',
 'oauth2_provider',
 'django_celery_results',
 'compressor')
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'arches.app.utils.middleware.ModifyAuthorizationHeader',
 'oauth2_provider.middleware.OAuth2TokenMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'arches.app.utils.middleware.SetAnonymousUser']



Traceback (most recent call last):
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/cbyrd/Projects/arches/arches/app/views/graph.py", line 282, in get
    files_for_export = create_mapping_configuration_file(graphid, True)
  File "/Users/cbyrd/Projects/arches/arches/app/utils/data_management/resource_graphs/exporter.py", line 261, in create_mapping_configuration_file
    dest.write(json.dumps(values, indent=4))
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

Exception Type: TypeError at /graph/b9e0701e-5463-11e9-b5f5-000d3ab1e588/export_mapping_file
Exception Value: Object of type dict_items is not JSON serializable


```

**To Reproduce**
1. Ensure you're on core branch `8090-cbyrd-adds-frontend-compiler` + arches-HER branch `update_project_for_webpack_v7`
2. Ensure the application has been successfully webpacked
3. navigate to the graph designer
4. attempt to select the `Create Mapping File` option from the `Manage` dropdown for the `Activity` Resource Model
5. See it fail with above error
6. attempt to select the `Create Mapping File` option from the `Manage` dropdown for the `Application Area` Resource Model
7. See it succeed

**Comment by chrabyrd** [comment]
resolved in #8785
