### ISSUE TITLE
`Clone Model` interaction in Arches Designer fails with error

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8724]
**Describe the bug**

Stacktrace: 
```
[01/Aug/2022 12:12:55] "POST /graph/22477f01-1a44-11e9-b0a9-000d3ab1e588/clone HTTP/1.1" 500 132728
Internal Server Error: /graph/42ce82f6-83bf-11ea-b1e8-f875a44e0e11/clone
Traceback (most recent call last):
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/cbyrd/Projects/arches/arches/app/views/graph.py", line 392, in post
    clone_data = graph.copy()
  File "/Users/cbyrd/Projects/arches/arches/app/models/graph.py", line 819, in copy
    widget.node_id = node_map[widget.node_id]
KeyError: '0a5e6b91-860d-11ea-aa4f-f875a44e0e11'
```

**To Reproduce**
1. Ensure you're on core branch `8090-cbyrd-adds-frontend-compiler` + arches-HER branch `update_project_for_webpack_v7`
2. Ensure the application has been successfully webpacked
3. navigate to the graph designer
4. Attempt to clone any Resource Model
5. Notice the interaction fails with above error

**Comment by chrabyrd** [comment]
resolved in #8874
