### ISSUE TITLE
`Delete Model` interaction in Arches Designer fails for some Resource Models in v7

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8725]
**Describe the bug**

Stacktrace:
```
[01/Aug/2022 12:13:17] "POST /graph/42ce82f6-83bf-11ea-b1e8-f875a44e0e11/clone HTTP/1.1" 500 134256
Internal Server Error: /graph/78b32d8c-b6f2-11ea-af42-f875a44e0e11/delete
Traceback (most recent call last):
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/cbyrd/Projects/arches/arches/app/views/graph.py", line 459, in delete
    graph.delete()
  File "/Users/cbyrd/Projects/arches/arches/app/models/graph.py", line 508, in delete
    nodegroup.delete()
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
    return collector.delete()
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/django/db/models/deletion.py", line 382, in delete
    self.data[model] = sorted(instances, key=attrgetter("pk"))
TypeError: '<' not supported between instances of 'str' and 'UUID'
```

**To Reproduce**
1. Ensure you're on core branch `8090-cbyrd-adds-frontend-compiler` + arches-HER branch `update_project_for_webpack_v7`
2. Ensure the application has been successfully webpacked
3. navigate to the graph designer
4. Attempt to delete the `Place` Resource model
5. Watch the interaction fail
6. Attempt to delete the `Person` Resource model
7. Watch the interaction succeed

NOTE: THIS APPEARS TO BE REQUEST-DEPENDANT! The first `DELETE` request seems to fail regardless of model, the second `DELETE` requests seems to succeed regardless of model!

**Comment by chrabyrd** [comment]
resolved in #8822
