### ISSUE TITLE
Attempting to order search results with either `Ascending` or `Descending` values results in error

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8775]
**Describe the bug**

Attempting to order search results with either `Ascending` or `Descending` values results in error

**To Reproduce**
1. arches-HER webpack branch, arches-core webpack branch
2. ensure you have enough search results to order
3. attempt to order the search results via dropdown
4. notice the error flash

stacktrace:
```
2022-08-08 11:38:54,789 arches.app.search.search ERROR    2022-08-08 11:38:54.788977: WARNING: search failed for query: {'bool': {'should': [], 'must': [], 'must_not': [], 'filter': [{'terms': {'graph_id': ['118feab4-025c-11eb-b7e6-f875a44e0e11', 'a7bde770-992f-11ea-929a-f875a44e0e11', '8fd40cd0-993a-11ea-a3b9-f875a44e0e11', '62c8f462-1809-11e9-8552-000d3ab1e588', '12c12770-f0f0-11ea-834d-f875a44e0e11', 'f4b26223-fad7-11e6-957d-6c4008b05c4c', '8f6b220a-3e8f-11ea-ae87-c4d9877d154e', 'a3570880-9b5c-11ea-af46-f875a44e0e11', 'b8903248-734c-11ea-8881-287fcf6a5e72', '4f565430-fad7-11e6-9950-6c4008b05c4c', '8d41e49e-a250-11e9-9eab-00224800b26d', 'dea0a412-2999-11eb-92fe-f875a44e0e11', '74388066-3a38-11eb-a5bf-f875a44e0e11', 'ec89d5f0-9923-11ea-9ddc-f875a44e0e11', '4a6c95f0-1298-11e9-ba52-000d3ab1e588', '19f87c07-03d5-11eb-b20f-f875a44e0e11', '2c478fc0-12dc-11eb-9ce9-f875a44e0e11', 'aadccd7a-fac0-11e6-800a-6c4008b05c4c', '5dc5de2c-8554-11ea-b812-f875a44e0e11', 'f9045867-8861-11ea-b06f-f875a44e0e11', 'c3cea108-9b68-11ea-85fa-f875a44e0e11', '24d7b54f-5464-11e9-a86b-000d3ab1e588', '00231834-51c1-11eb-84cf-f875a44e0e11', '1852df01-5782-11e9-9696-18cf5eb368c4', 'c80d7a6e-f447-11eb-8c61-a87eeabdefba', '343cc20c-2c5a-11e8-90fa-0242ac120005', '37c2a230-5539-11e9-89ef-000d3ab1e588', '1a00ebb4-992e-11ea-9af5-f875a44e0e11', '5d720c36-efa6-11eb-b713-a87eeabdefba', 'db618aac-993a-11ea-9bde-f875a44e0e11', 'b07cfa6f-894d-11ea-82aa-f875a44e0e11', '6719b83e-a0e8-11ea-8173-f875a44e0e11', '5a50d3fa-9930-11ea-b7b2-f875a44e0e11', 'beabc9b0-59db-11e9-bad6-18cf5eb368c4', 'c0bb4150-5aa2-11e9-9aa3-000d3ab1e588', 'fb1484f6-992e-11ea-9d18-f875a44e0e11', 'e90c0ff6-992e-11ea-ace2-f875a44e0e11', '9f363a6e-04c6-11eb-8274-f875a44e0e11', 'f68b49ee-3a39-11eb-99ac-f875a44e0e11', 'e8036dc7-8482-11ea-bbe5-f875a44e0e11', 'b8032b00-594d-11e9-9cf0-18cf5eb368c4', '62df6eec-efd9-11eb-be91-a87eeabdefba', '80af9af4-51ab-11eb-b3f9-f875a44e0e11', '7cfb164a-894f-11ea-bbcf-f875a44e0e11', 'a535a235-8481-11ea-a6b9-f875a44e0e11', 'ff623370-fa12-11e6-b98b-6c4008b05c4c', '6da66130-59d4-11e9-8ff9-18cf5eb368c4', '24398081-4a53-11e9-a929-000d3ab1e588', '2350e86e-9aa7-11ea-9e8f-f875a44e0e11', '42ce82f6-83bf-11ea-b1e8-f875a44e0e11', 'b6f174f5-fa13-11e6-9116-6c4008b05c4c', 'ef38c17e-9924-11ea-a5ee-f875a44e0e11', '5aabb9b1-661d-11e7-b43c-021893e306d8', 'c3cb4d26-19bc-11eb-aee7-f875a44e0e11', 'e5550180-59ef-11e9-9ce4-18cf5eb368c4', 'b1d2b794-f446-11eb-9eee-a87eeabdefba', '78b32d8c-b6f2-11ea-af42-f875a44e0e11', 'd4a88461-5463-11e9-90d9-000d3ab1e588', 'f1ff5f90-29ba-11eb-adb1-f875a44e0e11', '58eb83b0-3b98-11eb-aa2f-f875a44e0e11', '49bac32e-5464-11e9-a6e2-000d3ab1e588', '22477f01-1a44-11e9-b0a9-000d3ab1e588', 'b53d88cf-5780-11e9-86b6-18cf5eb368c4', '979aaf0b-7042-11ea-9674-287fcf6a5e72', 'c8e413a6-025b-11eb-9a3a-f875a44e0e11', '5211c471-59f0-11e9-a975-18cf5eb368c4', '251551d8-7fe7-11ea-bcad-f875a44e0e11', '80117d70-5aae-11e9-b76d-000d3ab1e588', '5dedc7c0-993a-11ea-bc4e-f875a44e0e11', '74195ea4-9930-11ea-8d78-f875a44e0e11', '048cf280-9924-11ea-a9c7-f875a44e0e11', '37ad98ae-7021-11ea-973c-287fcf6a5e72', 'e48c1806-025b-11eb-9d63-f875a44e0e11', '076f9381-7b00-11e9-8d6b-80000b44d1d9', 'bf1d2148-28bd-11eb-b0b8-f875a44e0e11', '9247f478-992e-11ea-9c2f-f875a44e0e11', 'ae71416c-025b-11eb-9eec-f875a44e0e11', '7b2a44a6-28ee-11eb-a379-f875a44e0e11', '8aeb4e58-1b46-11ea-89a5-c4d9877d154e', '934cd7f0-480a-11ea-9240-c4d9877d154e', 'b9e0701e-5463-11e9-b5f5-000d3ab1e588', '1f29ee7a-025c-11eb-89d0-f875a44e0e11', 'bbd0d023-955d-11e6-b664-024f9e178154', 'e1851264-afcf-11ea-b2e2-f875a44e0e11', 'fc0a29e8-28c3-11eb-a8cf-f875a44e0e11', '7541f73e-839c-11ea-b880-f875a44e0e11', '45882188-06f7-11eb-8601-f875a44e0e11', '3e46d01e-efd9-11eb-be69-a87eeabdefba', 'ef0b811b-fe43-11ea-bd91-f875a44e0e11', '7e987d1c-992d-11ea-8117-f875a44e0e11', '77994b9e-51ad-11eb-96de-f875a44e0e11', '3ef7295a-9b69-11ea-a303-f875a44e0e11', 'd8fd2b0f-fad8-11e6-8ebc-6c4008b05c4c', '0add0e11-99aa-11ea-9ab8-f875a44e0e11', 'f313164c-992f-11ea-a67e-f875a44e0e11', '52a4a16e-9931-11ea-81cd-f875a44e0e11', 'ab806134-1838-11ea-95a5-c4d9877d154e', '03685224-eebc-11eb-b661-a87eeabdefba']}}]}} 
Exception detail: BadRequestError(400, 'search_phase_execution_exception', 'No mapping found for [displayname] in order to sort on')
Traceback (most recent call last):
  File "/Users/cbyrd/Projects/arches/arches/app/search/search.py", line 149, in search
    ret = self.es.search(**kwargs).body
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 3752, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/Users/cbyrd/Projects/ENV/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 321, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'search_phase_execution_exception', 'No mapping found for [displayname] in order to sort on')
Internal Server Error: /search/resources
```

**Screenshots**

<img width="1409" alt="Screen Shot 2022-08-08 at 9 42 54 AM" src="https://user-images.githubusercontent.com/9162695/183469611-fc8dbaa1-5d39-4647-a758-893b00ffc2c5.png">

**Comment by chiatt** [comment]
Fixed in #8820
