### ISSUE TITLE
Default project template sample-widget.json cause package export to fail

### ISSUE THREAD

**Issue by jlayt** [archesproject/arches#9137]
Running the create_package and update_package commands fail when the default my-project/widget/sample-widget.json example file still exists. Removing this file allows the package export to complete.

```
operation: update_package
Updating Widgets
Traceback (most recent call last):
  File "/srv/www/lib/fasti/fasti_arches/project/manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/www/lib/fasti/fasti_arches/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/srv/www/lib/fasti/fasti_arches/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/www/lib/fasti/fasti_arches/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/www/lib/fasti/fasti_arches/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/srv/www/lib/fasti/fasti_arches/.venv/lib/python3.9/site-packages/arches/management/commands/packages.py", line 362, in handle
    self.update_package(options["dest_dir"], options["yes"])
  File "/srv/www/lib/fasti/fasti_arches/.venv/lib/python3.9/site-packages/arches/management/commands/packages.py", line 470, in update_package
    self.export_widgets(os.path.join(dest_dir, "extensions", "widgets"))
  File "/srv/www/lib/fasti/fasti_arches/.venv/lib/python3.9/site-packages/arches/management/commands/packages.py", line 460, in export_widgets
    widget_instance = models.Widget.objects.get(name=details["name"])
  File "/srv/www/lib/fasti/fasti_arches/.venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/www/lib/fasti/fasti_arches/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
arches.app.models.models.DoesNotExist: Widget matching query does not exist.
```

Issue was identified by @mradamcox @chiatt in thread https://community.archesproject.org/t/package-error-widget-matching-query-does-not-exist/1439. Proposed workaround was to not install examples by default. Root cause fix would be to find why export is reading local config files.

**Comment by ydrea** [comment]
same here!
```
Updating Widgets
Traceback (most recent call last):
  File "/home/archesadmin/suhozid/manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/archesadmin/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/archesadmin/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/archesadmin/env/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/archesadmin/env/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/archesadmin/arches/arches/management/commands/packages.py", line 353, in handle
    self.update_package(options["dest_dir"], options["yes"])
  File "/home/archesadmin/arches/arches/management/commands/packages.py", line 464, in update_package
    self.export_widgets(os.path.join(dest_dir, "extensions", "widgets"))
  File "/home/archesadmin/arches/arches/management/commands/packages.py", line 454, in export_widgets
    widget_instance = models.Widget.objects.get(name=details["name"])
  File "/home/archesadmin/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/archesadmin/env/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
arches.app.models.models.Widget.DoesNotExist: Widget matching query does not exist.
```
