### ISSUE TITLE
BUG in  "arches-project create arches_proj" (stable/7.2.1)

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#9157]
I'm working on a Dockerized deployment for Arches (including Nginx and Lets Encrypt for HTTPS). I'm running into a problem with the `arches-project create` command.

Here's the part of my Dockerfile that's the issue:
`
RUN pip install arches

RUN arches-project create ${ARCHES_PROJECT} 
`

The `pip install arches` seems to work fine (OS is Ubuntu 20.04). However the `RUN arches-project create ${ARCHES_PROJECT}` (where `ARCHES_PROJECT` is cleverly set to `arches_proj`) gives me a failure as below:

`
 > [arches 12/20] RUN arches-project create arches_proj:
#0 0.590 /usr/local/bin/arches-project:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
#0 0.590   import imp
#0 0.603 Traceback (most recent call last):
#0 0.603   File "/usr/local/bin/arches-project", line 161, in <module>
#0 0.603     main()
#0 0.603   File "/usr/local/bin/arches-project", line 154, in main
#0 0.603     COMMANDS[args.command](args)
#0 0.603   File "/usr/local/bin/arches-project", line 70, in command_create_app
#0 0.603     cmd.handle(options)
#0 0.603   File "/usr/local/bin/arches-project", line 36, in handle
#0 0.603     self.validate_name(project_name, "project")
#0 0.603   File "/usr/local/lib/python3.9/dist-packages/django/core/management/templates.py", line 238, in validate_name
#0 0.603     an=self.a_or_an,
#0 0.603 AttributeError: 'ArchesCommand' object has no attribute 'a_or_an'
`

**Comment by ekansa** [comment]
Cancel this. I happened to be creating the project in a directory that already exists

**Comment by chiatt** [comment]
Ok - thanks @ekansa
