### ISSUE TITLE
The grouping card appears broken in 7.x

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#9159]
**Arches Version/Branch:** v7.x

**Describe the bug and how to reproduce it:**
There are several issues with the grouping card.
1. The placeholder string appears to reference the incorrect translation value
2. When selecting the grouping card, it can sometimes throw various errors in the console related to undefined values
3. When selecting the grouping card and it doesn't throw an error, and a user selects a card to group, the tree updates but the main data entry form doesn't.

All of those scenarios are visible when using the Digital Object model in AFS.

**Comment by jlayt** [comment]
Confirmed still present in 7.3.

Here's what the screen looks like when switching to Grouping Card.

![Screenshot 2022-12-13 at 09 34 57](https://user-images.githubusercontent.com/3813093/216311437-9d773139-127d-42b3-80b1-f3fd95d4fcce.jpg)

The error logged in the console is

```
knockout-latest.js:20 Uncaught TypeError: Cannot read properties of undefined (reading 'model')
    at viewModel.eval (grouping.js:53:33)
    at eval (underscore-min.js:6:6193)
    at Function.jr (underscore-min.js:6:9523)
    at viewModel.eval (grouping.js:51:18)
    at Function.xd (knockout-latest.js:59:369)
    at Function.yd (knockout-latest.js:59:66)
    at Function.ha (knockout-latest.js:58:406)
    at a.o.a.$ (knockout-latest.js:56:165)
    at new viewModel (grouping.js:50:28)
    at Object.eval [as createViewModel] (knockout-latest.js:92:380)
```

**Comment by chiatt** [comment]
There was a fix to the grouping card in 6.2 that didn't make it into 7.0. I'm not sure if it addresses the issue that @jlayt is seeing. I'll try to test it tomorrow. https://github.com/archesproject/arches/pull/9230/commits/9b38cb121939f891a40d79bdf24e28db7218978e

**Comment by chiatt** [comment]
Unfortunately https://github.com/archesproject/arches/commit/9b38cb121939f891a40d79bdf24e28db7218978e doesn't seem to solve this particular issue. It appears that a user can set one card on a resource model to be a grouping card. I've managed to do that on several models without an issue. The error occurs when the grouping.js file is loaded for a second card. When this happens, the params ('groupedCardIds' and 'sortedWidgetIds') come in as nested observables - observables of observables and this causes an error. This can be seen by watching this value: `params.card.model.attributes.config.groupedCardIds()`

**Comment by chiatt** [comment]
Fixed in #9276
