### ISSUE TITLE
Resource instance permissions panel fails to open

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9186]
When a user tries to open the 'Manage Permissions' link in the resource editor on a new resource instance nothing happens (the resource instance panel should open up). If the user refreshes the page, then the link works. However, once the link works, if the user clicks 'Configure Access to This Instance', nothing seems to happen. On the backend however the following error occurs:
```
Internal Server Error: /resource/permissions
Traceback (most recent call last):
...
psycopg2.errors.NotNullViolation: null value in column "createdtime" of relation "resource_instances" violates not-null constraint
DETAIL:  Failing row contains (dcc079b7-281d-4793-9768-cc9feab4a8b0, null, e9e7289f-d45c-4c8b-8e8c-7ef48977fbde, null, {"en": {"name": null, "map_popup": null, "description": null}}, {"en": null}, e1b07f8a-9769-11ed-aed5-a683e74f6c3a).

The above exception was the direct cause of the following exception:
...
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/arches/arches/app/views/resource.py", line 403, in post
    result = self.make_instance_private(resourceid, graphid)
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/arches/arches/app/views/resource.py", line 468, in make_instance_private
    resource.add_permission_to_all("no_access_to_resourceinstance")
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/arches/arches/app/models/resource.py", line 765, in add_permission_to_all
    self.index()
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/arches/arches/app/models/resource.py", line 280, in index
    super(Resource, self).save()
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/arches/arches/app/models/models.py", line 932, in save
    super(ResourceInstance, self).save()
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/models/base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/cyrus/Documents/projects/GCI/arches4/v72/tempEnvV3/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "createdtime" of relation "resource_instances" violates not-null constraint
DETAIL:  Failing row contains (dcc079b7-281d-4793-9768-cc9feab4a8b0, null, e9e7289f-d45c-4c8b-8e8c-7ef48977fbde, null, {"en": {"name": null, "map_popup": null, "description": null}}, {"en": null}, e1b07f8a-9769-11ed-aed5-a683e74f6c3a).
```

**Comment by chiatt** [comment]
Duplicate of #8907
