### ISSUE TITLE
Resource models fail to clone

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#9196]
The following error occurs when attempting to clone a resource model:

```
Traceback (most recent call last):
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/cyrus/Documents/projects/GCI/arches4/arches/arches/app/views/graph.py", line 400, in post
    ret.save()
  File "/Users/cyrus/Documents/projects/GCI/arches4/arches/arches/app/models/graph.py", line 529, in save
    self._nodegroups_to_delete = []
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
    connection.commit()
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/cyrus/Documents/projects/GCI/arches4/env73/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "nodes" violates foreign key constraint "nodes_nodegroupid_30e98973_fk_node_groups_nodegroupid"
DETAIL:  Key (nodegroupid)=(3a5d19d2-983b-11ed-9ad3-a683e74f6c3a) is not present in table "node_groups".
```

**Comment by bferguso** [comment]
This also happens for Branches. It seems that the clone only fails if the Resource Model/Branch is published. Unpublised graphs appear to clone properly.

Noting this behaviour in dev/7.4.x

**Comment by chrabyrd** [comment]
should be resolved in https://github.com/archesproject/arches/pull/9275 when it gets merged

**Comment by chiatt** [comment]
#9275 is now merged
