### ISSUE TITLE
[REST API] Type Error on /resources/{uuid:resource id} endpoint

### ISSUE THREAD

**Issue by nicospor** [archesproject/arches#9256]
Hi, I'm running a local development Arches 6.2 instance on Ubuntu 22.04 (PostgreSQL 14, Python 3.10.6) using Django's development server.

I was trying to use the REST API endpoints and while the `/resources/` endpoint works correctly, listing URIs for all available resource instances, the `/resources/{uuid:resource id}` endpoint causes a 500 error with this exception:

```
TypeError at /resources/8c21bfdd-6228-4e4d-86e6-08f3ac37525d

argument of type 'NoneType' is not iterable

Request Method: 	GET
Request URL: 	http://localhost:8000/resources/8c21bfdd-6228-4e4d-86e6-08f3ac37525d
Django Version: 	3.2.15
Exception Type: 	TypeError
Exception Value:        argument of type 'NoneType' is not iterable
```

This happens for all individual resource instances, while reports and in general Web views work properly.

Should I add some specific configuration to `settings.py`?

This is the full stacktrace:

```
Environment:

Request Method: GET
Request URL: http://localhost:8000/resources/8c21bfdd-6228-4e4d-86e6-08f3ac37525d

Django Version: 3.2.15
Python Version: 3.10.6
Installed Applications:
('django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.gis',
'arches',
'arches.app.models',
'arches.management',
'guardian',
'captcha',
'revproxy',
'corsheaders',
'oauth2_provider',
'django_celery_results',
'compressor')
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.locale.LocaleMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'arches.app.utils.middleware.ModifyAuthorizationHeader',
'oauth2_provider.middleware.OAuth2TokenMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'arches.app.utils.middleware.SetAnonymousUser']

Traceback (most recent call last):
File "/home/user/arches/ENV/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/home/user/arches/ENV/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/user/arches/ENV/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)
File "/home/user/arches/ENV/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
return bound_method(*args, **kwargs)
File "/home/user/arches/ENV/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/home/user/arches/ENV/lib/python3.10/site-packages/arches/app/views/api.py", line 154, in dispatch
return super(APIBase, self).dispatch(request, *args, **kwargs)
File "/home/user/arches/ENV/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
return handler(request, *args, **kwargs)
File "/home/user/arches/ENV/lib/python3.10/site-packages/arches/app/views/api.py", line 632, in get
output = exporter.writer.write_resources(resourceinstanceids=[resourceid], indent=indent, user=request.user)
File "/home/user/arches/ENV/lib/python3.10/site-packages/arches/app/utils/data_management/resources/formats/rdffile.py", line 269, in write_resources
js = self.build_json(graph_id, resourceinstanceids, **kwargs)
File "/home/user/arches/ENV/lib/python3.10/site-packages/arches/app/utils/data_management/resources/formats/rdffile.py", line 232, in build_json
g = self.get_rdf_graph()
File "/home/user/arches/ENV/lib/python3.10/site-packages/arches/app/utils/data_management/resources/formats/rdffile.py", line 216, in get_rdf_graph
add_edge_to_graph(g, domainnode, rangenode, edge, tile, graph_info)
File "/home/user/arches/ENV/lib/python3.10/site-packages/arches/app/utils/data_management/resources/formats/rdffile.py", line 160, in add_edge_to_graph
graph.add((pkg["d_uri"], RDF.type, URIRef(edge.domainnode.ontologyclass)))
File "/home/user/arches/ENV/lib/python3.10/site-packages/rdflib/term.py", line 223, in new
if not _is_valid_uri(value):
File "/home/user/arches/ENV/lib/python3.10/site-packages/rdflib/term.py", line 76, in _is_valid_uri
if c in uri: return False

Exception Type: TypeError at /resources/8c21bfdd-6228-4e4d-86e6-08f3ac37525d
Exception Value: argument of type 'NoneType' is not iterable
```

**Comment by chiatt** [comment]
Hi @nicospor Which version of 6.2 are you using? I don't see this problem on 6.2.2 (released last Friday).

**Comment by nicospor** [comment]
Thank you @chiatt. I was on 6.2.1, I've upgraded to 6.2.2 after you mentioned the release, but the error is still there.
I can post my `settings.py` or Django's full debug dump, if you think it could be useful.

I should also mention that I have imported the Arches for Science package as part of the project I'm working on.

**Comment by chiatt** [comment]
Thanks @nicospor, that's good to know. I'm using Arches for Science as well. I checked `physical thing` and `person` instances and they worked ok. Could you try requesting the data in standard json format - like this:

`http://localhost:8000/resources/8c21bfdd-6228-4e4d-86e6-08f3ac37525d?format=json&indent=2`

**Comment by nicospor** [comment]
Thank you very much @chiatt, it works with the parameters for standard JSON format. I'm closing the issue.
