### ISSUE TITLE
String can be force entered into resource layer service styling causing ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches#9441]
Issue found on 6.2.2.

In the resource layer service styling user input boxes, found at /map_layer_manager, a user can force input a string which causes an entire Arches instance to crash with the following error:
```
Internal Server Error: /map_layer_manager
Traceback (most recent call last):
  File "/mnt/c/dev/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/mnt/c/dev/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/dev/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/dev/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/mnt/c/dev/env/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/dev/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/c/dev/arches/arches/app/views/map.py", line 50, in get
    context = self.get_context_data(
  File "/mnt/c/dev/arches/arches/app/views/base.py", line 109, in get_context_data
    map_layer = datatype.get_map_layer(node)
  File "/mnt/c/dev/arches/arches/app/datatypes/datatypes.py", line 1207, in get_map_layer
    "expanded_weight": int(node.config["weight"]) * 2,
ValueError: invalid literal for int() with base 10: ''
```

Normally, whenever anything but a number is inputted the input is replaced in two scenarios:
- A letter is inputted after the default number, causing the input to revert to 1
- If default number is deleted it is automatically replaced with 1
However, this can be bypassed by force by highlighting the input and typing any string.

Steps to reproduce:
- See the Line Style "Weight" OR "Halo Weight" input boxes as possibilities: 
![image](https://user-images.githubusercontent.com/119508494/233033578-17b08044-9bf2-401d-8afd-fdb08330b85e.png)
- If save is selected once and the page refreshed the error will occur. If the save is selected for the second time then the error won't occur.

**Comment by chiatt** [comment]
Fixed in #9485
