### ISSUE TITLE
Creating the mapping file through the command line interface does not work

### ISSUE THREAD

**Issue by atapscott** [archesproject/arches#9608]
This happened with the stable branch of Arches 7.3 using a development environment (not the pip package).

The [command provided in the Arches documentation](https://arches.readthedocs.io/en/stable/command-line-reference/#other-data-management-commands) does not work.
To reproduce run the following command **with the env enabled**:
```
python manage.py packages -o create_mapping_file -d [path/to/destination] -g [graph_uuid]

```
The resulting error:
```
operation: create_mapping_file
Traceback (most recent call last):
  File "/home/maphsa/maphsa_arches/manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/maphsa/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/maphsa/ENV/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/maphsa/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/maphsa/ENV/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/maphsa/arches_source/arches/arches/management/commands/packages.py", line 343, in handle
    self.create_mapping_file(options["dest_dir"], options["graphs"])
  File "/home/maphsa/arches_source/arches/arches/management/commands/packages.py", line 1338, in create_mapping_file
    graph_exporter.create_mapping_configuration_file(graphs, include_concepts, dest_dir)
  File "/home/maphsa/arches_source/arches/arches/app/utils/data_management/resource_graphs/exporter.py", line 282, in create_mapping_configuration_file
    with open(os.path.join(data_dir, file_name + ".zip"), "wb") as archive:
TypeError: unsupported operand type(s) for +: 'I18n_String' and 'str'

Process finished with exit code 1
```
It does seem an issue with I18n and string concatenation.

**Comment by johnatawnclementawn** [comment]
Resolved in #9609
