### ISSUE TITLE
Bug with resource instance select when relationship is null/missing

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#9684]
I'm experimenting with creating and editing conservation science data using AFS dev/7.4.x 

I ran into a problem with some of the UI for editing a "Physical Thing" resource instance, "Production Event of Object" branch. 

My browser console tracked out 24+ console errors. I'm including a small part of this (not the easiest thing to copy and past here):
```

WebSocketClient.js:21 WebSocket connection to 'ws://127.0.0.1:8080/ws' failed: 
WebSocketClient @ WebSocketClient.js:21
initSocket @ socket.js:32
eval @ index.js:321
./media/node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=8080&pathname=%2Fws&logging=info&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true @ editor.js:14886
__webpack_require__ @ editor.js:16282
(anonymous) @ editor.js:17536
(anonymous) @ editor.js:17541
execCb @ require.js:1696
check @ require.js:883
enable @ require.js:1176
init @ require.js:788
(anonymous) @ require.js:1460
index.js:561 [webpack-dev-server] Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
logger @ index.js:561
eval @ index.js:730
error @ index.js:180
WebSocketClient.client.onerror @ WebSocketClient.js:24
error (async)
WebSocketClient @ WebSocketClient.js:23
initSocket @ socket.js:32
eval @ index.js:321
./media/node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=8080&pathname=%2Fws&logging=info&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true @ editor.js:14886
__webpack_require__ @ editor.js:16282
(anonymous) @ editor.js:17536
(anonymous) @ editor.js:17541
execCb @ require.js:1696
check @ require.js:883
enable @ require.js:1176
init @ require.js:788
(anonymous) @ require.js:1460
setTimeout (async)
req.nextTick @ require.js:1815
localRequire @ require.js:1449
requirejs @ require.js:1797
(anonymous) @ editor.js:9
WebSocketClient.js:21 WebSocket connection to 'ws://127.0.0.1:8080/ws' failed: 
WebSocketClient @ WebSocketClient.js:21
initSocket @ socket.js:32
eval @ socket.js:56
index.js:561 [webpack-dev-server] Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
logger @ index.js:561
eval @ index.js:730
error @ index.js:180
WebSocketClient.client.onerror @ WebSocketClient.js:24
error (async)
WebSocketClient @ WebSocketClient.js:23
initSocket @ socket.js:32
eval @ socket.js:56
setTimeout (async)
eval @ socket.js:55
WebSocketClient.js:21 WebSocket connection to 'ws://127.0.0.1:8080/ws' failed: 
WebSocketClient @ WebSocketClient.js:21
initSocket @ socket.js:32
eval @ socket.js:56
index.js:561 [webpack-dev-server] Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
logger @ index.js:561
eval @ index.js:730
error @ index.js:180
WebSocketClient.client.onerror @ WebSocketClient.js:24
error (async)
WebSocketClient @ WebSocketClient.js:23
initSocket @ socket.js:32
eval @ socket.js:56
setTimeout (async)
eval @ socket.js:55
WebSocketClient.js:21 WebSocket connection to 'ws://127.0.0.1:8080/ws' failed: 
WebSocketClient @ WebSocketClient.js:21
initSocket @ socket.js:32
eval @ socket.js:56
index.js:561 [webpack-dev-server] Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
logger @ index.js:561
eval @ index.js:730
error @ index.js:180
WebSocketClient.client.onerror @ WebSocketClient.js:24
error (async)
WebSocketClient @ WebSocketClient.js:23
initSocket @ socket.js:32
eval @ socket.js:56
setTimeout (async)
eval @ socket.js:55
knockout-latest.js:20 Uncaught TypeError: Unable to process binding "if: function(){return !configForm  && state ==='form' }"
Message: Unable to process binding "let: function(){return {self:$data} }"
Message: Unable to process binding "if: function(){return self.displayOntologyTable }"
Message: Unable to process binding "if: function(){return relationshipsInFilter().length > 0 }"
Message: Unable to process binding "foreach: function(){return relationshipsInFilter }"
Message: Unable to process binding "if: function(){return self.node.config.graphs()[0].useOntologyRelationship }"
Message: Cannot read properties of undefined (reading 'useOntologyRelationship')
    at if (eval at parseBindingsString (knockout-latest.js:1:1), <anonymous>:3:90)
    at a.o.l (knockout-latest.js:107:381)
    at Function.xd (knockout-latest.js:59:380)
    at Function.yd (knockout-latest.js:59:66)
    at Function.ha (knockout-latest.js:58:406)
    at a.o.a.$ (knockout-latest.js:56:165)
    at init (knockout-latest.js:107:356)
    at eval (knockout-latest.js:83:50)
    at Object.K (knockout-latest.js:45:458)
    at eval (knockout-latest.js:83:31)
if @ VM7288:3

```
Lot's more console log stuff....
```

VM7288:3 Uncaught (in promise) TypeError: Unable to process binding "foreach: function(){return relationshipsInFilter }"
Message: Unable to process binding "if: function(){return self.node.config.graphs()[0].useOntologyRelationship }"
Message: Cannot read properties of undefined (reading 'useOntologyRelationship')
    at if (eval at parseBindingsString (knockout-latest.js:1:1), <anonymous>:3:90)
    at a.o.l (knockout-latest.js:107:381)
    at Function.xd (knockout-latest.js:59:380)
    at Function.yd (knockout-latest.js:59:66)
    at Function.ha (knockout-latest.js:58:406)
    at a.o.a.$ (knockout-latest.js:56:165)
    at init (knockout-latest.js:107:356)
    at eval (knockout-latest.js:83:50)
    at Object.K (knockout-latest.js:45:458)
    at eval (knockout-latest.js:83:31)
if @ VM7288:3
```
Lot's more console log stuff....

Here's  a screenshot of what it looks like in the UI:

![afs-physical-thing-resource-instance-edit-v7_4_x-ui-bug](https://github.com/archesproject/arches-for-science-prj/assets/1286742/67395e9b-3480-4731-803c-58911ea37685)

**Comment by aarongundel** [comment]
This is an arches core issue related to changes in the resource instance select widget.  Currently the check blows up when an ontology relationship is null/undefined - it should not.
