### ISSUE TITLE
Add support for connecting to Elasticsearch via Elastic Cloud

### ISSUE THREAD

**Issue by RobOatesHistoricEngland** [archesproject/arches#9850]
Whilst looking in to #9700, HE have a requirement to connect to Elasticsearch 8.x via Elastic Cloud. Specifying the Cloud ID and API Key such as...

```python
ELASTICSEARCH_CONNECTION_OPTIONS = {
    "cloud_id": "<CLOUD_ID>",
    "api_key": "<API_KEY>",
}
```
...is not sufficient. An obscure error message results:

```
[31/Jul/2023 06:53:01] "GET /search_component_data/advanced-search HTTP/1.1" 200 44595
2023-07-31 06:53:01,801 arches.app.search.search ERROR    2023-07-31 06:53:01.801778: WARNING: search failed for query: {'bool': {'should': [], 'must': [], 'must_not': [], 'filter': [{'terms': {'graph_id': ['5e8dcba3-3ac8-11eb-b1c6-c0b8832fa043', '1fe4bf71-3a3c-11eb-8023-c0b8832fa043', 'ff623370-fa12-11e6-b98b-6c4008b05c4c', '86cd5919-45c3-4ef7-9557-d39ceb85210f']}}]}} 
Exception detail: memoryview: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/web_root/arches/arches/app/search/search.py", line 151, in search
    ret = self.es.search(**kwargs).body
  File "/root/.local/lib/python3.9/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/elasticsearch/_sync/client/__init__.py", line 3863, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/root/.local/lib/python3.9/site-packages/elasticsearch/_sync/client/_base.py", line 285, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/root/.local/lib/python3.9/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/root/.local/lib/python3.9/site-packages/elastic_transport/_node/_http_urllib3.py", line 157, in perform_request
    body_to_send = gzip.compress(body)
  File "/usr/local/lib/python3.9/gzip.py", line 548, in compress
    f.write(data)
  File "/usr/local/lib/python3.9/gzip.py", line 284, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'
```
Transpires that the serialized query object needs to be UTF-8 encoded.

It is proposed the `SearchEngine` class instructs the `JSONSerializer` to return a UTF-8 encoded response.

**Comment by RobOatesHistoricEngland** [comment]
@apeters @chiatt Any feedback on this and #9700?

**Comment by apeters** [comment]
@RobOatesHistoricEngland This seems like a reasonable thing to do as long as it doesn't break compatibility with current installs (which I doubt it would).

**Comment by aj-he** [comment]
completed by #9860
