### ISSUE TITLE
Saving new node of type string raises 500

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#9858]
EDIT: see[ simpler reproducer](https://github.com/archesproject/arches/issues/9858#issuecomment-1673729350)

#### Reproducer ####
1. Start a new graph, choose an ontology
2. Create a node under the root
3. Click save edits: Graph Validation Error appears as expected (child node doesn't define ontology)
4. Discard edits.
5. Edit the data type of the child node to something other than semantic.
6. Save edits.
7. Create new node under root.
8. Publish graph.
9. Navigate to Add Resource Instances
10. Click browser back button.

#### Result ####
```py
Traceback (most recent call last):
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/jwalls/prj/arches/arches/app/views/graph.py", line 518, in post
    card = Card(data)
  File "/Users/jwalls/prj/arches/arches/app/models/card.py", line 165, in __init__
    widget_model.save()
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/jwalls/prj/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "cards_x_nodes_x_widgets_nodeid_cardid_widgetid_976dc542_uniq"
DETAIL:  Key (nodeid, cardid, widgetid)=(78003bdc-307c-11ee-9042-1ea1ac521291, c454da8b-b0c4-4f01-9d44-806bc493e729, 10000000-0000-0000-0000-000000000001) already exists.

[01/Aug/2023 10:02:59] "POST /card/c454da8b-b0c4-4f01-9d44-806bc493e729 HTTP/1.1" 500 214438
```

#### Version ####
7.4

https://github.com/archesproject/arches/assets/38668450/c4c4366e-01dc-48ef-8334-9c2ffdc873bd

**Comment by chiatt** [comment]
It seems like the fundamental problem is that the first node was allowed to be saved without an ontology class - despite the error. If the graph has an ontology, we shouldn't allow a user to save the datatype of a node that doesn't have an ontology class. That node really shouldn't even exist.

**Comment by jacobtylerwalls** [comment]
@chiatt That makes sense, however I think it's important to observe that in step 1 I haven't clicked "Save Changes" yet. So when adding the first node (in step 2), I'm adding a node without an ontology to a top node without an ontology, which is okay. Editing the top node at a later point to take an ontology would not be okay (and isn't even permitted in the UI, because the dropdown is disabled).

In Step 4 I discard changes anyway, so through step 4 I think all is just fine.
