### ISSUE TITLE
IntegrityError when saving two new collections in the RDM

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#9870]
### To reproduce ###
1. From the RDM, add a new collection.
2. Repeat step 1

### Version ###
7.4 dev

### Traceback ###
```py
afs7             | Internal Server Error: /concepts/
afs7             | Traceback (most recent call last):
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 581, in get_or_create
afs7             |     return self.get(**kwargs), False
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
afs7             |     raise self.model.DoesNotExist(
afs7             | arches.app.models.models.Concept.DoesNotExist: Concept matching query does not exist.
afs7             | 
afs7             | During handling of the above exception, another exception occurred:
afs7             | 
afs7             | Traceback (most recent call last):
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
afs7             |     return self.cursor.execute(sql, params)
afs7             | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "concepts_legacyoid_key"
afs7             | DETAIL:  Key (legacyoid)=(New Collection 1) already exists.
afs7             | 
afs7             | 
afs7             | The above exception was the direct cause of the following exception:
afs7             | 
afs7             | Traceback (most recent call last):
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
afs7             |     response = get_response(request)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
afs7             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
afs7             |     return view_func(request, *args, **kwargs)
afs7             |   File "/web_root/arches/arches/app/views/concept.py", line 245, in concept
afs7             |     concept.save()
afs7             |   File "/web_root/arches/arches/app/models/concept.py", line 263, in save
afs7             |     concept, created = models.Concept.objects.get_or_create(
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
afs7             |     return getattr(self.get_queryset(), name)(*args, **kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 588, in get_or_create
afs7             |     return self.create(**params), True
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
afs7             |     obj.save(force_insert=True, using=self.db)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
afs7             |     self.save_base(using=using, force_insert=force_insert,
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
afs7             |     updated = self._save_table(
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
afs7             |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
afs7             |     return manager._insert(
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
afs7             |     return getattr(self.get_queryset(), name)(*args, **kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
afs7             |     return query.get_compiler(using=using).execute_sql(returning_fields)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
afs7             |     cursor.execute(sql, params)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
afs7             |     return super().execute(sql, params)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
afs7             |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
afs7             |     return executor(sql, params, many, context)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
afs7             |     with self.db.wrap_database_errors:
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
afs7             |     raise dj_exc_value.with_traceback(traceback) from exc_value
afs7             |   File "/root/.local/lib/python3.10/
afs7             | site-packages/django/db/backends/utils.py", line 84, in _execute
afs7             |     return self.cursor.execute(sql, params)
afs7             | django.db.utils.IntegrityError: duplicate key value violates unique constraint "concepts_legacyoid_key"
afs7             | DETAIL:  Key (legacyoid)=(New Collection 1) already exists.
afs7             | 
afs7             | [04/Aug/2023 14:23:31] "POST /concepts/ HTTP/1.1" 500 210201
```

**Comment by jacobtylerwalls** [comment]
Can no longer reproduce on 7.4 or 7.5. Will reopen if I see it again.

**Comment by jacobtylerwalls** [comment]
Whoops, I was expecting a UI error, turns out the error surfaces server-side only. Reopening.
