### ISSUE TITLE
GET /resource/related raises 500 when there are no related resources

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#9916]
### To reproduce ###
1. Create a model with no related resources
2. Publish
3. Create an instance
4. From resource editor, click "Related Resources" in left sidebar

### Traceback ###
```py
afs7             | 2023-08-14 14:13:09,621 arches.app.search.search ERROR    2023-08-14 14:13:09.621253: WARNING: search failed for query: {'bool': {'should': [], 'must': [{'nested': {'path': 'permissions', 'query': {'terms': {'permissions.users_with_no_access': ['6']}}}}], 'must_not': [], 'filter': []}} 
afs7             | Exception detail: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: [nested] failed to find nested object under path [permissions]')
afs7             | Traceback (most recent call last):
afs7             |   File "/web_root/arches/arches/app/search/search.py", line 149, in search
afs7             |     ret = self.es.search(**kwargs).body
afs7             |   File "/root/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
afs7             |     return api(*args, **kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 3863, in search
afs7             |     return self.perform_request(  # type: ignore[return-value]
afs7             |   File "/root/.local/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
afs7             |     raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
afs7             | elasticsearch.BadRequestError: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: [nested] failed to find nested object under path [permissions]')
afs7             | Internal Server Error: /resource/related/be53b834-2dea-4bfc-8551-9efa1dcd7d13
afs7             | Traceback (most recent call last):
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
afs7             |     response = get_response(request)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
afs7             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
afs7             |     return self.dispatch(request, *args, **kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
afs7             |     return bound_method(*args, **kwargs)
afs7             |   File "/web_root/arches/arches/app/utils/decorators.py", line 100, in wrapper
afs7             |     return function(request, *args, **kwargs)
afs7             |   File "/root/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
afs7             |     return handler(request, *args, **kwargs)
afs7             |   File "/web_root/arches/arches/app/views/resource.py", line 873, in get
afs7             |     related_resources = resource.get_related_resources(
afs7             |   File "/web_root/arches/arches/app/models/resource.py", line 668, in get_related_resources
afs7             |     restricted_instances = get_restricted_instances(user, se) if user is not None else []
afs7             |   File "/web_root/arches/arches/app/utils/permission_backend.py", line 108, in get_restricted_instances
afs7             |     scroll_id = results["_scroll_id"]
afs7             | TypeError: 'NoneType' object is not subscriptable
afs7             | [14/Aug/2023 14:13:09] "GET /resource/related/be53b834-2dea-4bfc-8551-9efa1dcd7d13?page=1 HTTP/1.1" 500 141256
```

### Version ###
7.5 dev

**Comment by chiatt** [comment]
Maybe related https://github.com/archesproject/arches/issues/11395
