### ISSUE TITLE
IIIF views swallow errors and return None

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#9986]
Several views in the `ManifestManagerView` swallow exceptions and return `None`, which just cause generic Django errors instead (`ValueError: The view ... didn't return an HttpResponse object. It returned None instead.`)

```py
2023-09-01 11:05:07 Internal Server Error: /image-service-manager
2023-09-01 11:05:07 Traceback (most recent call last):
2023-09-01 11:05:07   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
2023-09-01 11:05:07     response = get_response(request)
2023-09-01 11:05:07   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
2023-09-01 11:05:07     self.check_response(response, callback)
2023-09-01 11:05:07   File "/root/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
2023-09-01 11:05:07     raise ValueError(
2023-09-01 11:05:07 ValueError: The view arches.app.views.manifest_manager.view didn't return an HttpResponse object. It returned None instead.
```

**Comment by jacobtylerwalls** [comment]
Fixed in #10046
